someengineering/fixinventory

plugins/vsphere/resoto_plugin_vsphere/__init__.py
plugins/vsphere/resoto_plugin_vsphere/resources.py

add new features to the vSphere graph including clusters, DCs and datastores
- Fixes #XXXX

Improved vSphere graph

---

resotocore/resotocore/cli/cli.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/query/model.py
resotocore/resotocore/report/__init__.py
resotocore/resotocore/report/inspector_service.py
resotocore/resotocore/report/report_config.py
resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/static/report/benchmark/aws/aws_cis_1.5.json
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/query/model_test.py
resotocore/tests/resotocore/report/inspector_service_test.py

[resotocore][feat] Filter report by account and return results aggregated by account

---

plugins/aws/tools/awspolicygen/awspolicygen/gen.py

Add pricing policy to cf template export

[plugins/aws][fix] Add pricing policy to cf template export

---

resotoshell/resotoshell/shell.py

[resotoshell][fix] No dot in download log line

---

plugins/vsphere/resoto_plugin_vsphere/__init__.py

Fix an indentation issue in vSphere collection where esxi host objects are added multiple times due to it being called for every datastore
- Fixes #XXXX

FIX: duplicate host error. Bad indentation

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/gcp/resoto_plugin_gcp/resources/base.py
plugins/k8s/resoto_plugin_k8s/resources.py

Affected Builders:
- k8s
- aws
- gcp

[resoto][fix] Make GraphBuilder thread safe

---

resotoworker/resotoworker/collect.py

Rename cluster_graph -> collector_graph

[resotoworker][fix] Rename cluster_graph -> collector_graph

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/configuration.py
plugins/aws/test/configuration_test.py

Temporary workaround for memory leak in AWS collector

[plugins/aws][fix] Temporary workaround for memory leak in AWS collector

---

plugins/aws/resoto_plugin_aws/resource/ec2.py

[aws][fix] ElasticIp.id should be PublicIp

---

resotocore/requirements.txt

[resotocore][feat] Bump UI version to 3.2.5

---

resotolib/resotolib/config.py

Fixed a bug where configuration changes made by a plugin were not sent back to the core.
- Fixes #XXXX

[resotolib][fix] Correctly apply default config in resotolib

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/test/aws_client_test.py

Adjust retry setting to wait max 5 minutes.

[aws][fix] Adjust retry settings to wait max 5 minutes

---

resotolib/resotolib/config.py
resotolib/resotolib/utils.py
resotolib/test/test_utils.py

Fixed a bug where a removed property stayed in the configuration.
- Fixes #XXXX

[resotolib][fix] Drop deleted config props

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/configuration.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/elb.py
plugins/aws/resoto_plugin_aws/resource/elbv2.py
plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/test/aws_client_test.py
plugins/aws/test/collector_test.py
plugins/aws/test/configuration_test.py
plugins/aws/test/resources/base_test.py

[aws][feat] Use a single ExecutorQueue

---

resotoshell/resotoshell/shell.py

[resotoshell][fix] Write file should overwrite existing file

---

plugins/aws/resoto_plugin_aws/resource/base.py
resotolib/resotolib/lock.py

The read/write lock might improve access time to the graph, since it allows multiple reader in parallel.

[aws][feat] Use a read/write lock instead of a simple lock

---

resotocore/resotocore/analytics/__init__.py
resotocore/resotocore/report/inspector_service.py

Send an Analytics event when a benchmark is performed.

[resotocore][feat] Analytics event when a benchmark is performed

---

resotocore/resotocore/cli/cli.py

[resotocore][fix] Only access first command if defined

---

plugins/gcp/Makefile
plugins/gcp/resoto_plugin_gcp/__init__.py
plugins/gcp/resoto_plugin_gcp/gcp_client.py
plugins/gcp/resoto_plugin_gcp/resources/base.py
plugins/gcp/resoto_plugin_gcp/resources/billing.py
plugins/gcp/resoto_plugin_gcp/resources/compute.py
plugins/gcp/resoto_plugin_gcp/resources/container.py
plugins/gcp/resoto_plugin_gcp/resources/sqladmin.py
plugins/gcp/setup.cfg
plugins/gcp/test/conftest.py
plugins/gcp/test/random_client.py
plugins/gcp/test/test_billing.py
plugins/gcp/test/test_compute.py
plugins/gcp/test/test_config.py
plugins/gcp/test/test_container.py
plugins/gcp/test/test_sqladmin.py
plugins/gcp/tools/model_gen.py
plugins/gcp/tox.ini
resotolib/resotolib/baseresources.py

Rename GCP property names by removing the prefix.
Also enable mypy.

[gcp][feat] Use plain property names and enable mypy

---

resotolib/resotolib/config.py
resotolib/resotolib/utils.py
resotolib/test/test_config.py
resotolib/test/test_utils.py

Fixed a bug where an empty default config can erase the user-defined values.
- Fixes #XXXX

[resotolib][fix] Fix the config deletion bug

---

resotocore/requirements.txt

[resotocore][feat] Bump UI version to 3.2.6

---

resotocore/resotocore/report/report_config.py
resotocore/resotocore/static/report/benchmark/aws/aws_cis_1_5.json
resotocore/resotocore/static/report/benchmark_template.json

Defining id and file name does not make sense.

[resotocore][fix] Benchmark id is defined by the file name

---

resotocore/resotocore/model/model.py
resotolib/resotolib/graph/__init__.py

Add exported_at timestamp to account nodes

[resotolib][feat] Add exported_at timestamp to account nodes

---

plugins/github/resoto_plugin_github/__init__.py
plugins/github/resoto_plugin_github/resources.py

Extend  Github Repo with:
- clones_traffic
- views_traffic
- top_referrers
- top_paths
- contributors_count

[plugins/github][feat] Add repository statistics

---

plugins/aws/resoto_plugin_aws/resource/base.py
resotolib/resotolib/baseresources.py
resotolib/resotolib/core/model_export.py

[resotolib][chore] Refactor node json generation

---

resotoshell/resotoshell/promptsession.py

[resotoshell][feat] Also complete command aliases

---

resotocore/resotocore/db/graphdb.py
resotocore/resotocore/model/model.py
resotocore/tests/resotocore/db/graphdb_test.py
resotocore/tests/resotocore/model/model_test.py

[resotocore][feat] Compute derived properties in metadata section

---

resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/config.py
resotoworker/resotoworker/utils.py
resotoworker/test/test_utils.py

Added a feature that allows saving files to the resotoworker's home directory by defining them in the configuration.
- Fixes #XXXX

[resotoworker][feat] Save files to home dir via config

---

resotocore/requirements.txt
resotocore/resotocore/infra_apps/manifest.py
resotocore/tox.ini

One part of the infrastructure apps series. The application manifest.
- Fixes #XXXX

[resotocore][feat] Infrastructure apps - app manifest

---

resotocore/resotocore/web/api.py

[resotocore][fix] Keep connections only for 5 seconds

---

resotocore/resotocore/web/api.py
resotocore/resotocore/web/tsdb.py

- increase retry
- add exponential backoff
- retry on 400 only if the content-length is zero or none

[resotocore][fix] Retry with backoff on empty BadRequest

---

resotocore/requirements.txt

[resotocore][chore] Bump UI 3.3.0

---

.devcontainer/Dockerfile
.devcontainer/docker-compose.yml

Added the docker volume to keep the devcontainer bash history between container rebuilds.
- Fixes #XXXX

[devcontainer][feat] Keep the bash history

---

resotocore/requirements.txt

[resotocore][fix] Bump UI to 3.3.1

---

docker-compose.yaml

Pick up exported AWS credentials from ENV and make them available to the worker.

[docker][feat] Pass temporary AWS credentials

---

plugins/gcp/resoto_plugin_gcp/resources/compute.py
plugins/gcp/test/files/disk_type.json
plugins/gcp/test/files/skus.json
plugins/gcp/test/test_compute.py
plugins/gcp/test/test_project_collector.py

OnDemand cost information for GcpDiskType

[gcp][feat] OnDemand cost information for GcpDiskType

---

Dockerfile.resotobase

[docker][chore] Bump base image

---

resotocore/resotocore/model/model.py
resotolib/resotolib/core/model_export.py
resotoworker/resotoworker/config.py

[resotocore][feat] Model allows metadata on properties

---

resotocore/resotocore/__main__.py
resotocore/resotocore/cli/cli.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/cli/model.py
resotocore/resotocore/infra_apps/local_runtime.py
resotocore/resotocore/infra_apps/package_manager.py
resotocore/resotocore/infra_apps/runtime.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/conftest.py
resotocore/tests/resotocore/infra_apps/local_runtime_test.py
resotocore/tests/resotocore/infra_apps/package_manager_test.py

Wired together different parts of the infrastructure apps.
- Fixes #XXXX

[resotocore][feat] Enable Infrastsucture Apps

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/db/packagedb.py
resotocore/resotocore/infra_apps/package_manager.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/infra_apps/package_manager_test.py

Added support for searching an infra app index
- Fixes #XXXX

[resotocore][feat] Support search for infra apps

---

plugins/github/resoto_plugin_github/__init__.py
plugins/github/resoto_plugin_github/config.py
plugins/github/resoto_plugin_github/resources.py
plugins/onelogin/resoto_plugin_onelogin/__init__.py

Add support for GitHub pull requests.

[plugins/github][feat] Add support for pull requests

---

.github/workflows/publish.yml

Turn on example collector for model generation

[github][fix] Turn on example collector for model generation

---

plugins/gcp/resoto_plugin_gcp/resources/compute.py
plugins/gcp/resoto_plugin_gcp/resources/sqladmin.py
plugins/gcp/tools/model_gen.py

Fix the model generator and fix the model.

[gcp][fix] Fix datetime that should be string

---

.devcontainer/Dockerfile
resotocore/resotocore/analytics/__init__.py
resotocore/resotocore/db/async_arangodb.py
resotocore/resotocore/db/graphdb.py
resotocore/tests/resotocore/db/graphdb_test.py

GraphDB now supports creating a copy of it with a different name
- Fixes #XXXX

[resotocore][feat] Resoto Snapshots: support graph copy

---

resotolib/resotolib/jwt.py
resotolib/resotolib/x509.py
resotolib/test/test_jwt.py
resotolib/test/test_x509.py

Add JWT and x509 functions to use PKI with JWTs

[resotolib][feat] Add JWT and x509 functions to use PKI with JWTs

---

resotocore/resotocore/model/model_handler.py

[resotocore][fix] Fix the model kind handling for legacy implementation

---

resotolib/resotolib/jwt.py
resotolib/resotolib/x509.py
resotolib/test/test_jwt.py

Allow encoding the certificate fingerprint into JWT

[resotolib][feat] Allow encoding the certificate fingerprint into JWT

---

resotocore/resotocore/infra_apps/local_runtime.py
resotolib/resotolib/core/search.py

Use default graph section in searches.
Also uses graph search for infra apps.

[resotolib][feat] Use default graph section in searches

---

resotocore/resotocore/infra_apps/local_runtime.py
resotolib/resotolib/durations.py

[resotolib][feat] Add optional duration parsing

---

resotocore/resotocore/cli/cli.py
resotocore/tests/resotocore/cli/command_test.py

The adjusted context was not provided to the rewritten parts of the command line.
A test was added to ensure proper behavior.

[resotocore][fix] Default list output does not show selected attributes

---

resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py

[resotocore][fix] Model API

---

resotoworker/resotoworker/utils.py
resotoworker/test/test_utils.py

Create path of `write_files_to_home_dir` config files

[resotoworker][fix] Create path of `write_files_to_home_dir` config files

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/config/__init__.py
resotocore/resotocore/config/config_handler_service.py
resotocore/resotocore/message_bus.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/config/config_handler_service_test.py

Added a config copy command 
- Fixes #XXXX

[resotocore][feat] Config copy command

---

resotocore/resotocore/web/api.py
resotolib/resotolib/asynchronous/utils.py
resotolib/resotolib/utils.py
resotolib/test/asynchronous/test_utils.py
resotolib/test/test_utils.py

Add `stdin_generator` functions.
Also adds tests to the already existing `async_lines` function.

[resotolib][feat] Add `stdin_generator` functions

---

resotoworker/resotoworker/utils.py
resotoworker/test/test_utils.py

Write home directory files securely

[resotoworker][fix] Write home directory files securely

---

plugins/gcp/resoto_plugin_gcp/resources/compute.py

Fix wrong edge direction instance->disk

[plugins/gcp][fix] Fix wrong edge direction instance->disk

---

.github/workflows/publish.yml
tools/release_notes.py

Updates to CI & release notes script due to changes in someengineering/resoto.com#692

[ci][chore] Update publish CI workflow to reflect website changes

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/graph_manager/graph_manager.py
resotocore/resotocore/web/api.py

[resotocore][fix] Serve debug endpoints only when debug is enabled

---

resotocore/resotocore/__main__.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/config/core_config_handler.py
resotocore/resotocore/core_config.py
resotocore/resotocore/db/arango_query.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/graph_manager/graph_manager.py
resotocore/resotocore/task/__init__.py
resotocore/resotocore/task/task_handler.py
resotocore/resotocore/util.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/config/core_config_handler_test.py
resotocore/tests/resotocore/conftest.py
resotocore/tests/resotocore/db/arango_query_test.py
resotocore/tests/resotocore/graph_manager/graph_manager_test.py
resotocore/tests/resotocore/task/job_handler_test.py
resotocore/tests/resotocore/task/task_handler_test.py
resotocore/tests/resotocore/web/api_test.py

Do graph snapshots based on cron expression schedule.
- Fixes #XXXX

[resotocore][feat] Automated Graph Snapshots

---

Dockerfile.resotobase

Build all Python packages in one go so pip can look at all dependencies at the same time.

[docker][fix] Build all Python packages in one go

---

plugins/digitalocean/resoto_plugin_digitalocean/collector.py

Fixed region handling when collecting snapshots
- Fixes #XXXX

[plugins/digitalocean][fix] Fix region extraction

---

resotocore/resotocore/report/report_config.py
resotocore/resotocore/task/task_description.py

Updating a benchmark configuration has thrown an error - this is now possible.

[resotocore][fix] Allow benchmark configuration change

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/files/ec2/describe-volumes.json

[aws][fix] Always set atime/mtime for ec2 volumes

---

plugins/gcp/resoto_plugin_gcp/project_collector.py
resotolib/resotolib/baseresources.py

Remove redundant core feedback calls and make some cleanup info log

[resotoworker/gcp][fix] Remove redundant core feedback calls and make some cleanup info log

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/infra_apps/local_runtime.py
resotocore/resotocore/infra_apps/manifest.py
resotocore/resotocore/infra_apps/package_manager.py
resotocore/resotocore/infra_apps/runtime.py
resotocore/tests/resotocore/infra_apps/local_runtime_test.py
resotocore/tests/resotocore/infra_apps/package_manager_test.py

[resotocore][fix] Fix the argument handling for the infrastructure apps

---

resotocore/resotocore/infra_apps/local_runtime.py

[resotocore][fix] Fix kwargs

---

resotoshell/resotoshell/authorized_client.py

Create the .resoto directory if it does not exist.

[resotocore][fix] Create parent directory if not existent

---

resotocore/resotocore/cli/model.py
resotocore/resotocore/infra_apps/local_runtime.py
resotocore/resotocore/infra_apps/package_manager.py
resotocore/tests/resotocore/cli/model_test.py

[resotocore][fix] Fix infra apps aliases and error reporting

---

.github/CODEOWNERS

[resoto][chore] Remove anjafr from code owners

---

.vscode/settings.json
plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/configuration.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/pricing.py
plugins/aws/resoto_plugin_aws/utils.py

Add support for non-default partitions
Note: Also reverts nm's change where vscode sorts imports as it conflicts with black's sorting.

[plugins/aws][fix] Add support for non-default partitions

---

plugins/aws/resoto_plugin_aws/aws_client.py

Propagate partition to all client calls

[plugins/aws][fix] Propagate partition to all client calls

---

plugins/gcp/resoto_plugin_gcp/resources/base.py
plugins/gcp/resoto_plugin_gcp/resources/compute.py
plugins/gcp/resoto_plugin_gcp/resources/sqladmin.py

[gcp][feat] Add missing edges

---

plugins/aws/resoto_plugin_aws/resource/pricing.py

Find pricing partition index dynamically

[plugins/aws][fix] Find pricing partition index dynamically

---

plugins/aws/resoto_plugin_aws/resource/base.py

[aws][fix] Log json if the resource can not be mapped

---

plugins/aws/resoto_plugin_aws/resource/cloudwatch.py
plugins/aws/resoto_plugin_aws/resource/ec2.py

[aws][fix] Detach Network interface before cleanup and correct LogGroup service

---

plugins/aws/resoto_plugin_aws/resource/sagemaker.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/sagemaker/describe-artifact__arn_aws_sagemaker_us_east_1_test_artifact_2.json
plugins/aws/test/resources/files/sagemaker/list-artifacts.json
plugins/aws/test/resources/sagemaker_test.py

[aws][fix] AWS Artifacts are referenced by arn not name

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/configuration.py
plugins/aws/resoto_plugin_aws/resource/apigateway.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/cloudformation.py
plugins/aws/resoto_plugin_aws/resource/cognito.py
plugins/aws/resoto_plugin_aws/resource/ecs.py
plugins/aws/resoto_plugin_aws/resource/eks.py
plugins/aws/resoto_plugin_aws/resource/glacier.py
plugins/aws/resoto_plugin_aws/resource/iam.py
plugins/aws/resoto_plugin_aws/resource/route53.py
plugins/aws/resoto_plugin_aws/resource/service_quotas.py
plugins/aws/resoto_plugin_aws/resource/sns.py
plugins/aws/test/collector_test.py
plugins/aws/test/configuration_test.py

[aws][fix] Make sure all services have service names

---

.devcontainer/Dockerfile
plugins/k8s/resoto_plugin_k8s/resources.py
plugins/k8s/test/collector_test.py
plugins/k8s/test/files/apis_networking.k8s.io_v1_ingresses.json
plugins/k8s/test/resources_test.py

[plugins/k8s][feat] Store LB backends when collecting ingress

---

plugins/gcp/resoto_plugin_gcp/resources/base.py
plugins/gcp/resoto_plugin_gcp/resources/compute.py
plugins/k8s/resoto_plugin_k8s/base.py
plugins/k8s/resoto_plugin_k8s/resources.py
plugins/k8s/test/fixtures.py
plugins/k8s/test/resources_test.py
resotolib/resotolib/baseresources.py
resotolib/resotolib/config.py
resotolib/resotolib/core/model_export.py
resotolib/resotolib/core/tasks.py
resotolib/resotolib/graph/__init__.py
resotolib/resotolib/json.py
resotolib/test/core/model_export_test.py
resotolib/test/test_json.py
resotometrics/resotometrics/config.py
resotoshell/resotoshell/promptsession.py

Plugin json serialization was a mixture of jsons / cattrs / hand-written logic.
This PR tries to unify handling to use cattrs always.
ResotoCore has still a lot of custom jsons handling which should be replaced in a subsequent PR.

[resoto][fix] Cleanup cattrs/jsons complexity

---

plugins/k8s/resoto_plugin_k8s/resources.py
plugins/k8s/test/files/api_v1_services.json
plugins/k8s/test/resources_test.py
resotolib/resotolib/json_bender.py
resotolib/test/json_bender_test.py

Made a k8s service a load balancer too
- Fixes #XXXX

[plugins/k8s][feat] Make KubernetesService a load balancer

---

resotocore/resotocore/cli/model.py
resotocore/tests/resotocore/cli/model_test.py

[resotocore][fix] arg names without `--`

---

resotoshell/resotoshell/promptsession.py
resotoshell/test/test_promptsession.py

[resotoshell][fix] Parse argument commands

---

resotocore/resotocore/config/__init__.py
resotocore/resotocore/core_config.py
resotocore/resotocore/report/report_config.py
resotocore/resotocore/user/__init__.py
resotolib/resotolib/config.py
resotolib/resotolib/core/model_export.py

[resotocore][fix] Empty collectors yield an error

---

resotocore/resotocore/cli/command.py

[resotocore][fix] Document all cmd line parameters of report

---

requirements-all.txt
requirements-dev.txt
requirements-test.txt
requirements.txt
resotolib/pyproject.toml

[resotolib][fix] Update dependencies

---

resotocore/.pylintrc
resotocore/resotocore/__main__.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/db/arango_query.py
resotocore/resotocore/graph_manager/graph_manager.py
resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/graph_manager/graph_manager_test.py
resotocore/tests/resotocore/web/api_test.py

Now it is possible to search the graph at specific points in time by providing a timestamp with an --at flag.
- Fixes #XXXX

[resotocore][feat] --at support for the search command

---

.devcontainer/Dockerfile
resotocore/resotocore/cli/cli.py
resotocore/tests/resotocore/cli/command_test.py

Fixed the source position detection by adding an offset to the enumerator.
- Fixes #XXXX

[resotocore][fix] Allow piping output into an infra app

---

resotocore/resotocore/cli/command.py

Wrapped the stream into a generator function to stop it from complaining.
- Fixes #XXXX

[resotocore][fix] Remove warning about the iterating outside of the streaming context

---

.github/workflows/check_pr_plugin_aws.yml
.github/workflows/check_pr_plugin_gcp.yml
.github/workflows/publish.yml

Required changes for someengineering/resoto.com#752

[ci][chore] Update CI to process GCP policies

---

resotolib/resotolib/json.py
resotolib/resotolib/logger.py

[resotolib][chore] debug -> trace

---

plugins/digitalocean/resoto_plugin_digitalocean/collector.py

Now we fill the instance type on the droplets.
- Fixes #XXXX

[plugins/digitalocean][fix] Store the droplet's instance type

---

plugins/digitalocean/resoto_plugin_digitalocean/client.py
plugins/digitalocean/resoto_plugin_digitalocean/collector.py
plugins/digitalocean/resoto_plugin_digitalocean/resources.py
plugins/digitalocean/resoto_plugin_digitalocean/utils.py
plugins/digitalocean/test/test_collector.py
resotolib/resotolib/baseresources.py
resotolib/resotolib/json.py

Collect all tags where possible, do not store them as resources and correctly handle the null values of tags.
- Fixes #XXXX

[plugins/digitalocean][fix] DigitalOcean tagging fixes

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/utils.py
plugins/aws/test/test_utils.py

If the user provides a credentials file to Resoto without specifying the profiles, try to use all profiles by default.

[aws][feature] Read the list of profiles from credentials file

---

.github/workflows/check_pr_resotoshell.yml

This should create a homebrew tap PR when a new resoto shell is released.

[resotoshell][feat] Add brew trigger workflow

---

plugins/digitalocean/resoto_plugin_digitalocean/__init__.py
plugins/digitalocean/resoto_plugin_digitalocean/config.py

[plugins/digitalocean][fix] Make config easier to work with

---

resotolib/resotolib/config.py
resotolib/resotolib/core/actions.py
resotolib/resotolib/core/events.py
resotolib/resotolib/core/tasks.py
resotolib/resotolib/web/metrics.py
resotoworker/resotoworker/__main__.py

Health Check for ResotoWorker that takes the connection status of the worker into account

[resotoworker][feat] Health check takes connection to core into account

---

resotocore/resotocore/db/db_access.py

[resotocore][feat] Do not migrate snapshots on startup

---

plugins/gcp/resoto_plugin_gcp/__init__.py
plugins/gcp/resoto_plugin_gcp/utils.py

[feat][gcp] Reveal credential errors

---

requirements-all.txt
requirements-dev.txt
requirements-test.txt
requirements.txt

Update resotoui package to last version

[resoto][chore] Bump UI version

---

.github/workflows/publish.yml

[ci][fix] Add current helm chart version to GH output

---

.github/workflows/publish_homebrew.yml

[ci][fix] Do not run on merge

---

.devcontainer/Dockerfile
.vscode/launch.json
plugins/aws/resoto_plugin_aws/__init__.py

[plugins/aws][fix] Use a real aws cli instead of translating to boto3 APIs

---

plugins/gcp/resoto_plugin_gcp/collector.py
plugins/gcp/resoto_plugin_gcp/gcp_client.py
plugins/gcp/resoto_plugin_gcp/resources/base.py
plugins/gcp/resoto_plugin_gcp/resources/compute.py
plugins/gcp/test/files/database_instance.json
plugins/gcp/test/random_client.py
plugins/gcp/test/test_compute.py
plugins/gcp/test/test_sqladmin.py

[gcp][fix] Zonal Handling, Resource removal and speed improvements

---

plugins/gcp/resoto_plugin_gcp/resources/base.py
plugins/gcp/test/files/gcp_regions.json
plugins/gcp/test/test_base.py
resotolib/resotolib/json_bender.py

[gcp][feat] Introduce regional quotas.

---

resotocore/resotocore/db/graphdb.py
resotocore/resotocore/graph_manager/graph_manager.py
resotocore/tests/resotocore/db/graphdb_test.py

[resotocore][fix] Do not create unnecessary collections when making snapshots

---

resotocore/resotocore/core_config.py

[resoto][chore] Update PlantUML address

---

resotocore/resotocore/report/__init__.py
resotocore/resotocore/report/report_config.py

[resotocore][fix] ReportCheck related is optional

---

requirements-all.txt
requirements-extra.txt
requirements-test.txt
requirements.txt

[resoto][chore] Bump UI version to 3.6.3

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/configuration.py
plugins/aws/resoto_plugin_aws/utils.py

Allow assuming role for org scraping

[plugins/aws][fix] Allow assuming role for org scraping

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/gcp/resoto_plugin_gcp/__init__.py
plugins/k8s/resoto_plugin_k8s/__init__.py
plugins/onprem/resoto_plugin_onprem/__init__.py
resotolib/resotolib/proc.py

[resoto][feat] Set nice level for collectors

---

plugins/aws/resoto_plugin_aws/resource/ec2.py

[plugins/aws] fix the missing utilizaton metrics

---

resotocore/resotocore/model/model.py
resotocore/resotocore/query/template_expander.py
resotocore/tests/resotocore/query/template_expander_test.py
resotolib/resotolib/core/model_check.py
resotolib/resotolib/core/model_export.py
resotolib/resotolib/graph/__init__.py
resotoshell/resotoshell/promptsession.py

Allow short forms for predicates of cloud, account, region, zone and usage.
Example:
```
search is(instance) and account~sandbox
```

[resoto][feat] Allow abbreviated names

---

.devcontainer/devcontainer.json
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/utils.py
resotocore/resotocore/db/arango_query.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/model/db_updater.py
resotocore/resotocore/model/graph_access.py
resotocore/resotocore/model/model.py
resotocore/tests/resotocore/conftest.py
resotocore/tests/resotocore/db/arango_query_test.py
resotocore/tests/resotocore/db/graphdb_test.py
resotocore/tests/resotocore/graph_manager/graph_manager_test.py
resotocore/tests/resotocore/model/graph_access_test.py

[resotocore][feat] Store usage metrics on the graph

---

resotoworker/resotoworker/collect.py
resotoworker/resotoworker/resotocore.py
resotoworker/test/test_collect.py
resotoworker/test/test_resotocore.py

[resoto][chore] Create tempdir per task id

---

requirements-all.txt
requirements-extra.txt
requirements-test.txt
requirements.txt

[resoto-ui][feat] bump UI version

---

.devcontainer/devcontainer.json
.pylintrc
.vscode/settings.json

Removed the outdated settings of pylintrc, and updated the devcontainer extensions
- Fixes #XXXX

[resoto][chore] Update pylintrc and devcontainer files

---

resotocore/resotocore/__main__.py
resotocore/resotocore/dependencies.py
resotolib/pyproject.toml

[resotocore][fix] Wrong dependency name

---

resotocore/resotocore/db/db_access.py
resotocore/resotocore/model/db_updater.py
resotocore/resotocore/model/model_handler.py
resotocore/tests/resotocore/model/db_updater_test.py
resotocore/tests/resotocore/web/api_test.py

[resotocore][fix] Use the right model during the graph merge

---

.vscode/launch.json
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/db/usagedb.py
resotocore/resotocore/model/db_updater.py
resotocore/resotocore/model/graph_access.py
resotocore/resotocore/model/model.py
resotocore/tests/resotocore/conftest.py
resotocore/tests/resotocore/db/graphdb_test.py
resotocore/tests/resotocore/graph_manager/graph_manager_test.py
resotocore/tests/resotocore/model/graph_access_test.py

[resotocore][fix] Update the graph merge mechanism, use changeid to update usage data

---

plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
resotocore/resotocore/db/graphdb.py

[resoto][fix] Fix the metrics import

---

requirements-all.txt
requirements-extra.txt
requirements-test.txt
requirements.txt

Bump UI version to 3.7.0

---

.github/workflows/publish_homebrew.yml

[publish_brew][fix] Check out repo

---

plugins/azure/pyproject.toml

[azure][fix] Update wrong version

---

resotocore/resotocore/cli/command.py
resotocore/tests/resotocore/cli/command_test.py

[resotocore][fix] Batch size and argument handling

---

resotocore/tests/resotocore/db/graphdb_test.py

[resotocore][fix] Reduce the flakiness of the graph_merge test

---

resotocore/tests/resotocore/conftest.py
resotocore/tests/resotocore/db/graphdb_test.py
resotocore/tests/resotocore/task/task_handler_test.py
resotocore/tests/resotocore/utils.py

[resotocore][chore] Refactor aio.sleep in graph_merge test

---

codecov.yml
resotolib/resotolib/utils.py

[resoto][chore] Define codecov settings

---

plugins/azure/resoto_plugin_azure/resource/compute.py
plugins/azure/tools/azure_model_gen.py

[azure][fix] Fix generator for ctime

---

plugins/azure/resoto_plugin_azure/azure_client.py
plugins/azure/resoto_plugin_azure/collector.py
plugins/azure/resoto_plugin_azure/resource/base.py
plugins/azure/resoto_plugin_azure/resource/compute.py
plugins/azure/test/collector_test.py
plugins/azure/test/compute_test.py
plugins/azure/test/conftest.py
plugins/azure/test/files/compute/vmSizes.json
plugins/azure/tools/azure_model_gen.py

Some resources can only be fetched in combination with the location.
Add handling for regional resources.
Add VirtualMachineSize as regional resource.

[azure][feat] Add location aware resource handling

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/resource/lambda_.py
plugins/aws/resoto_plugin_aws/resource/sns.py

[aws][fix] AWS client errors

---

resotolib/resotolib/proc.py
resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/collect.py

[resotolib][fix] Increase limits for all forked processes

---

codecov.yml
resotocore/.pylintrc
resotocore/resotocore/__main__.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/db/runningtaskdb.py
resotocore/resotocore/message_bus.py
resotocore/resotocore/system_start.py
resotocore/resotocore/task/__init__.py
resotocore/resotocore/task/scheduler.py
resotocore/resotocore/task/task_description.py
resotocore/resotocore/task/task_handler.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/conftest.py
resotocore/tests/resotocore/message_bus_test.py
resotocore/tests/resotocore/task/job_handler_test.py
resotocore/tests/resotocore/task/task_description_test.py
resotocore/tests/resotocore/task/task_handler_test.py
resotocore/tests/resotocore/web/api_test.py

For separate sync processes, we don't want to schedule any jobs or interfere with any running task.
Introduce flags to allow this behaviour.

[resotocore][feat] Add options to disable scheduling and ignore interrupted tasks

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/utils.py

[plugins/aws][feat] Collect cloudwatch metrics for EBS

---

resotocore/resotocore/config/config_override_service.py
resotocore/resotocore/system_start.py
resotocore/tests/resotocore/config/config_override_service_test.py

[resotocore][fix] Update config override docs and fix the validation bug

---

.github/workflows/docker-build-arm.yml
.github/workflows/publish.yml

[docker][fix] Fix out of space error

---

.github/workflows/docker-build.yml

[docker][fix] Update outdated action

---

plugins/posthog/resoto_plugin_posthog/resources.py

…
Prevent converting any type/string that is neither a valid date string nor present.

[posthog][fix] Handle/Catch a possible conversion failure

---

.vscode/extensions.json
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/elb.py
plugins/aws/resoto_plugin_aws/resource/elbv2.py

[plugins/aws] Collect ALB/ELB usage data

---

resotolib/resotolib/graph/__init__.py

Only log exceptions during dataclass validation

[resotolib][fix] Only log exceptions during dataclass validation

---

resotolib/resotolib/graph/__init__.py

Remove nodes that fail to validate from the graph

[resotolib][fix] Remove nodes that fail to validate from the graph

---

plugins/aws/resoto_plugin_aws/resource/sqs.py

[aws][fix] Use correct type

---

resotolib/resotolib/utils.py

[resotolib][fix] Function invocation in signature

---

resotocore/resotocore/db/graphdb.py
resotocore/resotocore/model/graph_access.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/__init__.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/db/graphdb_test.py
resotocore/tests/resotocore/infra_apps/local_runtime_test.py
resotocore/tests/resotocore/report/benchnmark_renderer_test.py
resotocore/tests/resotocore/report/inspector_service_test.py
resotocore/tests/resotocore/web/api_test.py

[resotocore][feat] Allow subgraph to be deleted.

---

resotocore/resotocore/task/task_description.py
resotocore/resotocore/task/task_handler.py
resotocore/tests/resotocore/message_bus_test.py
resotocore/tests/resotocore/task/task_description_test.py

[resotocore][feat] Progress end before Task end

---

resotocore/resotocore/report/inspector_service.py

[resotocore][fix] User warining for iterating streams

---

resotocore/.pylintrc
resotocore/resotocore/cli/command.py
resotocore/resotocore/db/arango_query.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/model/graph_access.py
resotocore/resotocore/model/resolve_in_graph.py
resotocore/resotocore/query/model.py
resotocore/resotocore/query/query_parser.py
resotocore/resotocore/report/__init__.py
resotocore/resotocore/report/benchmark_renderer.py
resotocore/resotocore/report/inspector_service.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/db/arango_query_test.py
resotocore/tests/resotocore/db/graphdb_test.py
resotocore/tests/resotocore/query/query_parser_test.py
resotocore/tests/resotocore/report/benchnmark_renderer_test.py
resotocore/tests/resotocore/report/inspector_service_test.py
resotoshell/resotoshell/promptsession.py

[feat][resotocore] Maintain security information in its own section.

---

plugins/azure/resoto_plugin_azure/resource/compute.py
plugins/azure/tools/azure_model_gen.py

Mappings for base classes need to be combined.

[fix][azure] Map properties of base classes

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/configuration.py

[plugins/aws] Get account name from profile

---

resotolib/resotolib/web/__init__.py

This PR adds a convenience function to the resotolib web server that allows to mount additional apps at arbitrary routes.

[resotolib][feat] Allow mounting additional apps

---

resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/web/api_test.py

[resotocore][feat] List available benchmarks

---

resotolib/resotolib/x509.py

[resotolib][chore] Refactor CA bundle generation

---

resotocore/resotocore/__main__.py
resotocore/resotocore/db/db_access.py
resotocore/resotocore/system_start.py
resotocore/resotocore/web/certificate_handler.py

[fix][resotocore] Add additional CA to bundle

---

.github/workflows/docker-build.yml

[chore][resoto] Trigger build on merge to main.

---

resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/web/api_test.py

[feat] Load checks by id

---

resotocore/resotocore/model/resolve_in_graph.py
resotocore/tests/resotocore/model/graph_access_test.py

[feat] Resolve ancestor of cloud, account and region

---

resotocore/resotocore/web/api.py

[fix] Load checks by id

---

resotocore/resotocore/web/api.py
resotocore/tests/resotocore/web/api_test.py

[feat] benchmarks include severity in short info

---

plugins/gcp/resoto_plugin_gcp/__init__.py

Add more debug logging to GCP project discovery. This will help with situations where it is not clear why GCP does not find any projects.
- Fixes #XXXX

[plugins/gcp][chore] Add more debug logging to GCP project discovery

---

plugins/azure/resoto_plugin_azure/azure_client.py
plugins/azure/resoto_plugin_azure/resource/base.py
plugins/azure/test/conftest.py

* New Methods:
* `update_resource_tag`: This method allows for updating a specific tag associated with a resource by its tag name and tag value.
* `delete_resource_tag`: This method allows for deleting a specific tag associated with a resource by its tag name.
* `update_resource_tag`:
* Pass the tag name and the new tag value to update the respective tag on the specified resource.
* `delete_resource_tag`:
* Provide the tag name to delete the corresponding tag from the specified resource.

[azure] [feat] Implement update_tag, delete_tag of a resource

---

plugins/azure/resoto_plugin_azure/resource/base.py
plugins/azure/resoto_plugin_azure/resource/compute.py
plugins/azure/resoto_plugin_azure/resource/network.py
plugins/azure/tools/azure_model_gen.py

[feat] Azure add network resources

---

resotocore/resotocore/db/arango_query.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/db/arango_query_test.py
resotocore/tests/resotocore/db/graphdb_test.py

[resotocore][feat] Provide possible values for attributes and values

---

.github/workflows/docker-build.yml

[feat][resotocore] Bump inventory version on merge

---

resotocore/resotocore/model/exportable_model.py
resotocore/resotocore/model/model.py
resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/conftest.py
resotocore/tests/resotocore/model/exportable_model_test.py
resotocore/tests/resotocore/model/model_test.py

[feat][resotocore] Allow accessing detailed model information

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/db/model.py
resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/db/graphdb_test.py
resotocore/tests/resotocore/db/model_test.py

[resotocore][feat] Allow kind to be part of the node data

---

resotocore/resotocore/core_config.py
resotocore/resotocore/graph_manager/graph_manager.py

[resotocore][fix] Do not create snapshot jobs when scheduling is disabled

---

resotoworker/resotoworker/__main__.py

Allow defining a startup idle timeout

[resotoworker][feat] Allow defining a startup idle timeout

---

resotocore/Makefile
resotocore/resotocore/cli/command.py
resotocore/resotocore/model/model.py
resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/model/model_test.py

[resotocore][feat] Provide property complete endpoint

---

resotocore/resotocore/db/graphdb.py

[resotocore][fix] History ttl index was wrong

---

resotocore/resotocore/query/query_parser.py
resotocore/tests/resotocore/query/query_parser_test.py

[resotocore][fix] Fix query parser for predicates that start with all

---

resotocore/resotocore/model/model.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/model/model_test.py

[resotocore][fix] Type of exported model

---

resotolib/resotolib/core/__init__.py
resotoshell/resotoshell/__main__.py
resotoshell/resotoshell/authorized_client.py
resotoshell/resotoshell/shell.py

[resh][feat] Allow defining http headers for the shell via cmd line

---

resotocore/resotocore/db/graphdb.py
resotocore/resotocore/web/api.py

The ancestor section needs to be maintained correctly in history nodes.
This PR also allows deleting the related history when deleting a node.

[resotocore][fix] Maintain ancestor refs in history and allow to delete it

---

resotocore/resotocore/__main__.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/web/accesslog.py

[resotocore][chore] Improve logging

---

resotocore/resotocore/model/transform_kind_convert.py
resotoshell/resotoshell/__main__.py

[resotocore][fix] Try to make a string before

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/model/model.py
resotocore/tests/resotocore/cli/command_test.py

[resoto][fix] Handle backticks in list command

---

resotocore/resotocore/cli/command.py

[resotocore][fix] History should accept count flag

---

resotocore/resotocore/static/report/checks/aws/aws_cloudtrail.json

[resotocore][fix] result kind in check

---

resotocore/resotocore/db/async_arangodb.py
resotocore/tests/resotocore/db/graphdb_test.py

[resotocore][fix] do not filter non none values

---

resotocore/resotocore/db/graphdb.py

[resotocore][fix] Quote account ids

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/model/model.py
resotocore/tests/resotocore/cli/command_test.py

[resotocore][fix] Use the property path if existing

---

resotocore/.pylintrc
resotocore/resotocore/model/model.py
resotocore/tests/resotocore/model/model_test.py

[resotocore][feat] Improve sort order for complete path

---

resotocore/resotocore/task/task_description.py
resotocore/tests/resotocore/task/task_description_test.py

[resotocore][fix] Only show progress for collect

---

resotolib/resotolib/durations.py
resotolib/test/durations_test.py

[resotolib] Allow ISO 8601 durations

---

resotocore/resotocore/db/graphdb.py
resotocore/resotocore/model/resolve_in_graph.py
resotocore/tests/resotocore/db/graphdb_test.py

[resoto][fix] Change node should also reflect resolved properties

---

resotocore/resotocore/db/graphdb.py
resotocore/tests/resotocore/db/graphdb_test.py

[resoto][fix] Change node should also reflect ancestors in self

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/base.py

Add organization information to account node

[plugins/aws][feat] Add organization information to account node

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/core_config.py
resotocore/resotocore/db/arango_query.py
resotocore/resotocore/db/db_access.py
resotocore/resotocore/db/timeseriesdb.py
resotocore/tests/resotocore/conftest.py
resotocore/tests/resotocore/core_config_test.py
resotocore/tests/resotocore/db/arango_query_test.py
resotocore/tests/resotocore/db/timeseriesdb_test.py

[resotocore][feat] Add timeseries downsampling functionality

---

resotocore/resotocore/report/__init__.py
resotocore/resotocore/report/benchmark_renderer.py
resotocore/resotocore/report/inspector_service.py
resotocore/resotocore/report/report_config.py
resotocore/resotocore/static/report/check_template.json
resotocore/resotocore/static/report/checks/aws/aws_apigateway.json
resotocore/resotocore/static/report/checks/aws/aws_cloudtrail.json
resotocore/resotocore/static/report/checks/aws/aws_config.json
resotocore/resotocore/static/report/checks/aws/aws_ec2.json
resotocore/resotocore/static/report/checks/aws/aws_efs.json
resotocore/resotocore/static/report/checks/aws/aws_iam.json
resotocore/resotocore/static/report/checks/aws/aws_kms.json
resotocore/resotocore/static/report/checks/aws/aws_lambda.json
resotocore/resotocore/static/report/checks/aws/aws_rds.json
resotocore/resotocore/static/report/checks/aws/aws_s3.json
resotocore/tests/resotocore/conftest.py

[resotocore][feat] Allow multiple result kinds for ReportCheck

---

resotocore/resotocore/db/arangodb_extensions.py
resotocore/resotocore/report/__init__.py
resotocore/resotocore/report/benchmark_renderer.py
resotocore/resotocore/report/inspector_service.py
resotocore/resotocore/report/report_config.py
resotocore/resotocore/static/report/benchmark/aws/aws_cis_2_0.json
resotocore/resotocore/static/report/check_template.json
resotocore/resotocore/static/report/checks/aws/aws_apigateway.json
resotocore/resotocore/static/report/checks/aws/aws_cloudtrail.json
resotocore/resotocore/static/report/checks/aws/aws_config.json
resotocore/resotocore/static/report/checks/aws/aws_ec2.json
resotocore/resotocore/static/report/checks/aws/aws_efs.json
resotocore/resotocore/static/report/checks/aws/aws_iam.json
resotocore/resotocore/static/report/checks/aws/aws_kms.json
resotocore/resotocore/static/report/checks/aws/aws_lambda.json
resotocore/resotocore/static/report/checks/aws/aws_rds.json
resotocore/resotocore/static/report/checks/aws/aws_s3.json
resotocore/tests/resotocore/conftest.py

[resotocore][feat] Add AWS CIS 2.0

---

.github/PULL_REQUEST_TEMPLATE.md

Align the template to common work scenarios.

[resoto][chore] Make the PR template simpler.

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/db/async_arangodb.py
resotocore/resotocore/db/timeseriesdb.py
resotocore/resotocore/graph_manager/graph_manager.py

[resotocore][fix] timeseries batch size and timeout

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/ecr.py

[aws][fix] Public ECR repositories are global

---

plugins/aws/resoto_plugin_aws/resource/acm.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/resource/ecr.py
plugins/aws/resoto_plugin_aws/resource/opensearch.py
plugins/aws/resoto_plugin_aws/resource/rds.py
plugins/aws/resoto_plugin_aws/resource/secretsmanager.py
plugins/aws/resoto_plugin_aws/resource/ssm.py
plugins/aws/resoto_plugin_aws/resource/waf.py
resotolib/resotolib/core/model_check.py

[aws][fix] Define missing AWS Metadata

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/configuration.py

[feat] STS session duration and improve error handling

---

resotocore/resotocore/config/config_handler_service.py

[resotocore][fix] yaml handling

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/cli/model.py

[resotocore][fix] Only show info when requested

---

resotocore/resotocore/cli/command.py
resotocore/tests/resotocore/cli/command_test.py

[resotocore][feat] report check: show failing resources

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/base.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/model/graph_access.py
resotocore/tests/resotocore/__init__.py
resotocore/tests/resotocore/db/graphdb_test.py
resotocore/tests/resotocore/model/graph_access_test.py

[plugins/aws][feat] Create org tree.

---

resotocore/resotocore/db/graphdb.py
resotocore/resotocore/report/__init__.py
resotocore/resotocore/report/benchmark_renderer.py
resotocore/resotocore/report/inspector_service.py
resotocore/tests/resotocore/db/graphdb_test.py

[resotocore][fix] Same check from multiple benchmarks should result in one issue

---

resotocore/resotocore/dependencies.py
resotocore/tests/resotocore/dependencies_test.py

[resotocore][fix] Close the arangoconnection on stop

---

resotolib/resotolib/logger.py

[resotolib][feat] Add log counter

---

resotocore/resotocore/task/task_handler.py
resotocore/resotocore/web/accesslog.py

[resotocore][fix] small fixes

---

resotocore/resotocore/__main__.py
resotocore/resotocore/core_config.py
resotocore/resotocore/db/__init__.py
resotocore/resotocore/db/db_access.py
resotocore/resotocore/db/system_data_db.py
resotocore/resotocore/dependencies.py
resotocore/resotocore/graph_manager/graph_manager.py
resotocore/resotocore/system_start.py
resotocore/tests/resotocore/analytics/posthog_test.py
resotocore/tests/resotocore/conftest.py
resotocore/tests/resotocore/core_config_test.py
resotocore/tests/resotocore/db/system_data_db_test.py

[resotocore][feat] Maintain version and run migrations on demand

---

resotolib/resotolib/logger.py

This reverts commit c83481cd5aa1121a05ba5ddd07a52619bb7d758c.

Revert "[resotolib][feat] Add log counter (#1885)"

---

resotocore/resotocore/db/arango_query.py
resotocore/tests/resotocore/db/arango_query_test.py

[resotocore][fix] Aggregate over prop where last part is an array

---

resotocore/resotocore/cli/command.py
resotocore/tests/resotocore/cli/command_test.py

[resotocore][feat] Add path to table json output

---

resotocore/resotocore/db/graphdb.py
resotocore/resotocore/model/resolve_in_graph.py
resotocore/resotocore/report/__init__.py
resotocore/tests/resotocore/db/graphdb_test.py

[resotocore][fix] Maintain security improvements

---

resotocore/resotocore/db/graphdb.py
resotocore/resotocore/model/db_updater.py
resotocore/resotocore/model/graph_access.py
resotocore/tests/resotocore/db/graphdb_test.py

Fix the replacement of the organization roots

---

resotocore/resotocore/db/graphdb.py
resotocore/resotocore/model/graph_access.py
resotocore/resotocore/report/__init__.py
resotocore/tests/resotocore/db/graphdb_test.py

[resotocore][fix] Maintain security changes

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/collector.py

[chore][aws] Reduce logging level error->warning

---

resotocore/resotocore/static/report/checks/aws/aws_iam.json

[fix][resotocore] Fix MFA check

---

resotocore/resotocore/db/timeseriesdb.py
resotocore/tests/resotocore/db/timeseriesdb_test.py

[resotocore][fix] Allow only one timeseries creation at a time

---

plugins/azure/resoto_plugin_azure/__init__.py
plugins/azure/resoto_plugin_azure/azure_client.py
plugins/azure/resoto_plugin_azure/collector.py
plugins/azure/resoto_plugin_azure/config.py
plugins/azure/resoto_plugin_azure/resource/base.py
plugins/azure/resoto_plugin_azure/resource/compute.py
plugins/azure/resoto_plugin_azure/resource/metrics.py
plugins/azure/resoto_plugin_azure/resource/network.py
plugins/azure/resoto_plugin_azure/utils.py
plugins/azure/test/conftest.py
plugins/azure/test/files/compute/vm1.json
plugins/azure/test/files/compute/{virtualMachineName}.json
plugins/azure/test/files/metric/metrics.json
plugins/azure/test/metric_test.py

The implementation of Azure metrics collection, mirroring the model used for AWS

[azure] [feat] Collecting Azure Metrics

---

.github/workflows/publish.yml

Updates Fix docs on updates to `edge`.

[ci][chore] Update resource models & IAM policies in Fix docs

---

plugins/azure/resoto_plugin_azure/resource/metrics.py

[azure] [fix] NoneType error fix

---

plugins/aws/resoto_plugin_aws/resource/ecr.py
plugins/aws/resoto_plugin_aws/resource/efs.py
plugins/aws/resoto_plugin_aws/resource/glacier.py
plugins/aws/resoto_plugin_aws/resource/iam.py
plugins/aws/resoto_plugin_aws/resource/kms.py
plugins/aws/resoto_plugin_aws/resource/opensearch.py
plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/resoto_plugin_aws/resource/sns.py
plugins/aws/resoto_plugin_aws/resource/sqs.py
plugins/aws/resoto_plugin_aws/resource/ssm.py
plugins/dockerhub/resoto_plugin_dockerhub/resources.py
plugins/k8s/resoto_plugin_k8s/resources.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/db/arango_query.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/model/graph_access.py
resotocore/resotocore/model/model.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/model/graph_access_test.py
resotocore/tests/resotocore/model/model_test.py
resotolib/resotolib/json.py
resotolib/resotolib/json_bender.py
resotolib/test/test_json.py

[resotocore][feat] Maintain history only for configuration changes

---

resotocore/resotocore/db/arango_query.py
resotocore/resotocore/db/graphdb.py

[resotocore][fix] access to graphdb props

---

plugins/aws/resoto_plugin_aws/resource/ec2.py

[aws][fix] Handle wrong encoded user data gracefully

---

plugins/aws/resoto_plugin_aws/resource/cloudtrail.py
plugins/aws/resoto_plugin_aws/resource/cloudwatch.py
plugins/aws/resoto_plugin_aws/resource/config.py
plugins/aws/resoto_plugin_aws/resource/iam.py

[aws][chore] Mark additional fields as irrelevant for history changes

---

resotocore/resotocore/cli/cli.py
resotocore/tests/resotocore/cli/cli_test.py

[resotocore][fix] custom sorting in history

---

resotocore/resotocore/static/report/checks/aws/aws_lambda.json
resotocore/resotocore/static/report/checks/aws/aws_sqs.json

[resotocore][fix] wrong checks for lambda and sqs

---

plugins/aws/resoto_plugin_aws/resource/cloudfront.py
plugins/aws/resoto_plugin_aws/resource/ecs.py

[aws][fix] Collect capacity providers only once

---

resotocore/resotocore/static/report/checks/aws/aws_sqs.json

[resotocore][fix] broken sqs check

---

plugins/aws/resoto_plugin_aws/resource/ecs.py

[aws][fix] indentation level

---

resotocore/resotocore/static/report/checks/aws/aws_acm.json
resotocore/resotocore/static/report/checks/aws/aws_elb.json
resotocore/resotocore/static/report/checks/aws/aws_s3.json
resotocore/resotocore/static/report/checks/aws/aws_secretsmanager.json

- invert check for empty listener list
- SecretsManager date checks should be in the past not in the future
- filter buckets without encryption enabled 

[resotocore][fix] compliance checks

---

plugins/aws/resoto_plugin_aws/resource/cognito.py
resotocore/resotocore/static/report/checks/aws/aws_iam.json

[aws][fix] Make cognito group unique

---

resotocore/resotocore/static/report/checks/aws/aws_s3.json

[resotocore][fix] s3 bucket_secure_transport_policy

---

resotocore/resotocore/static/report/checks/aws/aws_s3.json

Take all actions into account.

[aws][fix] s3 bucket_secure_transport_policy: all actions

---

resotocore/resotocore/report/inspector_service.py
resotocore/resotocore/report/report_config.py
resotocore/tests/resotocore/report/inspector_service_test.py

[resotocore][feat] Allow blacklisting accounts

---

resotolib/resotolib/core/actions.py

[resotolib][fix] log feedback errors as warning

---

plugins/aws/tools/awspolicygen/requirements-test.txt
plugins/aws/tools/awspolicygen/requirements.txt
plugins/gcp/tools/gcppolicygen/requirements-test.txt
plugins/gcp/tools/gcppolicygen/requirements.txt

[inventory][fix] fix policy gen requirements

---

.github/workflows/check_pr_plugin_aws.yml

[inventory][fix] fix policy gen path

---

.github/workflows/check_pr_fixmetrics.yml
.github/workflows/check_pr_fixshell.yml
.github/workflows/check_pr_fixworker.yml
.github/workflows/fixcore_test_and_build.yml

[inventory][fix] use correct secret name

---

dockerV2/bootstrap

[docker][fix] Outdated home path

---

dockerV2/bootstrap

[fixinventory][fix] Update runuser

---

.github/workflows/publish.yml

Updates publish workflow to push changes to the new `someengineering/inventory.fix.security` repo.

[ci][chore] Update publish workflow

---

plugins/aws/tools/awspolicygen/awspolicygen/templates/fix-role.template.in

Update Fix -> FixInventory

---

fixmetrics/fixmetrics/__main__.py
fixshell/fixshell/__main__.py

more typos

---

fixcore/fixcore/cli/command.py

[core][fix] Wait after stdout/stderr has been read

---

fixcore/fixcore/static/fix.css
fixcore/fixcore/templates/base.html
fixcore/fixcore/templates/home.html
fixcore/fixcore/web/api.py
fixcore/fixcore/web/auth.py
fixcore/pyproject.toml
fixcore/tests/fixcore/web/api_test.py
requirements-all.txt
requirements-extra.txt
requirements.txt

[core][chore] Remove resoto-ui and show static HTML page instead.

---

fixcore/fixcore/system_start.py
fixmetrics/fixmetrics/__main__.py
fixworker/fixworker/__main__.py

Update core env prefix
Misc. description updates

[fixinventory][fix] Update core env prefix

---

setup_venv.sh

[inventory][fix] Use fixinventory instead of fix

---

fixcore/fixcore/__main__.py
fixlib/fixlib/utils.py
fixlib/test/test_utils.py
fixmetrics/fixmetrics/__main__.py
fixshell/fixshell/__main__.py
fixworker/fixworker/__main__.py

Ensure backwards compatibility with Resoto <= 3.9

[fixinventory][fix] Ensure backwards compatibility

---

fixlib/fixlib/config.py

Make overrides backwards compatible

[fixlib][fix] Make overrides backwards compatible

---

plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/resource/compute.py
plugins/azure/fix_plugin_azure/resource/containerservice.py
plugins/azure/fix_plugin_azure/resource/metrics.py
plugins/azure/fix_plugin_azure/resource/network.py
plugins/azure/test/collector_test.py
plugins/azure/test/compute_test.py
plugins/azure/test/containerservice_test.py
plugins/azure/test/files/compute/virtualMachineScaleSets.json
plugins/k8s/fix_plugin_k8s/deferred_edges/azure.py
plugins/k8s/fix_plugin_k8s/resources.py

[azure] [feat] Add new edges between resources

---

fixcore/fixcore/static/report/checks/aws/aws_ec2.json

[fixcore][fix] Adjust benchmark checks

---

tools/release_notes.py

Docusaurus v3 upgraded from MDX v1 to MDX v3.

[ci][fix] Update release notes truncate marker

---

fixcore/fixcore/db/graphdb.py
fixcore/fixcore/model/graph_access.py

[inventory][feat] Show the before section as part of history

---

fixcore/fixcore/db/graphdb.py

[inventory][fix] Also copy history as part of the graph copy operation

---

fixcore/fixcore/static/report/checks/aws/aws_acm.json
fixcore/fixcore/static/report/checks/aws/aws_apigateway.json
fixcore/fixcore/static/report/checks/aws/aws_autoscaling.json
fixcore/fixcore/static/report/checks/aws/aws_cloudformation.json
fixcore/fixcore/static/report/checks/aws/aws_cloudfront.json
fixcore/fixcore/static/report/checks/aws/aws_cloudtrail.json
fixcore/fixcore/static/report/checks/aws/aws_config.json
fixcore/fixcore/static/report/checks/aws/aws_dms.json
fixcore/fixcore/static/report/checks/aws/aws_dynamodb.json
fixcore/fixcore/static/report/checks/aws/aws_ec2.json
fixcore/fixcore/static/report/checks/aws/aws_ecr.json
fixcore/fixcore/static/report/checks/aws/aws_ecs.json
fixcore/fixcore/static/report/checks/aws/aws_eks.json
fixcore/fixcore/static/report/checks/aws/aws_elb.json
fixcore/fixcore/static/report/checks/aws/aws_glacier.json
fixcore/fixcore/static/report/checks/aws/aws_iam.json
fixcore/fixcore/static/report/checks/aws/aws_kms.json
fixcore/fixcore/static/report/checks/aws/aws_lambda.json
fixcore/fixcore/static/report/checks/aws/aws_opensearch.json
fixcore/fixcore/static/report/checks/aws/aws_rds.json
fixcore/fixcore/static/report/checks/aws/aws_redshift.json
fixcore/fixcore/static/report/checks/aws/aws_s3.json
fixcore/fixcore/static/report/checks/aws/aws_sagemaker.json
fixcore/fixcore/static/report/checks/aws/aws_secretsmanager.json
fixcore/fixcore/static/report/checks/aws/aws_sns.json
fixcore/fixcore/static/report/checks/aws/aws_sqs.json
fixcore/fixcore/static/report/checks/aws/aws_ssm.json
fixcore/fixcore/static/report/checks/aws/aws_wafv2.json

[fixcore][fix] Fix policy title style

---

Dockerfile.fixinventorybase

Update Docker to Python 3.12 / Debian Bookworm

[docker][feat] Update Docker to Python 3.12 / Debian Bookworm

---

.github/workflows/docker-build.yml
Dockerfile.fixinventorybase
dockerV2/common

Migrate from Debian to Fedora base image

[docker][feat] Migrate from Debian to Fedora base image

---

.github/workflows/bump_fixcompliance.yml
tools/bumpfixcompliance.sh

[github][feat] Workflow to bump fixcompliance

---

.github/workflows/bump_fixcompliance.yml

[github][fix] Update workflow

---

requirements-all.txt
requirements-extra.txt
requirements.txt
tools/requirements.py

[fix] Fix Bump Version to 4.0.1

---

plugins/aws/fix_plugin_aws/resource/iam.py
plugins/gcp/fix_plugin_gcp/resources/compute.py

[aws][feat] Indicate if policy is managed

---

fixcore/fixcore/model/graph_access.py
plugins/aws/fix_plugin_aws/resource/cloudfront.py

[aws][fix] Custom headers as dict

---

fixcore/fixcore/dependencies.py

[core][fix] Do not block on tear down

---

fixcore/fixcore/web/api.py

[core][fix] Require write permission instead of admin

---

fixcore/fixcore/db/arango_query.py
fixcore/fixcore/query/model.py
fixcore/fixcore/report/inspector_service.py
fixcore/tests/fixcore/query/model_test.py
fixcore/tests/fixcore/query/query_parser_test.py
fixcore/tests/fixcore/report/inspector_service_test.py

[fixcore][feat] Ignore resources

---

fixcore/fixcore/db/graphdb.py

[fixcore][fix] Improvement wit less issues not more

---

fixcore/fixcore/db/graphdb.py
fixcore/fixcore/web/api.py
fixcore/tests/fixcore/web/api_test.py

[fixcore][fix] Handle metadata/desired patches correctly

---

fixcore/fixcore/db/arango_query.py
fixcore/tests/fixcore/db/arango_query_test.py

[core][fix] Fix limit on with clause

---

fixcore/fixcore/db/arango_query.py
fixcore/tests/fixcore/db/arango_query_test.py

[core][fix] array access in combination with not

---

fixcore/fixcore/cli/command.py
fixcore/tests/fixcore/cli/command_test.py

[core][feat] Drop UpdatedAt and combine Region/Zone in table json

---

plugins/aws/fix_plugin_aws/resource/route53.py

[aws][fix] Record:  should include record_set_identifier

---

fixcore/fixcore/cli/command.py
fixcore/tests/fixcore/cli/command_test.py

[core][feat] Render aggregates in list output

---

fixcore/fixcore/cli/command.py

[core][fix] Render aggregates in json table

---

fixcore/fixcore/db/arango_query.py

[core][fix] Apply limit to aggregate result not query

---

fixcore/fixcore/cli/command.py
fixcore/fixcore/db/graphdb.py

[core][fix] Allow count and timeout for aggregate queries

---

fixcore/fixcore/query/model.py
fixcore/tests/fixcore/query/query_parser_test.py

[core][feat] Optimize merge query

---

plugins/aws/fix_plugin_aws/__init__.py
plugins/aws/fix_plugin_aws/utils.py
plugins/aws/test/test_utils.py

Use default profile if it exists

[fix][aws] Use default profile if it exists

---

plugins/gcp/pyproject.toml

[fix][gcp] Add fixinventorydata

---

fixcore/fixcore/report/__init__.py
fixcore/fixcore/report/benchmark_renderer.py
fixcore/fixcore/report/inspector_service.py
fixcore/tests/fixcore/cli/cli_test.py
fixcore/tests/fixcore/cli/command_test.py
fixcore/tests/fixcore/conftest.py
fixcore/tests/fixcore/db/graphdb_test.py
fixcore/tests/fixcore/db/modeldb_test.py
fixcore/tests/fixcore/db/timeseriesdb_test.py
fixcore/tests/fixcore/model/json_schema_test.py
fixcore/tests/fixcore/model/model_test.py
fixcore/tests/fixcore/report/inspector_service_test.py
fixcore/tests/fixcore/web/api_test.py
fixlib/test/test_tree.py

[core][feat] Maintain account score in metadata

---

fixcore/fixcore/db/arango_query.py
fixcore/tests/fixcore/db/arango_query_test.py

[core][fix] Timeseries apply aggregation on slotted values

---

plugins/vsphere/fix_plugin_vsphere/__init__.py

indentation and positional error while creating ESXi host connection to data center.

fix ESXiHost edge

---

fixlib/fixlib/core/actions.py
plugins/aws/fix_plugin_aws/aws_client.py
plugins/aws/fix_plugin_aws/collector.py
plugins/aws/test/aws_client_test.py
plugins/azure/fix_plugin_azure/__init__.py
plugins/azure/fix_plugin_azure/azure_client.py
plugins/azure/fix_plugin_azure/collector.py
plugins/azure/fix_plugin_azure/config.py
plugins/azure/fix_plugin_azure/resource/network.py

[azure][fix] Warn and ignore HttpResponseError

---

plugins/azure/fix_plugin_azure/__init__.py

[azure][fix] Finish in case of exception

---

docker-compose.yaml

[docker][fix] Remove obsolte version and download volume

---

plugins/aws/fix_plugin_aws/resource/cloudwatch.py
plugins/aws/fix_plugin_aws/resource/ec2.py
plugins/aws/fix_plugin_aws/resource/elb.py
plugins/aws/fix_plugin_aws/resource/elbv2.py
plugins/aws/fix_plugin_aws/resource/kinesis.py
plugins/aws/fix_plugin_aws/resource/lambda_.py
plugins/aws/fix_plugin_aws/resource/rds.py
plugins/aws/fix_plugin_aws/resource/redshift.py
plugins/aws/fix_plugin_aws/resource/s3.py
plugins/aws/fix_plugin_aws/resource/sns.py
plugins/aws/fix_plugin_aws/resource/sqs.py
plugins/aws/test/resources/cloudwatch_test.py

Implementing AWS parallel metric collection

[aws][feat] Add AWS parallel metrics collection

---

tools/release_notes.py

- `fix` or `inventory` or `fixinventory` component badges are unnecessary, as they do not add information (all commits are to the `fixinventory` repo)
- `fix` is not only a commit category/group but also the product name, so we don't want to always swap the component/group.
- `fix` is a better default group based on past commits (when time is not taken to format the commit message properly or a commit is rushed, it's more likely to be a bug fix)
- component names should be consistent (e.g., `core` instead of `fixcore`)
- README updates should be categorized as `docs`

[ci][chore] Refine release notes script

---

plugins/azure/fix_plugin_azure/__init__.py
plugins/azure/fix_plugin_azure/azure_client.py
plugins/azure/fix_plugin_azure/collector.py
plugins/azure/fix_plugin_azure/config.py
plugins/azure/fix_plugin_azure/resource/base.py

[azure] [feat]: Add new handling functionality for errors

---

plugins/aws/fix_plugin_aws/resource/ec2.py
plugins/aws/fix_plugin_aws/resource/iam.py

Add edge from IAM instance profile to EC2 instance

[aws][fix] Add edge from IAM instance profile to EC2 instance

---

fixcore/fixcore/db/graphdb.py
fixcore/fixcore/web/api.py

[core][feat] Allow update node with force

---

plugins/aws/fix_plugin_aws/resource/cloudwatch.py
plugins/aws/fix_plugin_aws/resource/s3.py

[aws][fix] Fix S3 storage metrics retrieval

---

plugins/aws/fix_plugin_aws/resource/s3.py

[aws][feat] Add S3 bucket location property

---

plugins/aws/fix_plugin_aws/aws_client.py

[aws][fix] Retry using retrying only

---

plugins/aws/fix_plugin_aws/resource/s3.py

[aws][fix] Collection S3 cloudwatch metrics in the corresponding regions

---

plugins/aws/fix_plugin_aws/resource/ecs.py

[aws][fix] wait for all ecs task definitions

---

fixcore/fixcore/db/arango_query.py

[core][fix] sort with `with` clause

---

plugins/aws/fix_plugin_aws/resource/cloudwatch.py
plugins/aws/fix_plugin_aws/resource/ec2.py
plugins/aws/fix_plugin_aws/resource/rds.py
plugins/aws/fix_plugin_aws/resource/s3.py
plugins/aws/test/resources/cloudwatch_test.py

[aws][fix] S3 metrics for all storage types

---

plugins/aws/test/resources/__init__.py
plugins/aws/test/resources/files/cloudwatch/get-metric-data__2024_05_01_12_00_00_00_00_numberofobjects_aws_s3_bucketname_bucket_1_storagetype_allstoragetypes_average_AWS_S3_NumberOfObjects_BucketName_bucket_1_StorageType_AllStorageTypes_86400_Average_Count_True_bucketsizebytes_a.json
plugins/aws/test/resources/s3_test.py

[aws][fix] Add test for s3 storage metrics

---

plugins/aws/fix_plugin_aws/resource/pricing.py

[aws][feat] Add io2 pricing

---

requirements-all.txt
requirements-extra.txt
requirements.txt

[aws][feat] Bump Fix Inventory Data

---

plugins/aws/fix_plugin_aws/resource/apigateway.py
plugins/aws/fix_plugin_aws/resource/athena.py
plugins/aws/fix_plugin_aws/resource/base.py
plugins/aws/fix_plugin_aws/resource/cloudformation.py
plugins/aws/fix_plugin_aws/resource/cloudfront.py
plugins/aws/fix_plugin_aws/resource/cloudtrail.py
plugins/aws/fix_plugin_aws/resource/cloudwatch.py
plugins/aws/fix_plugin_aws/resource/cognito.py
plugins/aws/fix_plugin_aws/resource/config.py
plugins/aws/fix_plugin_aws/resource/dynamodb.py
plugins/aws/fix_plugin_aws/resource/ec2.py
plugins/aws/fix_plugin_aws/resource/ecs.py
plugins/aws/fix_plugin_aws/resource/efs.py
plugins/aws/fix_plugin_aws/resource/eks.py
plugins/aws/fix_plugin_aws/resource/elasticache.py
plugins/aws/fix_plugin_aws/resource/elasticbeanstalk.py
plugins/aws/fix_plugin_aws/resource/elb.py
plugins/aws/fix_plugin_aws/resource/elbv2.py
plugins/aws/fix_plugin_aws/resource/glacier.py
plugins/aws/fix_plugin_aws/resource/iam.py
plugins/aws/fix_plugin_aws/resource/kinesis.py
plugins/aws/fix_plugin_aws/resource/kms.py
plugins/aws/fix_plugin_aws/resource/lambda_.py
plugins/aws/fix_plugin_aws/resource/rds.py
plugins/aws/fix_plugin_aws/resource/redshift.py
plugins/aws/fix_plugin_aws/resource/route53.py
plugins/aws/fix_plugin_aws/resource/s3.py
plugins/aws/fix_plugin_aws/resource/sagemaker.py
plugins/aws/fix_plugin_aws/resource/sns.py
plugins/aws/fix_plugin_aws/resource/sqs.py

The `collect` method has been updated to make it easier to collect usage metrics.

[aws][feat]: Update `collect` method implementation

---

fixcore/fixcore/core_config.py
fixcore/fixcore/model/model_handler.py

[fixcore][fix] Fix PlantUML settings

---

fixcore/fixcore/db/arango_query.py
fixcore/tests/fixcore/db/arango_query_test.py

[core][fix] Add whitespace to operation

---

fixcore/fixcore/report/__init__.py
fixcore/fixcore/report/inspector_service.py
fixcore/fixcore/static/api-doc.yaml
fixcore/fixcore/web/api.py

[core][feat] Allow filtering benchmarks

---

plugins/aws/fix_plugin_aws/resource/apigateway.py
plugins/aws/fix_plugin_aws/resource/athena.py
plugins/aws/fix_plugin_aws/resource/cloudtrail.py
plugins/aws/fix_plugin_aws/resource/cognito.py
plugins/aws/fix_plugin_aws/resource/dynamodb.py
plugins/aws/fix_plugin_aws/resource/ec2.py
plugins/aws/fix_plugin_aws/resource/ecs.py
plugins/aws/fix_plugin_aws/resource/eks.py
plugins/aws/fix_plugin_aws/resource/elb.py
plugins/aws/fix_plugin_aws/resource/elbv2.py
plugins/aws/fix_plugin_aws/resource/glacier.py
plugins/aws/fix_plugin_aws/resource/kinesis.py
plugins/aws/fix_plugin_aws/resource/lambda_.py
plugins/aws/fix_plugin_aws/resource/rds.py
plugins/aws/fix_plugin_aws/resource/redshift.py
plugins/aws/fix_plugin_aws/resource/route53.py
plugins/aws/fix_plugin_aws/resource/sagemaker.py
plugins/aws/fix_plugin_aws/resource/sns.py
plugins/aws/fix_plugin_aws/resource/sqs.py
plugins/aws/test/resources/__init__.py
plugins/aws/test/resources/service_quotas_test.py

[feat][aws] Add more resources to done in parallel

---

plugins/aws/fix_plugin_aws/resource/apigateway.py
plugins/aws/fix_plugin_aws/resource/athena.py
plugins/aws/fix_plugin_aws/resource/cloudtrail.py
plugins/aws/fix_plugin_aws/resource/cognito.py
plugins/aws/fix_plugin_aws/resource/dynamodb.py
plugins/aws/fix_plugin_aws/resource/ec2.py
plugins/aws/fix_plugin_aws/resource/ecs.py
plugins/aws/fix_plugin_aws/resource/eks.py
plugins/aws/fix_plugin_aws/resource/elb.py
plugins/aws/fix_plugin_aws/resource/elbv2.py
plugins/aws/fix_plugin_aws/resource/glacier.py
plugins/aws/fix_plugin_aws/resource/kinesis.py
plugins/aws/fix_plugin_aws/resource/lambda_.py
plugins/aws/fix_plugin_aws/resource/rds.py
plugins/aws/fix_plugin_aws/resource/redshift.py
plugins/aws/fix_plugin_aws/resource/route53.py
plugins/aws/fix_plugin_aws/resource/sagemaker.py
plugins/aws/fix_plugin_aws/resource/sns.py
plugins/aws/fix_plugin_aws/resource/sqs.py
plugins/aws/test/resources/__init__.py
plugins/aws/test/resources/service_quotas_test.py

This reverts commit 718fa3e175d2a483264800073c81be911522cbc5.

Revert "[feat][aws] Add more resources to done in parallel (#2066)"

---

fixlib/fixlib/baseresources.py
plugins/azure/fix_plugin_azure/azure_client.py
plugins/azure/fix_plugin_azure/config.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/resource/containerservice.py
plugins/azure/fix_plugin_azure/resource/metrics.py
plugins/azure/fix_plugin_azure/resource/storage.py
plugins/azure/test/metric_test.py

[azure][feat] Azure Storage `collect_usage_metrics` implementation

---

plugins/azure/fix_plugin_azure/collector.py
plugins/azure/fix_plugin_azure/resource/compute.py
plugins/azure/fix_plugin_azure/resource/containerservice.py
plugins/azure/fix_plugin_azure/resource/storage.py
plugins/azure/test/compute_test.py
plugins/azure/test/containerservice_test.py
plugins/azure/test/storage_test.py

[azure][feat] Align names of the azure resources

---

plugins/aws/fix_plugin_aws/resource/ec2.py

[aws][feat] Provide VPC in use flag

---

plugins/azure/fix_plugin_azure/resource/base.py

Sometimes in the tests got this error:
```shell
ERROR fix:threading.py:163 Unhandled exception in azure_collector: dictionary changed size during iteration
Traceback (most recent call last):
File "/home/runner/fixinventory/fixinventory/fixlib/fixlib/threading.py", line 159, in wait_for_submitted_work
future.result()
File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/concurrent/futures/_base.py", line 449, in result
return self.__get_result()
^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
raise self._exception
File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```

[azure][feat]: Add safety read/write access to the graph

---

fixcore/fixcore/db/db_access.py
fixcore/fixcore/db/graphdb.py

[core][feat] Improve update index efficiency

---

plugins/aws/fix_plugin_aws/collector.py
plugins/aws/fix_plugin_aws/resource/base.py
plugins/aws/test/collector_test.py

[aws][feat] Add region_in_use property for region

---

requirements-all.txt
requirements-extra.txt
requirements.txt

[fixinventory][chore] Bump libs

---

plugins/aws/fix_plugin_aws/resource/dynamodb.py
plugins/aws/test/resources/files/dynamodb/describe-continuous-backups__test1.json
plugins/aws/tools/aws_model_gen.py

[aws][feat] Add dynamodb continuous backup

---

fixlib/fixlib/basecategories.py
fixlib/fixlib/baseresources.py
fixlib/fixlib/core/model_export.py
fixlib/test/test_basecategories.py

[fixlib][feat] Export categories

---

plugins/aws/fix_plugin_aws/resource/ecs.py

[aws][fix] Update log level info -> debug for task def skipping

---

fixcore/fixcore/db/graphdb.py

[core][fix] Wait lock timeout

---

plugins/aws/fix_plugin_aws/resource/cloudwatch.py
plugins/aws/fix_plugin_aws/resource/ec2.py
plugins/aws/fix_plugin_aws/resource/elb.py
plugins/aws/fix_plugin_aws/resource/elbv2.py
plugins/aws/fix_plugin_aws/resource/kinesis.py
plugins/aws/fix_plugin_aws/resource/lambda_.py
plugins/aws/fix_plugin_aws/resource/rds.py
plugins/aws/fix_plugin_aws/resource/redshift.py
plugins/aws/fix_plugin_aws/resource/s3.py
plugins/aws/fix_plugin_aws/resource/sns.py
plugins/aws/fix_plugin_aws/resource/sqs.py
plugins/aws/test/resources/cloudwatch_test.py
plugins/aws/test/resources/s3_test.py

[aws][fix] Add clear names and fix `BucketSize` collection of the S3 resource

---

fixshell/fixshell/__main__.py
fixshell/fixshell/benchmark.py
fixshell/fixshell/shell.py
fixshell/test/test_benchmark.py

[fixshell][feat] Add --benchmark arg

---

fixcore/fixcore/model/model_handler.py
fixcore/fixcore/web/api.py

[core][fix] model creation

---

fixcore/fixcore/db/arango_query_rewrite.py
fixcore/tests/fixcore/db/arango_query_test.py

[core][fix] Only combine terms for properties in the reported section

---

fixcore/fixcore/cli/command.py
fixcore/fixcore/cli/model.py
fixcore/fixcore/db/async_arangodb.py
fixcore/fixcore/web/api.py

[core][feat] Add query stats as HTTP Header

---

fixshell/fixshell/benchmark.py
fixshell/fixshell/shell.py
fixshell/test/test_benchmark.py

[fixshell][feat] Add more benchmark stats

---

fixlib/fixlib/core/model_check.py
fixlib/test/core/model_check_test.py
plugins/aws/fix_plugin_aws/resource/waf.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/resource/compute.py
plugins/azure/fix_plugin_azure/resource/containerservice.py
plugins/azure/fix_plugin_azure/resource/network.py
plugins/azure/fix_plugin_azure/resource/storage.py

[lib][fix] Fix kind names

---

.github/workflows/basecheck.yml

[fix][fix] Fix typo in basechecker workflow

---

fixcore/fixcore/db/arango_query.py
fixcore/fixcore/query/query_parser.py
fixcore/tests/fixcore/db/arango_query_test.py
fixcore/tests/fixcore/db/graphdb_test.py

[core][fix] Fix and improve with statements

---

plugins/azure/fix_plugin_azure/resource/base.py

Use a single lock for the Azure graph builder

---

plugins/azure/fix_plugin_azure/resource/base.py

Collect the correct subscription id

---

plugins/aws/fix_plugin_aws/resource/s3.py
plugins/aws/test/collector_test.py

[aws][feat] Edge: s3 account settings --> s3 bucket

---

fixshell/fixshell/__main__.py

[shell][fix] Define graph and section

---

fixcore/fixcore/report/__init__.py
fixcore/fixcore/report/inspector_service.py

[core][fix] Stable node ids for benchmark results

---

fixcore/tools/README.md
fixcore/tools/render_dot.py
fixmetrics/README.md
fixshell/README.md
fixshell/fixshell/authorized_client.py

[fixsh][chore] resh->fixsh

---

fixworker/fixworker/collect.py

[worker] Fix description for cycle

---

plugins/aws/fix_plugin_aws/resource/backup.py
plugins/aws/test/collector_test.py

[aws][fix]: Fix non acyclic graph connection

---

plugins/aws/fix_plugin_aws/resource/dynamodb.py

[aws][chore] Ignore props for history

---

fixcore/fixcore/dependencies.py

[core][fix] Maintain db config in tenant config

---

fixcore/fixcore/model/model.py
fixcore/tests/fixcore/cli/command_test.py
fixcore/tests/fixcore/model/model_test.py

[core][fix] Model: resolve hierarchy not bases

---

fixcore/fixcore/db/arango_query_rewrite.py
fixcore/fixcore/model/model.py
fixcore/tests/fixcore/db/model_test.py
fixcore/tests/fixcore/model/model_test.py
plugins/azure/fix_plugin_azure/resource/base.py

[core][fix] Simplify and fix owner lookup

---

plugins/aws/fix_plugin_aws/resource/rds.py

[aws][fix] Ignore rds_latest_restorable_time for history

---

fixcore/fixcore/cli/command.py
fixcore/fixcore/report/__init__.py
fixcore/tests/fixcore/cli/command_test.py

Render empty sections (children without checks).

[core][fix] Render empty sections

---

plugins/azure/fix_plugin_azure/__init__.py
plugins/azure/fix_plugin_azure/azure_client.py
plugins/azure/fix_plugin_azure/collector.py
plugins/azure/fix_plugin_azure/config.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/resource/compute.py
plugins/azure/fix_plugin_azure/resource/containerservice.py
plugins/azure/fix_plugin_azure/resource/metrics.py
plugins/azure/fix_plugin_azure/resource/microsoft_graph.py
plugins/azure/fix_plugin_azure/resource/network.py
plugins/azure/fix_plugin_azure/resource/storage.py
plugins/azure/iam.puml
plugins/azure/test/collector_test.py
plugins/azure/test/compute_test.py
plugins/azure/test/conftest.py
plugins/azure/test/containerservice_test.py
plugins/azure/test/network_test.py
plugins/azure/tools/azure_model_gen.py
plugins/azure/tools/microsoft_graph_model_gen.py

[azure][feat] Add Microsoft Graph collector

---

fixcore/fixcore/__main__.py
fixcore/fixcore/action_handlers/merge_deferred_edge_handler.py
fixcore/fixcore/dependencies.py
fixcore/fixcore/static/api-doc.yaml
fixcore/fixcore/task/task_handler.py
fixcore/fixcore/web/api.py
fixcore/tests/fixcore/action_handlers/merge_deferred_edge_handler_test.py
fixcore/tests/fixcore/action_handlers/merge_outer_edge_handler_test.py
fixcore/tests/fixcore/conftest.py

[core][feat] Merge deferred edges via API

---

plugins/azure/fix_plugin_azure/collector.py
plugins/azure/fix_plugin_azure/config.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/utils.py
plugins/azure/test/conftest.py

[azure][feat] Case insensitive connect

---

plugins/azure/fix_plugin_azure/collector.py
plugins/azure/fix_plugin_azure/config.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/resource/security.py
plugins/azure/fix_plugin_azure/utils.py
plugins/azure/test/collector_test.py
plugins/azure/test/conftest.py
plugins/azure/test/files/security/assessments.json
plugins/azure/test/files/security/pricings.json
plugins/azure/test/files/security/serverVulnerabilityAssessmentsSettings.json
plugins/azure/test/files/security/settings.json
plugins/azure/test/security_test.py
plugins/azure/test/storage_test.py
plugins/azure/tools/azure_model_gen.py

[azure][feat] Collect security resources

---

fixcore/fixcore/action_handlers/merge_outer_edge_handler.py
plugins/azure/fix_plugin_azure/collector.py
plugins/azure/fix_plugin_azure/resource/authorization.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/resource/microsoft_graph.py
plugins/azure/iam.puml
plugins/azure/test/authorization_test.py
plugins/azure/test/collector_test.py
plugins/azure/test/conftest.py
plugins/azure/test/files/authorization/denyAssignments.json
plugins/azure/test/files/authorization/roleAssignments.json
plugins/azure/test/files/authorization/roleDefinitions.json
plugins/azure/tools/azure_model_gen.py

[azure][feat] Add authorization

---

fixcore/fixcore/db/arango_query.py
fixcore/tests/fixcore/db/arango_query_test.py

[core][fix] Turn off regexp rewriting

---

fixcore/fixcore/db/arango_query.py

[core][fix] Fix nested with statements

---

fixcore/fixcore/db/arango_query.py
fixcore/fixcore/db/arango_query_rewrite.py
fixcore/fixcore/db/graphdb.py
fixcore/fixcore/model/model.py
fixcore/tests/fixcore/db/arango_query_rewrite_test.py
fixcore/tests/fixcore/model/model_test.py

[core][fix] History search with sort and fulltext terms

---

fixcore/fixcore/db/graphdb.py

[core][fix] Security sync by always marking the resource vulnerable

---

plugins/azure/fix_plugin_azure/resource/sql.py
plugins/azure/test/sql_test.py

[azure][feat]: Add prefix 'server' to the SQL resources

---

plugins/azure/fix_plugin_azure/resource/storage.py

[azure][fix] Better names

---

fixcore/fixcore/db/arango_query.py
fixcore/fixcore/db/async_arangodb.py
fixcore/fixcore/db/graphdb.py
fixcore/fixcore/static/api-doc.yaml
fixcore/fixcore/web/api.py
fixcore/tests/fixcore/db/graphdb_test.py

[core][feat] Add history timeline

---

fixshell/fixshell/promptsession.py

[shell][fix] Do not warn when the model cannot be loaded

---

fixlib/fixlib/json_bender.py
plugins/gcp/fix_plugin_gcp/resources/compute.py
plugins/gcp/fix_plugin_gcp/resources/sqladmin.py

[fix][gcp] Disk size types

---

plugins/azure/fix_plugin_azure/resource/network.py
plugins/azure/fix_plugin_azure/utils.py
plugins/azure/test/collector_test.py
plugins/azure/test/files/network/flowLogs.json

[azure][feat] Add flow log resource collection

---

plugins/azure/fix_plugin_azure/azure_client.py
plugins/azure/fix_plugin_azure/resource/postgresql.py
plugins/azure/fix_plugin_azure/resource/sql_server.py
plugins/gcp/fix_plugin_gcp/resources/base.py
plugins/gcp/fix_plugin_gcp/resources/compute.py
plugins/gcp/fix_plugin_gcp/resources/storage.py
plugins/gcp/test/random_client.py

[gcp][feat] Save parsing with feedback

---

plugins/gcp/fix_plugin_gcp/resources/base.py

[gcp][fix] Improve error message

---

fixcore/fixcore/report/__init__.py
fixcore/fixcore/report/inspector_service.py
fixcore/tests/fixcore/report/inspector_service_test.py

[core][feat] account security score details

---

plugins/azure/fix_plugin_azure/resource/keyvault.py
plugins/azure/fix_plugin_azure/utils.py
plugins/azure/test/collector_test.py
plugins/azure/test/files/keyvault/secrets.json
plugins/azure/tools/azure_model_gen.py

[azure][feat] Improve KeyVault

---

fixcore/fixcore/db/arango_query.py
fixcore/fixcore/db/graphdb.py

[core][fix] Move timeline to request time after

---

plugins/gcp/fix_plugin_gcp/resources/sqladmin.py

Fixed `GcpSqlUser` replica error.

[gcp][fix]: Duplicate checksum error in sql service

---

fixcore/fixcore/db/arango_query.py

[core][fix] History timeseries slotter

---

fixcore/fixcore/web/api.py
fixcore/tests/fixcore/report/inspector_service_test.py

Make report checks lookup safer

---

plugins/azure/fix_plugin_azure/resource/cosmosdb.py
plugins/azure/test/collector_test.py
plugins/azure/test/cosmos-db_test.py
plugins/azure/test/files/cosmos-db/configurations.json
plugins/azure/test/files/cosmos-db/privateEndpointConnections.json
plugins/azure/test/files/cosmos-db/roles.json
plugins/azure/test/files/cosmos-db/serverGroupsv2.json
plugins/azure/test/files/cosmos-db/servers.json

Added missing `PostgreSQL` resource for Cosmos DB

[azure][feat] Add PostgreSQL collection for cosmos-db resources

---

fixcore/tests/fixcore/report/inspector_service_test.py

[core][fix] latest azure check

---

README.md

The current link 404s. I think this is where it is meant to go?

Update Link in overview of README.md

---

fixcore/fixcore/analytics/posthog.py

[core][feat] allowlist events for posthog

---

plugins/azure/fix_plugin_azure/resource/compute.py
plugins/azure/fix_plugin_azure/resource/containerservice.py
plugins/azure/fix_plugin_azure/resource/cosmosdb.py
plugins/azure/fix_plugin_azure/resource/network.py
plugins/azure/fix_plugin_azure/resource/postgresql.py
plugins/azure/fix_plugin_azure/resource/storage.py
plugins/azure/fix_plugin_azure/resource/web.py

[azure][chore] Remove unused classes

---

fixcore/fixcore/db/arango_query.py
fixcore/tests/fixcore/db/arango_query_test.py

[core][fix] arangosearch predicates with array access

---

plugins/aws/docs/iam.puml
plugins/aws/docs/sso.puml

[aws][chore] Documentation for AWS Iam and SSO

---

fixcore/fixcore/__main__.py

[core][fix] Surrogate system data

---

fixcore/fixcore/action_handlers/merge_deferred_edge_handler.py
fixcore/fixcore/cli/command.py
fixcore/fixcore/db/arango_query.py
fixcore/fixcore/db/async_arangodb.py
fixcore/fixcore/db/db_access.py
fixcore/fixcore/db/deferrededgesdb.py
fixcore/fixcore/db/graphdb.py
fixcore/fixcore/db/lockdb.py
fixcore/fixcore/db/runningtaskdb.py
fixcore/fixcore/db/timeseriesdb.py
fixcore/fixcore/db/usagedb.py
fixcore/fixcore/model/db_updater.py
fixcore/fixcore/model/graph_access.py
fixcore/fixcore/util.py
fixcore/pyproject.toml
fixcore/tests/fixcore/action_handlers/merge_deferred_edge_handler_test.py
fixcore/tests/fixcore/conftest.py
fixcore/tests/fixcore/db/deferrededgesdb_test.py
fixcore/tests/fixcore/graph_manager/graph_manager_test.py
fixcore/tests/fixcore/model/db_updater_test.py
fixcore/tests/fixcore/model/graph_access_test.py
fixcore/tests/fixcore/utils.py

[core][feat] Allow edge properties

---

.github/workflows/basecheck.yml
.github/workflows/check_pr_fixlib.yml
.github/workflows/check_pr_fixmetrics.yml
.github/workflows/check_pr_fixshell.yml
.github/workflows/check_pr_fixworker.yml
.github/workflows/check_pr_plugin_aws.yml
.github/workflows/check_pr_plugin_azure.yml
.github/workflows/check_pr_plugin_digitalocean.yml
.github/workflows/check_pr_plugin_dockerhub.yml
.github/workflows/check_pr_plugin_example_collector.yml
.github/workflows/check_pr_plugin_gcp.yml
.github/workflows/check_pr_plugin_github.yml
.github/workflows/check_pr_plugin_k8s.yml
.github/workflows/check_pr_plugin_onelogin.yml
.github/workflows/check_pr_plugin_onprem.yml
.github/workflows/check_pr_plugin_posthog.yml
.github/workflows/check_pr_plugin_random.yml
.github/workflows/check_pr_plugin_scarf.yml
.github/workflows/check_pr_plugin_slack.yml
.github/workflows/check_pr_plugin_vsphere.yml
.github/workflows/create_plugin_workflows.py
fixlib/fixlib/baseresources.py
plugins/aws/fix_plugin_aws/resource/base.py
plugins/aws/fix_plugin_aws/resource/iam.py

Add IamPrincipal base resource

---

fixcore/fixcore/web/api.py

[core][fix] Fix model filter condition

---

plugins/aws/fix_plugin_aws/resource/ec2.py
plugins/aws/fix_plugin_aws/resource/opensearch.py
plugins/aws/fix_plugin_aws/resource/rds.py
plugins/aws/fix_plugin_aws/resource/secretsmanager.py
plugins/aws/test/collector_test.py
plugins/azure/fix_plugin_azure/resource/authorization.py
plugins/azure/fix_plugin_azure/resource/microsoft_graph.py
plugins/azure/fix_plugin_azure/resource/mysql.py
plugins/azure/fix_plugin_azure/resource/security.py
plugins/azure/fix_plugin_azure/resource/sql_server.py
plugins/azure/test/collector_test.py
plugins/gcp/fix_plugin_gcp/resources/billing.py
plugins/gcp/fix_plugin_gcp/resources/compute.py
plugins/gcp/test/test_collector.py

[plugins][fix] Add missing metadata

---

fixlib/fixlib/baseresources.py
fixlib/fixlib/core/model_check.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/resource/microsoft_graph.py

[lib][feat] Improve model check

---

plugins/azure/fix_plugin_azure/resource/machinelearning.py

[azure][fix]: Fix unnecessary abstract class kinds

---

fixcore/fixcore/model/graph_access.py
fixcore/fixcore/types.py

[core][feat] Add IAM edge collection

---

fixcore/fixcore/cli/command.py
fixcore/tests/fixcore/cli/command_test.py

[core][feat] list: allow for listing props with default props

---

plugins/azure/fix_plugin_azure/resource/authorization.py
plugins/azure/fix_plugin_azure/resource/cosmosdb.py
plugins/gcp/fix_plugin_gcp/resources/base.py

[azure][fix] Ignore props for history

---

fixcore/fixcore/web/api.py

[core][fix] Multipart name

---

plugins/azure/fix_plugin_azure/resource/compute.py
plugins/azure/fix_plugin_azure/resource/containerservice.py
plugins/azure/fix_plugin_azure/resource/cosmosdb.py
plugins/azure/fix_plugin_azure/resource/keyvault.py
plugins/azure/fix_plugin_azure/resource/machinelearning.py
plugins/azure/fix_plugin_azure/resource/metrics.py
plugins/azure/fix_plugin_azure/resource/mysql.py
plugins/azure/fix_plugin_azure/resource/network.py
plugins/azure/fix_plugin_azure/resource/postgresql.py
plugins/azure/fix_plugin_azure/resource/sql_server.py
plugins/azure/fix_plugin_azure/resource/storage.py
plugins/azure/fix_plugin_azure/resource/web.py

[azure][chore] Adjust service names

---

fixcore/fixcore/model/exportable_model.py
fixcore/fixcore/model/model_handler.py
fixlib/fixlib/core/model_export.py
fixlib/fixlib/graph/__init__.py
fixlib/test/core/model_export_test.py

[core][feat] Add kind description in multi tenant mode

---

fixcore/fixcore/model/graph_access.py
fixcore/fixcore/model/resolve_in_graph.py
fixcore/fixcore/static/api-doc.yaml
fixcore/tests/fixcore/model/graph_access_test.py
fixlib/fixlib/baseresources.py
fixlib/fixlib/core/model_export.py
plugins/aws/fix_plugin_aws/__init__.py

[inventory][chore] Remove phantom property

---

fixlib/fixlib/baseresources.py
fixlib/fixlib/core/model_export.py
plugins/aws/fix_plugin_aws/resource/base.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/resource/compute.py
plugins/azure/fix_plugin_azure/resource/cosmosdb.py
plugins/azure/fix_plugin_azure/resource/machinelearning.py
plugins/azure/fix_plugin_azure/resource/microsoft_graph.py
plugins/azure/fix_plugin_azure/resource/monitor.py
plugins/azure/fix_plugin_azure/resource/mysql.py
plugins/azure/fix_plugin_azure/resource/network.py
plugins/azure/fix_plugin_azure/resource/postgresql.py
plugins/azure/fix_plugin_azure/resource/storage.py

[lib][chore] Dedicated property for provider_link

---

plugins/azure/fix_plugin_azure/resource/authorization.py

[azure][fix]: Fix `connect_in_graph` method of `AzureAuthorizationRoleAssignment` resource

---

fixcore/fixcore/cli/command.py
fixcore/tests/fixcore/cli/command_test.py
fixcore/tests/fixcore/web/api_test.py

[core][feat] Add node command

---

plugins/azure/fix_plugin_azure/collector.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/resource/cosmosdb.py
plugins/azure/test/collector_test.py

[azure][feat] Connect CosmosDB resources to the location instead of subscription

---

plugins/gcp/fix_plugin_gcp/collector.py
plugins/gcp/fix_plugin_gcp/gcp_client.py
plugins/gcp/fix_plugin_gcp/resources/aiplatform.py
plugins/gcp/fix_plugin_gcp/resources/base.py
plugins/gcp/tools/model_gen.py

[gcp][feat] Add Vertex AI collection

---

plugins/aws/fix_plugin_aws/resource/ecr.py
plugins/aws/fix_plugin_aws/resource/s3.py
plugins/aws/test/resources/s3_test.py

[aws][feat] Add lifecycle policy to the S3 resource

---

plugins/aws/fix_plugin_aws/collector.py
plugins/aws/fix_plugin_aws/resource/apigateway.py
plugins/aws/fix_plugin_aws/resource/bedrock.py
plugins/aws/fix_plugin_aws/resource/cloudwatch.py
plugins/aws/fix_plugin_aws/resource/s3.py
plugins/aws/test/resources/apigateway_test.py
plugins/aws/test/resources/cloudwatch_test.py

[aws][feat] Add additional policies to the cloudwatch 

---

fixcore/fixcore/db/arango_query.py
fixcore/tests/fixcore/db/arango_query_test.py
fixcore/tests/fixcore/db/timeseriesdb_test.py

[core][fix] move slotted data to previous slot, not next

---

plugins/aws/fix_plugin_aws/collector.py
plugins/aws/fix_plugin_aws/resource/base.py
plugins/azure/fix_plugin_azure/collector.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/test/collector_test.py
plugins/gcp/fix_plugin_gcp/collector.py
plugins/gcp/fix_plugin_gcp/resources/base.py

[azure][fix] Compute unused regions as last step

---

plugins/aws/fix_plugin_aws/collector.py
plugins/aws/fix_plugin_aws/resource/amazonq.py
plugins/aws/fix_plugin_aws/resource/base.py
plugins/aws/fix_plugin_aws/resource/iam.py
plugins/aws/fix_plugin_aws/resource/kinesis.py
plugins/aws/fix_plugin_aws/resource/opensearch.py
plugins/aws/fix_plugin_aws/resource/redshift.py

[aws][fix] Add missing resource docs

---

plugins/azure/fix_plugin_azure/collector.py
plugins/azure/test/collector_test.py

[azure][feat]: Improved AzureComputeDiskTypePricing deletion

---

plugins/azure/fix_plugin_azure/resource/authorization.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/resource/compute.py
plugins/azure/fix_plugin_azure/resource/cosmosdb.py
plugins/azure/fix_plugin_azure/resource/machinelearning.py
plugins/azure/fix_plugin_azure/resource/network.py
plugins/azure/fix_plugin_azure/resource/security.py
plugins/azure/fix_plugin_azure/resource/storage.py
plugins/azure/test/collector_test.py
plugins/gcp/fix_plugin_gcp/resources/compute.py

[azure][fix] Define Phantom Resources

---

fixcore/fixcore/model/graph_access.py
fixcore/tests/fixcore/model/graph_access_test.py

[core][fix] Add kinds to content hash

---

plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/resource/network.py
plugins/azure/test/collector_test.py
plugins/azure/test/files/network/virtualNetworkGateways.json

[azure][feat] Collect certificates from sub resources

---

README.md

[inventory][chore] Add a link to contribution guidelines

---

plugins/aws/fix_plugin_aws/resource/bedrock.py
plugins/aws/fix_plugin_aws/resource/dynamodb.py

[aws][fix] Handle AWS server errors properly

---

plugins/aws/fix_plugin_aws/collector.py
plugins/aws/test/__init__.py

Enable access edges collection

---

plugins/aws/fix_plugin_aws/resource/scp.py

Wrap scp collection into try catch

---

plugins/azure/fix_plugin_azure/resource/monitor.py
plugins/azure/test/monitor_test.py

[azure][feat]: Add more connections from monitor

---

fixcore/fixcore/core_config.py
fixcore/fixcore/report/report_config.py
fixcore/fixcore/user/__init__.py
fixlib/fixlib/config.py

[core][fix] Export property documentation for configs

---

README.md

completely updated our README with details on how Fix Inventory works, use cases, examples.

Update README.md with details

---

README.md

Added new images for shell and graph

Added images to README.md

---

plugins/aws/fix_plugin_aws/collector.py

[aws][fix] Turn off access edge collection

---

fixlib/fixlib/baseresources.py
plugins/aws/fix_plugin_aws/access_edges.py

Add an access section next to permissions in IAM edges

---

plugins/aws/fix_plugin_aws/collector.py

Enable access_edges via env variable

---

.gitignore
plugins/posthog/fix_plugin_posthog/resources.py

[fixinventory][chore] Remove unused gitignore entries

---

fixcore/fixcore/report/__init__.py
fixcore/fixcore/report/inspector_service.py

[core][fix] Count failing resources correctly

---

plugins/aws/fix_plugin_aws/access_edges.py

Store access levels directly on the reported section

---

fixcore/fixcore/model/graph_access.py
fixcore/tests/fixcore/db/graphdb_test.py

[core][fix] Use id and name for descendant count

---

plugins/azure/fix_plugin_azure/resource/compute.py

[azure][fix] Metadata

---

fixlib/fixlib/baseresources.py
plugins/aws/fix_plugin_aws/resource/ec2.py
plugins/aws/fix_plugin_aws/resource/inspector.py
plugins/aws/test/resources/files/ec2/describe-instance-types__instance_type_mac2_metal_m4_large.json

[aws][feat] Add searching instances also by region and make `SEVERITY_MAPPING` statically

---

README.md

Update README.md fix Get Started Guide Link (Fixes: 2285 https://github.com/someengineering/fixinventory/issues/2285)

---

fixlib/fixlib/baseresources.py
plugins/aws/fix_plugin_aws/resource/sqs.py
plugins/azure/fix_plugin_azure/resource/storage.py
plugins/gcp/fix_plugin_gcp/collector.py
plugins/gcp/fix_plugin_gcp/resources/pubsub.py
plugins/gcp/tools/model_gen.py

[gcp][feat] Add Pub/Sub service collection

---

.github/workflows/publish.yml

[inventory][fix] docker-compose -> docker compose

---

.github/workflows/publish.yml

[inventory][fix] docker-compose no pull info

---

plugins/aws/fix_plugin_aws/resource/inspector.py
plugins/gcp/fix_plugin_gcp/resources/scc.py

[plugins][feat]: Change SCC and Inspector2 details collection

---

plugins/aws/fix_plugin_aws/resource/bedrock.py
plugins/aws/fix_plugin_aws/resource/ecr.py
plugins/aws/test/resources/files/bedrock_agent/get-knowledge-base__foo.json

[aws][fix] Fix errors associated with AwsBedrock and AwsEcr resources

---

fixcore/tests/fixcore/config/config_handler_service_test.py
fixcore/tests/fixcore/conftest.py
fixcore/tests/fixcore/web/content_renderer_test.py
fixlib/test/test_config.py
fixlib/test/test_web.py
plugins/k8s/test/resources_test.py

This PR removes unused imports.

[style] Remove unused imports

---

fixcore/tests/fixcore/cli/cli_test.py
fixcore/tests/fixcore/cli/command_test.py
fixcore/tests/fixcore/dependencies_test.py
fixcore/tests/fixcore/model/model_test.py
fixcore/tests/fixcore/web/api_client.py
fixcore/tests/fixcore/web/api_test.py
fixcore/tools/grapher.py
fixcore/tools/render_dot.py

This PR makes the code conformant with [F541](https://docs.astral.sh/ruff/rules/f-string-missing-placeholders/#f-string-missing-placeholders-f541).

[style] F-strings are not necessary if there is no placeholder

---

docker-compose.yaml

[fix][chore] Use latest arangodb 3.11

---

fixcore/pyproject.toml
fixlib/pyproject.toml
fixmetrics/pyproject.toml
fixshell/pyproject.toml
plugins/aws/pyproject.toml
plugins/aws/tools/awspolicygen/setup.py
plugins/azure/pyproject.toml
plugins/digitalocean/pyproject.toml
plugins/dockerhub/pyproject.toml
plugins/example_collector/pyproject.toml
plugins/gcp/pyproject.toml
plugins/gcp/tools/gcppolicygen/setup.py
plugins/github/pyproject.toml
plugins/hetzner/pyproject.toml
plugins/k8s/pyproject.toml
plugins/onelogin/pyproject.toml
plugins/posthog/pyproject.toml
plugins/random/pyproject.toml
plugins/scarf/pyproject.toml
plugins/slack/pyproject.toml

Match license string to [trove classifier](https://pypi.org/classifiers/)

[fix][fix] Update license to match Trove classifier
