someengineering/fixinventory

plugins/tag_aws_alb_target_groups/cloudkeeper_plugin_tag_aws_alb_target_groups/__init__.py
plugins/tagvalidator/cloudkeeper_plugin_tagvalidator/__init__.py

There was a check-then-act race in the tagvalidator and alb target group tagger plugins.
The condition for the race to occur would be for the tagging to take exactly as long as one collect/clean loop takes (by default ~1h). I.e. extremely unlikely. Had the race occurred it would mean that resource get tagged with the same value twice, essentially doubling the number of outbound API calls.

Fix a race in tagvalidator and alb target group tagger

---

cloudkeeper/cloudkeeper/baseresources.py
cloudkeeper/cloudkeeper/cleaner.py
cloudkeeper/cloudkeeper/paralleltagger.py
plugins/aws/cloudkeeper_plugin_aws/resources.py
plugins/aws/cloudkeeper_plugin_aws/utils.py
plugins/example_collector/cloudkeeper_plugin_example_collector/__init__.py
plugins/tag_aws_ctime/cloudkeeper_plugin_tag_aws_ctime/__init__.py
plugins/tagvalidator/cloudkeeper_plugin_tagvalidator/__init__.py

Cleanly detach an Internet Gatway from its VPCs before attempting to delete it.

Cleanly remove VPCs, Internet Gateways, Route Tables and Security Groups and implement parallel resource tagging

---

cloudkeeper/cloudkeeper/baseplugin.py
cloudkeeper/cloudkeeper/baseresources.py
cloudkeeper/cloudkeeper/cli.py
cloudkeeper/cloudkeeper/graph.py
cloudkeeper/cloudkeeper/utils.py
plugins/cleanup_aws_vpcs/cloudkeeper_plugin_cleanup_aws_vpcs/__init__.py

When a VPC contains active instance we do no longer try to clean it and remove the cleanup flag from the VPC.

Add VPC cleanup failsafes

---

README.md
plugins/keepercore/README.md
plugins/keepercore/cloudkeeper_plugin_keepercore/__init__.py
plugins/keepercore/setup.cfg
plugins/keepercore/setup.py
plugins/keepercore/test/test_args.py
plugins/keepercore/tox.ini

This adds a plugin that can generate a model and send existing graph data to the keepercore backend service.

Keepercore Plugin MVP

---

Dockerfile
cloudkeeper/cloudkeeper/baseresources.py
plugins/keepercore/cloudkeeper_plugin_keepercore/__init__.py
plugins/onprem/README.md
plugins/onprem/cloudkeeper_plugin_onprem/__init__.py
plugins/onprem/cloudkeeper_plugin_onprem/resources.py
plugins/onprem/cloudkeeper_plugin_onprem/ssh.py
plugins/onprem/setup.cfg
plugins/onprem/setup.py
plugins/onprem/test/test_args.py
plugins/onprem/tox.ini

Initial support for collecting on-prem resources

On-Prem collector plugin

---

keepercore/core/db/graphdb.py
keepercore/core/model/graph_access.py
keepercore/core/model/model.py
keepercore/core/web/api.py
keepercore/tests/core/db/graphdb_test.py

- `created` timestamp is stored  when record is created
- `updated` timestamp is stored when record is updated
- `ctime` property of replaced is replaced by created, if not set and defined in model

[keepercore] Preserve ctime of node values.

---

cloudkeeper/cloudkeeper/collectord.py
cloudkeeper/cloudkeeper/event.py
graph_exporter/graph_exporter/__main__.py
graph_exporter/requirements.txt

Implement worker pool for parallel tag updates and deletes

---

keepercore/.pylintrc
keepercore/core/cli/command.py
keepercore/core/db/graphdb.py
keepercore/core/event_bus.py
keepercore/tests/core/cli/command_test.py

[keepercore] Add protect command

---

keepercore/core/cli/cli.py
keepercore/core/cli/command.py
keepercore/core/task/job_handler.py
keepercore/core/task/task_handler.py
keepercore/tests/core/cli/command_test.py

[keepercore] Add start_tasks and tasks command

---

keepercore/core/cli/command.py

Allow to pass a reason message to the clean command which will yield a log statement for all resources that are marked for cleaning.
Fixes #147

[keepercore] clean [reason]

---

keepercore/core/cli/command.py
keepercore/core/db/graphdb.py
keepercore/core/error.py
keepercore/core/query/model.py
keepercore/core/query/query_parser.py
keepercore/core/web/api.py
keepercore/tests/core/cli/command_test.py
keepercore/tests/core/db/graphdb_test.py
keepercore/tests/core/worker_task_queue_test.py

[keepercore] tag command needs to resolve cloud/account/region/zone and update the resulting node

---

.github/workflows/check_pr_core.yml
keepercore/Makefile
keepercore/core/__main__.py
keepercore/requirements.txt
keepercore/tox.ini

[keepercore] Allow definition of args via env vars

---

keepercore/core/constants.py
keepercore/core/db/graphdb.py

[keepercore] Fix null<any is true

---

ckcore/core/query/model.py
ckcore/tests/core/query/query_parser_test.py

[fix] with clause needs to be rendered

---

ckcore/core/cli/cli.py
ckcore/core/parse_util.py

[ckcore] Show help for alias command

---

ckcore/core/model/graph_access.py
ckcore/tests/core/db/graphdb_test.py
ckcore/tests/core/model/graph_access_test.py
ckcore/tools/grapher.py
cklib/cklib/baseplugin.py
cklib/cklib/baseresources.py
cklib/cklib/graph/__init__.py

Merge update: merge=>replace to mark nodes as replace nodes

---

docs/readme.md
docs/source/_static/css/custom.css
docs/source/model.rst

Also fixed too short underline in model.rst

[docs] Added css styles for tables and added readme

---

ckui/src/assets/graphics/spaceship_appear.png
ckui/src/assets/graphics/spaceship_appear.png.import
ckui/src/scripts/sfdp_test.gd
ckui/src/scripts/singletons/singleton_events.gd
ckui/src/scripts/singletons/singleton_global.gd
ckui/src/ui/CloudkeeperUI.tscn
ckui/src/ui/elements/Element_CloudNode.tscn
ckui/src/ui/elements/Element_Spaceship.tscn
ckui/src/ui/elements/scripts/element_cloud_node.gd
ckui/src/ui/elements/scripts/element_spaceship.gd
ckui/src/ui/views/UI_CommandLine.tscn
ckui/src/ui/views/UI_GraphView.tscn
ckui/src/ui/views/scripts/main_cloudkeeper_ui.gd
ckui/src/ui/views/scripts/ui_command_line.gd
ckui/src/ui/views/scripts/ui_graph_view.gd

Added Buttons to the lower right to control it.

Added randomization, ordering and improved the spaceship mode

---

docs/source/start.rst

* improved docker start and log reading.

[docs] small update for docker startup documentation

---

cklib/cklib/jwt.py
cklib/requirements.txt
cklib/test/test_jwt.py

JWT functions

---

plugins/aws/cloudkeeper_plugin_aws/accountcollector.py
plugins/aws/cloudkeeper_plugin_aws/resources.py

* added GetAccessKeyLastUsed information to aws_iam_access_key

[plugin_aws] Added more data to improve CIS 1.4 compliance check capabilities

---

ckui/src/ui/views/scripts/ui_search.gd

Fixed two minor bugs in the search:
- Now traveling to a resource when clicked
- Now properly disconnecting the signal if neccessary

[ckui] Search bugs fixed

---

cklib/cklib/baseplugin.py
cklib/cklib/core/__init__.py
cklib/cklib/core/actions.py
cklib/cklib/core/query.py
cklib/cklib/pluginloader.py
ckworker/ckworker/__main__.py
ckworker/ckworker/ckcore.py
ckworker/ckworker/cleanup.py
ckworker/test/test_args.py
setup_venv.sh

Action plugins react to ckcore action events. They allow to implement functions like Slack notifications or additional cleanup planing.

[ckworker/cklib] Implement action plugins

---

ckcore/core/db/graphdb.py
ckcore/core/util.py

Fixed by creating a stable key from the final change.

[ckcore] fix patch nodes for non hashable types

---

README.md

Add following badges via [shields.io](https://shields.io/).
See rendered page here: https://github.com/someengineering/cloudkeeper/tree/mv/readme_badges

[docs] Add badges to readme and remove manual version

---

.github/workflows/lint_ckcore.yml
ckcore/core/web/api.py
ckcore/core/web/directives.py

These are required for the UI to be able to use [SharedArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer).

[ckcore] Add COOP/COEP headers

---

ckui/src/scripts/networking/api.gd
ckui/src/ui/3delements/scripts/ui_graph_3D.gd
ckui/src/ui/elements/scripts/element_treemap.gd

This PR fixes a lot of smaller problems with the HttpClient implementation on master when the UI is used in a browser.

[ckui] Fixed problems using HttpClient in a browser environment.

---

ckui/src/scripts/networking/api.gd
ckui/src/scripts/tools/jwt.gd
ckui/src/ui/3delements/scripts/element_graphview_3D.gd
ckui/src/ui/3delements/scripts/ui_graph_3D.gd
ckui/src/ui/CloudkeeperUI.tscn
ckui/src/ui/elements/scripts/element_popup_connect_to_core.gd
ckui/src/ui/elements/scripts/element_treemap.gd

As chunks can contain multiple graph elements (compared to the desktop client where 1 chunk = 1 element), some adjustments had to be made.

[ckui] Networking fixes for web-ui

---

release-notes.md

See the rendered version here: https://github.com/someengineering/cloudkeeper/blob/mv/release_notes/release-notes.md

[Docs] Release Notes 2.0.0a9

---

.github/workflows/check_pr_cklib.yml
cklib/cklib/x509.py
cklib/requirements.txt
cklib/test/test_x509.py
cklib/tox.ini

This PR adds the ability to bootstrap a CA, generate CSRs and sign them and write/read them to/from disk.

[cklib] x509 functions for bootstrapping a CA and issuing certs

---

ckcore/core/db/async_arangodb.py

[ckcore] Enable db optimization again.

---

ckcore/core/cli/cli.py
ckcore/core/cli/command.py
ckcore/tests/core/cli/cli_test.py
ckcore/tests/core/cli/command_test.py

[ckcore] add --with-origin to successors/predecessors/ancestors/descendants

---

ckcore/core/model/model.py
ckcore/core/model/model_handler.py
ckcore/core/static/api-doc.yaml
ckcore/core/web/api.py
ckcore/tests/core/model/__init__.py

- show/hide instances explicitly
- show bases of visible instances
- show descendants of visible instances

[ckcore] Improve the model/uml API

---

resotocore/core/cli/command.py

[resotocore] list should not add a predicate that is already shown by default

---

.github/workflows/docker-build.yml

(`DOCKERHUB_USER` and `DOCKERHUB_PASS` secrets need to be added to the repo.)

Build and push images to Docker Hub

---

resotocore/core/cli/command.py
resotocore/core/util.py
resotocore/tests/core/cli/command_test.py

[resotocore] Unify output for boolean properties.

---

resotocore/core/__main__.py
resotocore/core/cli/cli.py
resotocore/core/cli/command.py
resotocore/core/dependencies.py
resotocore/core/task/task_handler.py
resotocore/tests/core/cli/command_test.py
resotocore/tests/core/task/task_handler_test.py

- add the `--version` flag which will print the version and exit
- add the `version` to help 
- add a new command `system info` which shows information about the system
Fixes #515

[resostocore] Add system info

---

resotocore/core/static/api-doc.yaml
resotocore/core/web/api.py

Allow the normal query API to define the section as query parameter to get the same functionality.

[resotocore] Remove section aware query API

---

release-notes.md

See rendered version here: https://github.com/someengineering/resoto/blob/mv/release_notes/release-notes.md

[docs] Release Notes for 2.0.0a10

---

.github/workflows/resotocore_coverage.yml
.github/workflows/resotocore_test.yml
resotocore/core/db/db_access.py
resotocore/core/dependencies.py
resotocore/tests/core/cli/cli_test.py
resotocore/tests/core/cli/command_test.py
resotocore/tests/core/db/arango_query_test.py
resotocore/tests/core/db/async_arangodb_test.py
resotocore/tests/core/db/db_access_test.py
resotocore/tests/core/db/graphdb_test.py
resotocore/tests/core/db/jobdb_test.py
resotocore/tests/core/db/modeldb_test.py
resotocore/tests/core/db/runningtaskdb_test.py
resotocore/tests/core/db/subscriberdb_test.py
resotocore/tests/core/db/templatedb_test.py
resotocore/tests/core/model/db_updater_test.py
resotocore/tests/core/task/task_handler_test.py
resotocore/tests/core/web/api_test.py
resotocore/tests/core/web/certificate_handler_test.py

Boot process:
- start to connect with username/password
- if this is not allowed
- try to access the system database with default settings (username=root, password=None)
- in case this is not allowed, give up
- otherwise try to create user and database
- in case this is not allowed, give up
- try to connect again

[resotocore] Create user/database with default setup

---

resotocore/core/model/graph_access.py
resotocore/tests/core/model/graph_access_test.py
resotocore/tests/core/model/model_test.py
resotocore/tools/grapher.py

For backward compatibility `/replace` is still supported.

[resotocore] graph update expect the replace flag in the metadata section

---

resotocore/core/cli/command.py
resotocore/core/db/arango_query.py
resotocore/core/db/async_arangodb.py
resotocore/core/db/graphdb.py
resotocore/core/dependencies.py
resotocore/core/model/graph_access.py
resotocore/tests/core/cli/command_test.py
resotocore/tests/core/db/graphdb_test.py
resotocore/tests/core/model/graph_access_test.py
resotocore/tests/core/query/__init__.py
resotocore/tests/core/task/task_handler_test.py
resotocore/tools/grapher.py

Edge type dependency renamed to default.
This PR includes a db migration, which renames the related edge collection.

[resotocore][feat] Rename edge type dependency to default

---

resotocore/core/model/graph_access.py
resotocore/tests/core/model/graph_access_test.py

Checks if a graph is acyclic.
- Fixes #XXXX

[resotocore][feat] Implement graph.is_acyclic_per_edge_type

---

resotocore/core/db/arango_query.py
resotocore/core/db/graphdb.py
resotocore/core/feature.py
resotocore/core/model/graph_access.py
resotocore/core/web/api.py
resotocore/tests/core/cli/command_test.py
resotocore/tests/core/model/graph_access_test.py
resotocore/tests/core/web/api_client.py
resotocore/tests/core/web/api_test.py

This PR enables the global search feature.
All documents after the next ingestion will be indexed.
The search feature is available via the REST API.
CLI commands will follow in a separate PR.
- Fixes #XXXX

[resotocore][feat] Enable global search

---

resotocore/core/query/model.py
resotocore/core/query/query_parser.py
resotocore/tests/core/query/model_test.py

Automatic merge queries also for aggregation variables and functions
- Fixes #588

[resotocore][fix] Automatic merge queries also for aggregation variables and functions

---

resotolib/resotolib/baseresources.py
resotolib/resotolib/graph/__init__.py
resotometrics/resotometrics/__main__.py

Updates metrics queries to use ancestors section in aggregate function introduced in #590 

[resotolib] Update metrics queries to use new ancestors section

---

README.md

[README] update outdated docs URI

---

resotocore/core/db/graphdb.py

[resotocore][fix] Use debug logging instead of info

---

resotocore/core/db/graphdb.py
resotocore/core/model/graph_access.py
resotocore/tests/core/db/graphdb_test.py

[resotocore][fix] Hash and flat need to be recomputed on update

---

plugins/aws/resoto_plugin_aws/cmd/s3.py
plugins/aws/tox.ini
plugins/cleanup_aws_alarms/tox.ini
plugins/cleanup_aws_loadbalancers/tox.ini
plugins/cleanup_aws_vpcs/tox.ini
plugins/cleanup_expired/tox.ini
plugins/cleanup_untagged/tox.ini
plugins/cleanup_volumes/tox.ini
plugins/example_collector/tox.ini
plugins/gcp/tox.ini
plugins/github/tox.ini
plugins/k8s/tox.ini
plugins/onelogin/tox.ini
plugins/onprem/resoto_plugin_onprem/ssh.py
plugins/onprem/tox.ini
plugins/protect_snowflakes/tox.ini
plugins/slack/tox.ini
plugins/tagvalidator/tox.ini
plugins/vsphere/tox.ini
resotocore/requirements-test.txt
resotolib/requirements-test.txt
resotometrics/tox.ini
resotoshell/tox.ini
resotoworker/tox.ini

[resoto][chore] Fix test dependencies in tox

---

resotocore/core/static/api-doc.yaml
resotocore/core/web/api.py

Mark unstable API as experimental.
resoto is used as the default name for the graph identifier.

[resotocore][api-docs] Mark experimental API

---

dockerV2/bootstrap

Fixes a typo in the `runuser` call

[docker] Fix runuser call

---

kubernetes/chart/Chart.yaml

Updates the helm chart appVersion to the current latest image tag

[helm] Update helm chart appVersion

---

docker-compose.yaml

Pin compose file to next tagged version

[docker] Pin compose to next tagged version

---

resotoworker/resotoworker/cleanup.py

Use ancestors on the root level 

[resotoworker] Use ancestors on the new `/ancestors` level

---

resotocore/core/model/model_handler.py

Updates colors in generated UML diagrams.
**Examples using these updated colors:**
https://resoto.com/docs/reference/data-models/aws
https://resoto.com/docs/reference/data-models/gcp

[resotocore][fix] Update UML diagram colors

---

resotocore/core/cli/command.py
resotocore/core/db/graphdb.py
resotocore/core/web/api.py
resotocore/tests/core/db/graphdb_test.py

[resotocore][fix] tag delete/update should replace the result not merge

---

resotocore/core/db/arango_query.py
resotocore/core/db/async_arangodb.py
resotocore/core/db/graphdb.py
resotocore/core/static/api-doc.yaml
resotocore/tests/core/db/graphdb_test.py

[resotocore][feat] Add edge_type when edges are rendered

---

resotocore/core/query/model.py
resotocore/tests/core/cli/cli_test.py
resotocore/tests/core/query/model_test.py
resotocore/tests/core/query/query_parser_test.py

Render a default navigation `-->` as `-default->`.

[resotocore][fix] Render edge_type always

---

resotocore/core/__main__.py
resotocore/core/db/db_access.py
resotocore/core/dependencies.py
resotocore/core/model/db_updater.py

[resotocore][fix] Increase outdated merge timeout and make it configurable

---

resotocore/core/cli/cli.py
resotocore/core/cli/command.py
resotocore/core/db/graphdb.py
resotocore/core/model/model.py
resotocore/core/task/task_description.py
resotocore/core/task/task_handler.py
resotocore/core/util.py
resotocore/tests/core/cli/command_test.py
resotocore/tests/core/model/model_test.py
resotocore/tests/core/task/job_handler_test.py

[resotocore][fix] Load model more efficient.

---

resotolib/resotolib/baseresources.py
resotolib/resotolib/graph/__init__.py
resotolib/test/test_graph.py
resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/collect.py
resotoworker/resotoworker/resotocore.py

This releases the in-memory graph as soon as its JSON representation has been written to disk.
It also optimises the writing of the JSON by caching the resource chksums which are used as node IDs and used in the edges from/to representation.

[resotolib/resotoworker][feat] Early release of in-memory graph

---

plugins/aws/resoto_plugin_aws/accountcollector.py
plugins/aws/resoto_plugin_aws/utils.py
plugins/aws/test/test_utils.py

Constructs the S3 ARN.
- Fixes #654

[plugins/aws][feat] Construct S3 ARN (fixes #654)

---

resotocore/core/cli/command.py
resotocore/core/web/api.py
resotocore/core/web/content_renderer.py
resotocore/tests/core/cli/command_test.py
resotocore/tests/core/web/content_renderer_test.py

[resotocore][fix] `write` add linefeed to any chunk of data.

---

resotocore/pyproject.toml

[resotocore][bug] Fix typo in pyproject.toml

---

docker-compose.yaml
dockerV2/prometheus.yml

Adds Prometheus to docker-compose.yml

[docker][feat] Add Prometheus to compose file

---

resotocore/resotocore/task/scheduler.py

Until APScheduler>3.8.1 is released.

[resotocore][fix] Swallow warning from APScheduler

---

kubernetes/setup-kind.sh

[kubernetes][bug] Fix typo

---

plugins/aws/resoto_plugin_aws/accountcollector.py

Make AWS retry to collect a region on RequestLimitExceeded error using exponential backoff

[plugin/aws][feat] Retry on RequestLimitExceeded

---

kubernetes/setup-kind.sh
resotocore/MANIFEST.in

[resotocore][bug] Fix typo in MANIFEST file

---

resotocore/resotocore/cli/command.py

The description of the list command was changed to a more suitable one.

[resotocore][chore] Update the list command description

---

resotolib/resotolib/baseresources.py
resotolib/resotolib/core/config.py
resotolib/resotolib/utils.py
resotometrics/MANIFEST.in
resotometrics/requirements.txt
resotometrics/resotometrics/__main__.py
resotometrics/resotometrics/default_metrics.yaml

Removes the hard coded metrics and loads them form the core

[resotolib/resotometrics][feat] Load metrics from core

---

resotocore/resotocore/db/arango_query.py

The limit of a query part was applied to the pre and post-filter criteria of a merge query.
Example:
```
> search is(volume) and age>10mo  {ancestors.account: <-[1:]- is(account)} /ancestors.account.reported.id~eng limit 1
```
All volumes older than ten months need to be selected first, then the account is merged, and the post-filter applied.
The limit is now applied afterward, not after the first filter.

[resotocore][fix] do not add a limit to a merge term pre-filter

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/dependencies.py

I realized that a backup -> restore cycle did restore all data but not the graph description itself.
This information is considered internal and needs to be included explicitly.

[resotocore][fix] backup/restore did not recreate the graph

---

resotolib/resotolib/graph/export.py
resotolib/test/test_graph_export.py

Export model data also derived from dynamically created classes.
- Fixes #XXXX

[resotolib][feat] Export resotocore model for a dynamically created object

---

resotocore/resotocore/__main__.py
resotocore/resotocore/config/__init__.py
resotocore/resotocore/config/config_handler_service.py
resotocore/resotocore/db/async_arangodb.py
resotocore/resotocore/db/configdb.py
resotocore/resotocore/db/db_access.py
resotocore/resotocore/db/entitydb.py
resotocore/resotocore/model/model.py
resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py
resotocore/resotocore/web/content_renderer.py
resotocore/tests/resotocore/config/config_handler_service_test.py
resotocore/tests/resotocore/db/configdb_test.py
resotocore/tests/resotocore/db/entitydb.py
resotocore/tests/resotocore/model/model_test.py
resotocore/tests/resotocore/web/api_client.py
resotocore/tests/resotocore/web/api_test.py
resotocore/tests/resotocore/web/content_renderer_test.py
resotoshell/resotoshell/__main__.py

A config item can have a typed model.
When the model is defined, every change to the config item is checked against the model.
Furthermore, it allows defining the config via yaml with comments.
- Fixes #XXXX

[resotocore][feat] Introduce optionally typed configs

---

resotocore/resotocore/__main__.py
resotocore/resotocore/cli/cli.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/cli/model.py
resotocore/resotocore/db/entitydb.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/cli/cli_test.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/task/task_handler_test.py
resotocore/tests/resotocore/web/api_test.py
resotoshell/resotoshell/__main__.py
resotoshell/resotoshell/shell.py

```shell
configs list
configs show <cfg_id>
configs set <cfg_id> <prop>=<value> [, <prop>=<value>]
configs edit <cfg_id>
configs update <cfg_id> <path>
configs delete <cfg_id>
```
- `configs list`: get the list of all config ids in the system.
- `configs show <cfg_id>`: show the configuration with provided identifier.
- `configs set <cfg_id> <prop>=<value>`: set one or more property values in the configuration with provided id.
- `configs edit <cfg_id>`: edit the complete configuration with provided id as file
- `configs update <cfg_id> <path>`: update or create the configuration with provided id with content of given file.
- `configs delete <cfg_id>`: delete the configuration with given identifier.
- cfg_id [mandatory]: The identifier of the configuration.
- prop: the path of the …

[resotocore][feat] Add configs command to change configuration.

---

resotoworker/resotoworker/resotocore.py

Fix a bug where resotoworker was not able to communicate to resotocore.
- Fixes #XXXX

[resotoworker][fix] Explicitly set the content type when calling core

---

plugins/digitalocean/resoto_plugin_digitalocean/collector.py

Added a fix where a default value is provided when tags are accessed during the collection.

[plugins/digitalocean][fix] Collect tags with a default value

---

resotocore/requirements.txt
resotocore/resotocore/__main__.py
resotocore/resotocore/config/core_config_handler.py
resotocore/resotocore/core_config.py
resotocore/resotocore/validator.py
resotocore/resotocore/worker_task_queue.py
resotocore/tests/resotocore/config/core_config_handler_test.py
resotocore/tests/resotocore/core_config_test.py
resotocore/tests/resotocore/validator_test.py

[resotocore][feat] Add config validation.

---

plugins/digitalocean/requirements.txt
plugins/digitalocean/resoto_plugin_digitalocean/client.py
plugins/digitalocean/resoto_plugin_digitalocean/utils.py

Added an exponential backoff for the digital ocean client.
- Fixes #XXXX

[plugins/digitalocean][feat] add an exponential backoff for DO client

---

setup_venv.sh

Added a vsphere plugin to the setup_venv.py script.

[plugins/digitalocean][feat] Add vsphere plugin to setup_venv.py

---

resotocore/Makefile
setup_venv.sh

Fix the path and remove a separate venv requirement using the Makefile.

[resotocore][chore] Fix mypy setup

---

resotocore/requirements-dev.txt
resotocore/requirements-test.txt
resotocore/requirements.txt
resotolib/requirements-test.txt
resotolib/requirements.txt
resotoshell/requirements.txt

[resoto][chore] Bump libs

---

plugins/digitalocean/resoto_plugin_digitalocean/__init__.py
plugins/digitalocean/resoto_plugin_digitalocean/client.py
plugins/digitalocean/resoto_plugin_digitalocean/collector.py
plugins/digitalocean/resoto_plugin_digitalocean/resources.py
plugins/digitalocean/test/test_collector.py

Added the capability to cleanup most of the digitalocean resources (except spaces).

[feat][plugins/digitalocean] Add cleanup capabilities to DO collector plugin

---

resotolib/resotolib/baseresources.py

This makes a field that defaults to `None` `Optional` in the data model.

[resotolib][bug] Make load balancer `public_ip_address` `Optional`

---

.github/workflows/docker-build.yml

Format PRs to the [someengineering/resoto.com](https://github.com/someengineering/resoto.com) repository.

[ci][chore] Format PRs to someengineering/resoto.com with Prettier

---

plugins/digitalocean/resoto_plugin_digitalocean/client.py
plugins/digitalocean/resoto_plugin_digitalocean/resources.py

Added support for DigitalOcean Spaces cleanup.

[feat][plugins/digitalocean] Add support for spaces cleanup

---

plugins/digitalocean/resoto_plugin_digitalocean/client.py
plugins/digitalocean/resoto_plugin_digitalocean/collector.py
plugins/digitalocean/resoto_plugin_digitalocean/resources.py
plugins/digitalocean/resoto_plugin_digitalocean/utils.py
plugins/digitalocean/test/fixtures/__init__.py
plugins/digitalocean/test/fixtures/alerts.py
plugins/digitalocean/test/test_collector.py

Added support for tag-related operations in digital ocean plugin as well as collection of alert policies

[plugins/digitalocean][feat] Add support for actions with tags, collect alert policies

---

plugins/digitalocean/resoto_plugin_digitalocean/client.py
resotolib/requirements-test.txt

Fixed a bug where the retry decorator did not work

[plugins/digitalocean][fix] fix the retry decorator

---

.github/workflows/docker-build.yml

[ci][chore] add env var to correct step

---

resotolib/resotolib/config.py

Allow `--override` of lists, sets, tuples.

[resotolib][feat] Allow override of collection attributes

---

resotocore/resotocore/db/arango_query.py
resotocore/tests/resotocore/db/arango_query_test.py

[resotocore][fix] Coerce ancestor properties correctly

---

resotocore/resotocore/__main__.py
resotocore/resotocore/config/core_config_handler.py
resotocore/resotocore/core_config.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/dependencies.py
resotocore/resotocore/message_bus.py
resotocore/resotocore/model/model.py
resotocore/resotocore/task/start_workflow_on_first_subscriber.py
resotocore/resotocore/task/task_handler.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/core_config_test.py
resotocore/tests/resotocore/model/model_test.py
resotolib/resotolib/core/__init__.py
resotolib/resotolib/core/model_export.py
resotolib/resotolib/core/tasks.py

- remove cmd line args that are available via configuration
- api config now supports web-hosts, web-port and web-path
- remove deprecated db migrations
- json array is able to coerce non array values
- web api can be mounted on a sub-path
- Fixes #XXXX

[resotocore][feat] Remove deprecated cmd line args

---

resotocore/resotocore/__main__.py
resotocore/resotocore/core_config.py
resotocore/resotocore/dependencies.py
resotocore/resotocore/parse_util.py
resotocore/tests/resotocore/core_config_test.py

- read the git commit hash created by docker build
- detect if running inside docker
- adjust the default hosts value according to docker detection

[resotocore][fix] Define default host in docker env

---

plugins/aws/resoto_plugin_aws/config.py
plugins/aws/test/test_config.py
plugins/gcp/resoto_plugin_gcp/config.py
plugins/gcp/test/test_config.py
plugins/k8s/resoto_plugin_k8s/config.py
plugins/k8s/test/test_config.py
resotolib/resotolib/utils.py
resotoworker/resotoworker/config.py

Detect number of usable CPU threads and set defaults accordingly.
Fixes: #372 

[resotolib/plugins][feat] Better thread num defaults

---

docker-compose.yaml

Prepare docker-compose file for new config syntax

[docker][fix] Prepare docker compose for config update

---

.editorconfig
.github/workflows/k8s-build.yml
kubernetes/chart/Chart.yaml
kubernetes/chart/templates/resotocore/deployment.yaml
kubernetes/chart/templates/resotocore/service.yaml
kubernetes/chart/templates/resotormetrics/deployment.yaml
kubernetes/chart/templates/resotoworker/deployment.yaml
kubernetes/chart/values.schema.json
kubernetes/chart/values.yaml
kubernetes/setup-kind.sh

[resoto][fix] Make helm chart work again

---

docker-compose.yaml
resotolib/resotolib/x509.py

Updates docker-compose to add resotocore to core's TLS certificate and updates TLS functions to add the name in addition to the local names.

[docker][fix] Extend local DNS names instead of replacing it

---

resotocore/resotocore/core_config.py
resotocore/resotocore/dependencies.py
resotolib/resotolib/args.py
resotolib/test/test_args.py

[resotolib][fix] Fix support for types in argparse env handling

---

resotocore/resotocore/core_config.py
resotocore/resotocore/model/model.py
resotocore/tests/resotocore/config/config_handler_service_test.py
resotocore/tests/resotocore/core_config_test.py
resotocore/tests/resotocore/model/model_test.py
resotocore/tests/resotocore/web/api_test.py

..and fallback to default configuration, where the value is not available.
- Fixes #XXXX

[resotocore][fix] Try to coerce configuration as good as possible

---

resotolib/resotolib/core/__init__.py
resotometrics/resotometrics/__main__.py
resotoshell/resotoshell/__main__.py
resotoworker/resotoworker/__main__.py

On start make `resh` check whether the core is online or not.

[resotoshell][fix] Check if resotocore is up in resh

---

Dockerfile
Dockerfile.resotobase

Default to xterm-256colors if not otherwise specified.

[docker][fix] Default to xterm-256colors

---

resotocore/resotocore/cli/cli.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/web/api.py
resotocore/resotocore/web/certificate_handler.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/web/api_test.py

Create new certificates based on the internal root ca.
- Fixes #XXXX

[resotocore][feat] Add certificate command

---

resotolib/README.md
resotometrics/README.md
resotoshell/README.md
resotoworker/README.md

Update READMEs to reflect 2.0 changes.
Eventually all content should be merged with the docs and the READMEs just link there.

[resoto][chore] Update READMEs to reflect 2.0 changes

---

resotocore/README.md
resotometrics/README.md
resotoshell/README.md
resotoworker/README.md

Update core cli args. Also put a link to each components docs in the READMEs.

[resoto][docs] Update core args and link all component READMEs to the corresponding docs

---

resotocore/resotocore/cli/cli.py
resotocore/resotocore/config/config_handler_service.py
resotocore/resotocore/config/core_config_handler.py
resotocore/resotocore/core_config.py
resotocore/tests/resotocore/config/core_config_handler_test.py
resotocore/tests/resotocore/core_config_test.py

separate configuration for `resoto.core` and `resoto.core.commands`.
- Fixes #XXXX

[resotocore][feat] Separate custom core command configuration

---

resotocore/resotocore/core_config.py
resotocore/resotocore/model/model.py
resotocore/resotocore/task/task_handler.py
resotocore/resotocore/validator.py
resotocore/tests/resotocore/config/config_handler_service_test.py
resotocore/tests/resotocore/core_config_test.py
resotocore/tests/resotocore/model/model_test.py
resotocore/tests/resotocore/task/task_handler_test.py
resotocore/tests/resotocore/validator_test.py

Allow configuration of workflow schedules.

[resotocore][feat] Allow configuration of workflow schedules

---

plugins/digitalocean/resoto_plugin_digitalocean/client.py
plugins/digitalocean/resoto_plugin_digitalocean/collector.py
plugins/digitalocean/resoto_plugin_digitalocean/resources.py
plugins/digitalocean/resoto_plugin_digitalocean/utils.py
plugins/digitalocean/test/test_collector.py
resotolib/resotolib/baseresources.py

Added support for key/value bugs. 

[plugins/digitalocean][feat] Support key/value tags

---

docker-compose.yaml

[docker][chore] Update compose file for 2.0.0

---

tools/release_notes.py

- Documentation is now a separate section
- The groups are now always sorted to have a fixed order

[feat][resoto] Add documentation as release note section

---

resotocore/tools/README.md

Added a small readme for the rendering script.

[resoto] Add the instruction for the graph rendering script

---

resotocore/tools/README.md

Changed the wording in the readme for the rendering script.

[resoto] Update rendering script docs

---

.github/workflows/resotocore_coverage.yml
.github/workflows/resotocore_test.yml

[resotocore][fix] No analytics in CI

---

resotolib/resotolib/core/ca.py

Update certificate files on disk so tmp cleaner doesn't purge them.

[resotolib][fix] Update certificate files on disk after a certain time has passed

---

Dockerfile
Dockerfile.resotobase

Adds editors to the Docker image for `config edit` to use.

[docker][fix] Add vi and nano to Docker images

---

kubernetes/chart/templates/arango-user-secret.yaml
kubernetes/chart/values.yaml
kubernetes/setup-kind.sh

[feat][helm] Simplify helm chart deployment

---

Dockerfile.resotobase

Copies arangodump and arangorestore into the base container.

[docker][fix] copy ArangoDB client binaries

---

resotocore/tools/README.md

Fixed typo in render_dot readme.

[resoto][docs] fix typo in render_dot readme

---

resotocore/requirements-test.txt
resotocore/tests/resotocore/web/api_test.py
resotocore/tools/render_dot.py

Resotoclient is now used in API tests.

[resotocore][fix] Use resotoclient in tests

---

kubernetes/chart/values.yaml

Define the UI by default in helm chart.

[resoto][fix] Define the UI by default in helm chart

---

resotocore/resotocore/cli/cli.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/cli/model.py
resotocore/resotocore/model/typed_model.py
resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py

[resotocore][feat] Export available command line arguments

---

resotoshell/resotoshell/__main__.py
resotoshell/resotoshell/promptsession.py
resotoshell/test/test_promptsession.py
resotoshell/tox.ini

Add support for autocomplete in interactive shell session.
The values to complete are currently hard coded - will be replaced in a separate step, when the core provides this information.

[resotoshell][feat] Add autocomplete in interactive shell session

---

.gitignore
resotocore/.gitignore

Ignore .dccache files created by Snyk

[resoto][fix] Add .dccache to .gitignore

---

resotolib/resotolib/core/actions.py
resotolib/resotolib/core/events.py
resotolib/resotolib/core/tasks.py

Sends regular ping packets over established websocket connection.

[resotolib][fix] Send regular pings over websocket

---

resotoshell/resotoshell/promptsession.py
resotoshell/test/test_promptsession.py

The following cases are handled:
- support full-text terms
- end of term: suggest and/or/sort/limit/traversal
- after a property is defined: suggest operation: =, >, <...
- after an operation, add a hint for value
- support sort with property and sort order
- support limit with a hint
- support common traversals
- after a traversal, start again

[resotoshell][feat] Improve search completion

---

resotolib/resotolib/core/ca.py
resotoshell/resotoshell/__main__.py

Better startup error messages for resotoshell. Instead of throwing a stacktrace log a single line of helpful error message.

[resotoshell][feat] Better startup error messages

---

resotocore/resotocore/cli/command.py
resotolib/resotolib/utils.py

Filter files from the tarball that try to escape the current directory.

[resotocore][fix] Validate tarfile content

---

resotoshell/resotoshell/promptsession.py
resotoshell/test/test_promptsession.py

[resotoshell][feat] Add aggregate completer

---

resotocore/resotocore/cli/command.py
resotoshell/resotoshell/promptsession.py
resotoshell/test/test_promptsession.py

[resotoshell][fix] Fix sort suggestion and improve option information

---

resotoshell/resotoshell/__main__.py

Call the shutdown in resh when exiting.

[resotoshell][fix] shutdown the client thread

---

resotoshell/requirements.txt
resotoshell/resotoshell/__main__.py

Do not throw stack traces in the user face.

[resotoshell][fix] Graceful exception handling

---

plugins/aws/resoto_plugin_aws/accountcollector.py
plugins/aws/resoto_plugin_aws/resources.py
plugins/aws/resoto_plugin_aws/utils.py

Allow fetching and updating of S3 bucket tags

[plugins/aws][feat] Allow fetching and updating of S3 bucket tags

---

plugins/aws/resoto_plugin_aws/accountcollector.py
plugins/aws/resoto_plugin_aws/config.py
plugins/aws/resoto_plugin_aws/resources.py
plugins/aws/test/test_config.py

Fetch S3 bucket tag sets in parallel

[plugins/aws][feat] Fetch S3 bucket tag sets in parallel

---

plugins/aws/requirements.txt
plugins/digitalocean/requirements.txt

[plugins/aws][chore] Bump boto3 1.22.6 -> 1.22.11

---

docker-compose.yaml
resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/cleanup.py

Tell the user when cleanup is not being performed because it's turned off.

[resotoworker][fix] Better logging of cleanup

---

resotocore/tools/render_dot.py

Sanitise inputs to avoid snyk complains

[resoto][fix] Escape inputs to mute snyk

---

resotocore/resotocore/cli/cli.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/query/model.py
resotocore/resotocore/query/query_parser.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/db/arango_query_test.py
resotocore/tests/resotocore/query/query_parser_test.py
resotocore/tests/resotocore/web/api_test.py

[resotocore][feat] Add separate sort and limit commands

---

resotocore/resotocore/cli/command.py

[resotocore][fix] format also supports yaml which was not listed

---

.github/workflows/check_pr_plugin_aws.yml
.github/workflows/check_pr_plugin_cleanup_aws_alarms.yml
.github/workflows/check_pr_plugin_cleanup_aws_loadbalancers.yml
.github/workflows/check_pr_plugin_cleanup_aws_vpcs.yml
.github/workflows/check_pr_plugin_cleanup_expired.yml
.github/workflows/check_pr_plugin_cleanup_untagged.yml
.github/workflows/check_pr_plugin_cleanup_volumes.yml
.github/workflows/check_pr_plugin_digitalocean.yml
.github/workflows/check_pr_plugin_example_collector.yml
.github/workflows/check_pr_plugin_gcp.yml
.github/workflows/check_pr_plugin_github.yml
.github/workflows/check_pr_plugin_k8s.yml
.github/workflows/check_pr_plugin_onelogin.yml
.github/workflows/check_pr_plugin_onprem.yml
.github/workflows/check_pr_plugin_protector.yml
.github/workflows/check_pr_plugin_slack.yml
.github/workflows/check_pr_plugin_tagvalidator.yml
.github/workflows/check_pr_plugin_vsphere.yml
.github/workflows/check_pr_resotolib.yml
.github/workflows/check_pr_resotometrics.yml
.github/workflows/check_pr_resotoshell.yml
.github/workflows/check_pr_resotoworker.yml
.github/workflows/create_plugin_workflows.py
.github/workflows/resotocore_test_and_build.yml

[resoto][fix] Build packages on tag push

---

plugins/aws/resoto_plugin_aws/accountcollector.py

Add extra logging during EKS collection

[plugins/aws][fix] Add extra logging during EKS collection

---

README.md

[resoto][chore] Update README

---

resotocore/requirements-test.txt
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/web/api_client.py
resotoshell/requirements.txt

API spec defined an array, but it returned a json object.

[resotocore][fix] Export model in correct format

---

resotocore/resotocore/cli/command.py
resotocore/tests/resotocore/cli/command_test.py

Add sort properties to list output.

[resotocore][feat] Add sort properties to list output

---

dockerV2/prometheus.yml
resotocore/resotocore/metrics.py

Use `https` scheme and turn off TLS verification.

[docker][fix] Use TLS setup for prometheus

---

resotocore/.pylintrc
resotocore/resotocore/config/config_handler_service.py
resotocore/resotocore/model/model.py
resotocore/tests/resotocore/model/model_test.py

Config is sorted on update based on the model.

[resotocore][feat] Sort config based on model order

---

resotocore/resotocore/web/api.py

[resotocore][fix] Content disposition header for ca certificate

---

resotocore/tests/resotocore/action_handlers/merge_outer_edge_handler_test.py

[resotocore][fix] package need to be marked as module

---

.github/workflows/k8s-build.yml

Make the helm test more reliable by triggering collect before checking the results.

[resotocore][fix] Make helm test more reliable

---

resotocore/resotocore/action_handlers/merge_outer_edge_handler.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/config/config_handler_service.py
resotocore/resotocore/db/runningtaskdb.py
resotocore/resotocore/ids.py
resotocore/resotocore/message_bus.py
resotocore/resotocore/task/task_description.py
resotocore/resotocore/web/api.py
resotocore/resotocore/worker_task_queue.py
resotocore/tests/resotocore/action_handlers/merge_outer_edge_handler_test.py
resotocore/tests/resotocore/db/runningtaskdb_test.py
resotocore/tests/resotocore/message_bus_test.py
resotocore/tests/resotocore/worker_task_queue_test.py

Task id is now typed! one less possibility to mess up the wrong identifiers.

[resotocore][feat] Typed Ids: TaskId

---

resotocore/resotocore/config/core_config_handler.py
resotocore/resotocore/ids.py
resotocore/resotocore/web/api.py
resotocore/resotocore/worker_task_queue.py
resotocore/tests/resotocore/worker_task_queue_test.py

More types and fewer error possibilities! This time WorkerId.

[resotocore][feat] Typed WorkerId

---

resotocore/resotocore/dependencies.py

Allow complex property values as config overrides.

[resotocore][fix] Allow complex config override values

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/config/__init__.py
resotocore/resotocore/config/config_handler_service.py
resotocore/resotocore/core_config.py
resotocore/resotocore/db/configdb.py
resotocore/resotocore/db/entitydb.py
resotocore/resotocore/db/jobdb.py
resotocore/resotocore/db/modeldb.py
resotocore/resotocore/db/runningtaskdb.py
resotocore/resotocore/db/subscriberdb.py
resotocore/resotocore/db/templatedb.py
resotocore/resotocore/ids.py
resotocore/resotocore/task/__init__.py
resotocore/resotocore/task/task_description.py
resotocore/resotocore/task/task_handler.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/analytics/recurrent_events_test.py
resotocore/tests/resotocore/config/config_handler_service_test.py
resotocore/tests/resotocore/db/configdb_test.py
resotocore/tests/resotocore/db/entitydb.py
resotocore/tests/resotocore/db/jobdb_test.py
resotocore/tests/resotocore/db/modeldb_test.py
resotocore/tests/resotocore/db/runningtaskdb_test.py
resotocore/tests/resotocore/db/subscriberdb_test.py
resotocore/tests/resotocore/db/templatedb_test.py
resotocore/tests/resotocore/task/job_handler_test.py
resotocore/tests/resotocore/task/subscribers_test.py
resotocore/tests/resotocore/task/task_description_test.py
resotocore/tests/resotocore/task/task_handler_test.py

More types! This time ConfigId and some of the database wrappers

[resotocore][feat] Add typed ConfigId

---

resotolib/resotolib/utils.py

Extend update check to distinguish between stable and pre-releases

[resotolib] [feat] Extend update check to distinguish between stable and pre-releases

---

setup_venv.sh

Make git repo check in setup_venv script work for https checkouts and forks.

[resoto][fix] Update git repo check in setup_venv script

---

plugins/k8s/resoto_plugin_k8s/resources.py
resotolib/resotolib/json_bender.py
resotolib/resotolib/units.py
resotolib/test/json_bender_test.py
resotolib/tox.ini

Conversion to specific units was not working as expected.
Fixed and added a test.

[resotolib][fix] Units are computed correctly

---

resotocore/resotocore/db/arango_query.py
resotocore/resotocore/model/model.py
resotocore/resotocore/model/model_handler.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/model/__init__.py
resotocore/tests/resotocore/model/model_test.py

[resotocore][feat] Uml model shows dependant complex types

---

plugins/k8s/resoto_plugin_k8s/resources.py
plugins/k8s/tools/successors.py

Define successors for k8s resources.

[k8s][feat] Define successors

---

resotolib/resotolib/config.py
resotolib/resotolib/graph/__init__.py
resotoworker/requirements.txt
resotoworker/resotoworker/resotocore.py

[resotoworker][fix] Retry sending of graph data

---

resotocore/resotocore/cli/__init__.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/db/arango_query.py
resotocore/resotocore/model/db_updater.py
resotocore/resotocore/model/graph_access.py
resotocore/resotocore/model/model.py
resotocore/resotocore/query/model.py
resotocore/resotocore/util.py
resotocore/tests/resotocore/action_handlers/merge_outer_edge_handler_test.py
resotocore/tests/resotocore/cli/cli_test.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/db/graphdb_test.py
resotocore/tests/resotocore/model/model_test.py
resotocore/tests/resotocore/util_test.py
resotocore/tests/resotocore/web/api_test.py
resotoshell/resotoshell/promptsession.py
resotoshell/test/test_promptsession.py

[resotocore][feat] Improve nested path handling

---

plugins/k8s/resoto_plugin_k8s/base.py
plugins/k8s/resoto_plugin_k8s/resources.py
resotolib/resotolib/json_bender.py
resotolib/test/json_bender_test.py

The status condition array is not ordered by k8s. 
Add ordering by lastTransitionTime to all status conditions.

[k8s][feat] Order status conditions by time.

---

plugins/k8s/resoto_plugin_k8s/base.py
plugins/k8s/resoto_plugin_k8s/collector.py
plugins/k8s/resoto_plugin_k8s/resources.py
plugins/k8s/test/collector_test.py
plugins/k8s/test/fixtures.py
resotoworker/resotoworker/tag.py

[k8s][fix] Fix api client handling

---

.github/workflows/check_pr_resotoeventlog.yml

[resotoeventlog][fix] Update PyPI secret name

---

plugins/k8s/resoto_plugin_k8s/base.py
plugins/k8s/test/config_test.py

[k8s][fix] Handle optional properties correctly

---

resotometrics/resotometrics/__main__.py

[resotometrics][fix] Fix metrics type

---

resotoworker/resotoworker/collect.py

Wrap collector plugins in try/except block

[resotoworker][fix] Wrap collector plugins in try/except block

---

plugins/k8s/README.md

[k8s][chore] Update Readme.

---

.github/workflows/docker-build.yml

Only build amd as long as we do not know better.

[docker][fix] Only build amd images

---

tools/release_notes.py

[resoto][fix] Fix release notes generator

---

resotometrics/resotometrics/config.py
resotometrics/test/test_args.py

[resotometrics][fix] Fix default config loading

---

resotocore/resotocore/model/db_updater.py

[fix][resotocore] use proper datetime

---

plugins/digitalocean_k8s/resoto_plugin_digitalocean_k8s/__init__.py
plugins/digitalocean_k8s/test/test_collector.py
resotolib/resotolib/baseplugin.py
resotoworker/resotoworker/collect.py

Added a timeout for post_collect collectors

[resotoworke][fix] Add a timeout to post_collect collectors

---

.github/workflows/resotobundle_publish.yml

[resoto][fix] Fix the broken resotobundle job

---

resotocore/resotocore/cli/cli.py

[resotocore][fix] Fix typo

---

.github/workflows/model_check.yml
resotolib/resotolib/core/model_check.py
resotolib/test/core/model_check_test.py

[resotolib][feat] Check model when it changes.

---

resotocore/resotocore/web/directives.py

Set CORS headers on all methods
@aquamatthias this is a very naive approach. Please review if there's a neater way to do this.

[resotocore][fix] Set CORS headers on all methods

---

.gitignore
plugins/aws/resoto_plugin_aws/config.py
plugins/aws/test/test_config.py
plugins/cleanup_untagged/resoto_plugin_cleanup_untagged/__init__.py
plugins/digitalocean/resoto_plugin_digitalocean/client.py
plugins/digitalocean/resoto_plugin_digitalocean/collector.py
plugins/gcp/resoto_plugin_gcp/config.py
plugins/gcp/resoto_plugin_gcp/utils.py
plugins/gcp/test/test_config.py
plugins/k8s/resoto_plugin_k8s/base.py
plugins/k8s/test/config_test.py
plugins/tagvalidator/resoto_plugin_tagvalidator/__init__.py
resotocore/resotocore/model/transform_kind_convert.py
resotolib/resotolib/baseresources.py
resotolib/resotolib/core/model_export.py
resotolib/resotolib/durations.py
resotolib/resotolib/event.py
resotolib/resotolib/graph/__init__.py
resotolib/resotolib/lock.py
resotolib/resotolib/proc.py
resotolib/resotolib/utils.py
resotolib/test/durations_test.py
resotolib/test/test_utils.py
resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/config.py

Try to move stuff out of utils to clean it up.
- use typing.Json everywhere
- use durations for parsing and string representation
- Fixes #XXXX

[resotolib][chore] Cleanup utils

---

plugins/slack/resoto_plugin_slack/__init__.py
resotolib/resotolib/baseresources.py
resotolib/resotolib/core/model_export.py
resotolib/resotolib/utils.py

[resoto][chore] utc formatted iso-8601 timestamps

---

plugins/aws/Makefile
plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/accountcollector.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/utils.py
plugins/aws/setup.cfg
plugins/aws/test/resource/__init__.py
plugins/aws/test/test_config.py
plugins/aws/test/test_utils.py
plugins/aws/tox.ini

[aws][chore] Add mypy support

---

plugins/aws/resoto_plugin_aws/accountcollector.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/resources.py
plugins/digitalocean/resoto_plugin_digitalocean/collector.py
plugins/digitalocean/resoto_plugin_digitalocean/resources.py
plugins/digitalocean/test/test_collector.py
plugins/example_collector/resoto_plugin_example_collector/__init__.py
plugins/gcp/resoto_plugin_gcp/collector.py
plugins/gcp/resoto_plugin_gcp/resources.py
plugins/k8s/resoto_plugin_k8s/resources.py
plugins/onprem/resoto_plugin_onprem/resources.py
plugins/onprem/resoto_plugin_onprem/ssh.py
plugins/vsphere/resoto_plugin_vsphere/__init__.py
plugins/vsphere/resoto_plugin_vsphere/resources.py
resotolib/resotolib/baseresources.py

[resoto/plugins][chore] Fix the _instance_setter  

---

plugins/aws/resoto_plugin_aws/accountcollector.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/resources.py
plugins/digitalocean/resoto_plugin_digitalocean/collector.py
plugins/digitalocean/resoto_plugin_digitalocean/resources.py
plugins/digitalocean/test/test_collector.py
plugins/example_collector/resoto_plugin_example_collector/__init__.py
plugins/gcp/resoto_plugin_gcp/collector.py
plugins/gcp/resoto_plugin_gcp/resources.py
plugins/k8s/resoto_plugin_k8s/resources.py
plugins/random/resoto_plugin_random/__init__.py
plugins/random/resoto_plugin_random/resources.py
resotolib/resotolib/baseresources.py
resotolib/resotolib/graph/__init__.py

volume_status attribute is easier to work with now.

[plugins][chore] Fix the _volume_status_setter

---

plugins/aws/resoto_plugin_aws/accountcollector.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/resources.py
plugins/k8s/resoto_plugin_k8s/resources.py
resotolib/resotolib/core/model_export.py
resotolib/resotolib/json_bender.py
resotolib/test/core/model_export_test.py
resotolib/test/json_bender_test.py

[k8s][fix] Use proper enumeration type.

---

resotolib/resotolib/graph/__init__.py

[resotolib][fix] Use str as enum value

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/config.py
plugins/aws/test/aws_client_test.py
plugins/aws/test/collector_test.py
plugins/aws/test/config_test.py
plugins/aws/test/resources/__init__.py
resotolib/resotolib/core/model_export.py
setup_venv.sh

[fix][resotolib] Fix enum model export

---

docker/bootstrap
dockerV2/bootstrap

Deactivate recursive chmod for ~resoto/ (fixes #978)

[docker][fix] deactivate recursive chmod for ~resoto/ (fixes #978)

---

plugins/example_collector/resoto_plugin_example_collector/__init__.py

Remove post init from example collector

[plugins/example][fix] Remove post init from example collector

---

plugins/digitalocean/resoto_plugin_digitalocean/collector.py
plugins/digitalocean/resoto_plugin_digitalocean/resources.py
plugins/digitalocean/test/test_collector.py

[plugins/digitalocean][feat] Collect volume pricing information

---

plugins/digitalocean/resoto_plugin_digitalocean/collector.py
plugins/digitalocean/resoto_plugin_digitalocean/resources.py
plugins/digitalocean/resoto_plugin_digitalocean/utils.py
plugins/digitalocean/test/test_collector.py

[plugins/digitalocean][feat] Collect droplet pricing information

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/iam.py
plugins/aws/resoto_plugin_aws/resource/route53.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/route53/list-hosted-zones.json
plugins/aws/test/resources/files/route53/list-resource-record-sets__test_zone.json
plugins/aws/test/resources/route53_test.py
plugins/aws/tools/model_gen.py

[feat][aws] Add Route53 Service

---

resotolib/resotolib/core/model_export.py

Fixed the init arguments name in export.

[resotolib][fix] Fix tagging and attrs init

---

resotolib/resotolib/core/model_export.py

Fixed the object deserialization using cattrs

[resotolib][fix] Fix the resource cleanup process

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/s3/list-buckets.json
plugins/aws/test/resources/s3_test.py
plugins/aws/tools/model_gen.py

[feat][aws] Add S3 Service

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/eks.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/eks_test.py
plugins/aws/test/resources/files/eks/describe-cluster__cluster1.json
plugins/aws/test/resources/files/eks/describe-nodegroup__cluster1_main.json
plugins/aws/test/resources/files/eks/list-clusters.json
plugins/aws/test/resources/files/eks/list-nodegroups__cluster1.json
plugins/aws/tools/model_gen.py

[aws][feat] Add eks Cluster and Nodegroups

---

resotocore/resotocore/web/content_renderer.py

[resotocore][fix] DOT renderer should allow dashes

---

.github/workflows/docker-build.yml

[resoto][feat] build arm64 docker images

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/accountcollector.py
plugins/aws/resoto_plugin_aws/config.py
plugins/aws/resoto_plugin_aws/resources.py
plugins/aws/resoto_plugin_aws/utils.py

[plugins/aws][feat] Add support for AWS profiles

---

plugins/aws/resoto_plugin_aws/accountcollector.py

[plugins/aws][fix] fix missing kwargs

---

resotolib/resotolib/baseresources.py
resotolib/resotolib/core/model_export.py
resotolib/resotolib/core/tasks.py

Changed the serialization code to get the ancestors into the object.
- Fixes #XXXX

[resotolib][fix] Fix broken tag updates

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/resource/pricing.py
plugins/aws/resoto_plugin_aws/resource/service_quotas.py
plugins/aws/test/__init__.py
plugins/aws/test/collector_test.py
plugins/aws/test/graphbuilder_test.py
plugins/aws/test/resources/__init__.py
plugins/aws/test/resources/ec2_test.py
plugins/aws/test/resources/files/ec2/describe-instance-types.json
plugins/aws/test/resources/files/pricing/get-products__TERM_MATCH_volumeType_General_Purpose_TERM_MATCH_volumeApiName_gp2_TERM_MATCH_location_US_East__N__Virginia__1_AmazonEC2.json
plugins/aws/test/resources/files/service_quotas/list-service-quotas__ebs.json
plugins/aws/test/resources/files/service_quotas/list-service-quotas__ec2.json
plugins/aws/test/resources/files/service_quotas/list-service-quotas__elasticloadbalancing.json
plugins/aws/test/resources/files/service_quotas/list-service-quotas__iam.json
plugins/aws/test/resources/files/service_quotas/list-service-quotas__vpc.json
plugins/aws/test/resources/pricing_test.py
plugins/aws/test/resources/service_quotas_test.py
plugins/aws/tools/model_gen.py
plugins/aws/tox.ini
resotolib/resotolib/json_bender.py
resotolib/test/json_bender_test.py

[aws][feat] Add quota limits

---

plugins/digitalocean/resoto_plugin_digitalocean/__init__.py
plugins/digitalocean/resoto_plugin_digitalocean/client.py
plugins/digitalocean/resoto_plugin_digitalocean/resources.py
resotolib/resotolib/baseplugin.py
resotolib/resotolib/baseresources.py
resotolib/resotolib/utils.py
resotolib/test/test_utils.py
resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/tag.py

Updated tagging code to do most of the work on the plugin side instead of the base resource
- Fixes #XXXX

[resotolib, resotoworker, plugins/digitalocean][chore] Refactor tag operations

---

plugins/aws/resoto_plugin_aws/config.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/cloudwatch.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/resource/rds.py
plugins/aws/test/resources/__init__.py
plugins/aws/test/resources/cloudwatch_test.py
plugins/aws/test/resources/files/cloudwatch/get-metric-data__2020_03_01_00_00_00_00_00_volumereadops_aws_ebs_volumeid_vol_123_AWS_EBS_VolumeReadOps_VolumeId_vol_123_3600_Sum_Count_True_volumewriteops_aws_ebs_volumeid_vol_123_AWS_EBS_VolumeWriteOps_VolumeId_vol_123_3600_Sum_Count.json
plugins/aws/tools/model_gen.py
resotolib/resotolib/config.py
resotolib/resotolib/core/model_export.py
resotolib/resotolib/json.py
resotolib/test/core/model_export_test.py

[aws][feat] Integrate cloudwatch and use it for atime and mtime

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/config.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/test/__init__.py
plugins/aws/test/aws_client_test.py
plugins/aws/test/resources/__init__.py

[aws][feat] Use stored account profile to access AWS

---

resotolib/resotolib/config.py
resotolib/test/test_config.py
resotoworker/resotoworker/collect.py

[resotolib][fix] Make config cache-friendly

---

plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/route53.py
plugins/aws/resoto_plugin_aws/resources.py
plugins/digitalocean/resoto_plugin_digitalocean/resources.py
plugins/gcp/resoto_plugin_gcp/resources.py
plugins/k8s/resoto_plugin_k8s/base.py
plugins/k8s/resoto_plugin_k8s/resources.py
plugins/k8s/tools/successors.py
plugins/slack/resoto_plugin_slack/resources.py
resotolib/resotolib/baseresources.py
resotolib/resotolib/core/model_export.py
resotolib/test/core/model_export_test.py

[resotolib][feat] Allow to define predecessor and successor

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/lambda_.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/lambda/list-functions.json
plugins/aws/test/resources/lambda_test.py
plugins/aws/tools/model_gen.py
resotolib/resotolib/baseresources.py

Add support for lambda functions for the new style AWS collector the same way as suggested for the existing collector in #992. Added example and roundtrip tests.

[aws][feat] Add lambda functions

---

plugins/aws/resoto_plugin_aws/resource/iam.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/iam/list-instance-profiles.json
plugins/aws/test/resources/iam_test.py
plugins/aws/tools/model_gen.py

[aws][feat] Add Iam Instance Profile

---

plugins/aws/resoto_plugin_aws/accountcollector.py
plugins/aws/resoto_plugin_aws/resources.py
resotolib/resotolib/baseresources.py

Add support for Lambda Functions

[plugin/aws][feat] Add support for Lambda Functions

---

plugins/aws/resoto_plugin_aws/accountcollector.py
plugins/aws/resoto_plugin_aws/resources.py

Update lambda resource insert order and dependencies.
Also fixes an edge direction for EKS clusters.

[plugins/aws][fix] Update resource insert order and dependencies

---

.github/CODEOWNERS

[resoto][chore] Add anjafr as code owner

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/resource/autoscaling.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/cloudformation.py
plugins/aws/resoto_plugin_aws/resource/cloudwatch.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/resource/eks.py
plugins/aws/resoto_plugin_aws/resource/elb.py
plugins/aws/resoto_plugin_aws/resource/elbv2.py
plugins/aws/resoto_plugin_aws/resource/iam.py
plugins/aws/resoto_plugin_aws/resource/lambda_.py
plugins/aws/resoto_plugin_aws/resource/rds.py
plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/resoto_plugin_aws/resource/service_quotas.py
plugins/aws/test/resources/autoscaling_test.py
plugins/aws/test/resources/cloudformation_test.py
plugins/aws/test/resources/cloudwatch_test.py
plugins/aws/test/resources/ec2_test.py
plugins/aws/test/resources/eks_test.py
plugins/aws/test/resources/elb_test.py
plugins/aws/test/resources/elbv2_test.py
plugins/aws/test/resources/iam_test.py
plugins/aws/test/resources/lambda_test.py
plugins/aws/test/resources/rds_test.py
plugins/aws/test/resources/s3_test.py
plugins/aws/test/resources/service_quotas_test.py

[plugins/aws][feat] Tagging support

---

plugins/aws/resoto_plugin_aws/resource/autoscaling.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/test/resources/autoscaling_test.py

[plugins/aws][feat] Support deletion in ASG

---

plugins/aws/resoto_plugin_aws/resource/cloudformation.py
plugins/aws/test/resources/cloudformation_test.py

[plugins/aws][feat] Support CloudFormatonStack deletion

---

plugins/aws/resoto_plugin_aws/resource/cloudformation.py
plugins/aws/test/resources/cloudformation_test.py

[plugins/aws][feat] Support deletion of cf stack sets

---

plugins/aws/resoto_plugin_aws/resource/cloudwatch.py
plugins/aws/test/resources/cloudwatch_test.py

[plugins/aws][feat] Support deletion of Cloudwatch alarms

---

plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Add ec2 volumes deletion support

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Support snapshot deletion

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Support ec2 keypair deletion

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Support EC2 instance deletion

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Support network acl deletion

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Support Elastic Ip deletion

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Support Vpc deletion

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Support ec2 network interface deletion

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Support vpc peering connection deletion

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Support subnet deletion

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Support security groups deletion

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Delete ec2 nat gateways support

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Support internet gateway deletion

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py

[plugins/aws][feat] Support route table deletion

---

plugins/aws/resoto_plugin_aws/resource/ec2.py

[plugins/aws][fix] Move pre-deletion to its own method

---

plugins/aws/resoto_plugin_aws/resource/eks.py
plugins/aws/test/resources/eks_test.py

[plugins/aws][feat] Support deletion of the EKS resources

---

plugins/aws/resoto_plugin_aws/resource/elbv2.py
plugins/aws/test/resources/elbv2_test.py

[plugins/aws][feat] Support ELB v2 deletion

---

plugins/aws/resoto_plugin_aws/resource/elb.py
plugins/aws/test/resources/elb_test.py

[plugins/aws][feat] Support ELB deletion

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/elasticbeanstalk.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/elasticbeanstalk_test.py
plugins/aws/test/resources/files/elasticbeanstalk/describe-applications.json
plugins/aws/tools/model_gen.py

Part 1: Collecting Applications (collecting, tagging, deleting)
Open: Collecting application environments and their resources, adding tags to application

[plugins/aws][feat] Add support for Elastic Beanstalk Applications

---

plugins/aws/resoto_plugin_aws/resource/iam.py
plugins/aws/test/resources/iam_test.py

[plugins/aws][feat] Support IAM resources deleteon

---

plugins/aws/resoto_plugin_aws/resource/lambda_.py
plugins/aws/test/resources/lambda_test.py

[plugins/aws][feat] Support lambda deletion

---

plugins/aws/resoto_plugin_aws/resource/rds.py
plugins/aws/test/resources/rds_test.py

[plugins/aws][feat] Support RDS deletion

---

plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/test/resources/s3_test.py

[plugins/aws][feat] Support s3 bucket deletion

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
resotolib/resotolib/baseplugin.py
resotolib/resotolib/baseresources.py
resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/cleanup.py

[plugins/aws][feat] Enable new resources pre_cleanup/cleanup

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/kinesis.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/kinesis/describe-stream__resoto_stream.json
plugins/aws/test/resources/files/kinesis/list-streams.json
plugins/aws/test/resources/files/kinesis/list-tags-for-stream__resoto_stream.json
plugins/aws/test/resources/kinesis_test.py
plugins/aws/tools/model_gen.py

[plugins/aws][feat] Add support for kinesis streams

---

plugins/aws/resoto_plugin_aws/resource/elasticbeanstalk.py

[plugins/aws][fix] Fix direction of edges

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/sqs.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/sqs/get-queue-attributes__All_queue_amazonaws_com_882347060974_SomeName.json
plugins/aws/test/resources/files/sqs/list-queue-tags__queue_amazonaws_com_882347060974_SomeName.json
plugins/aws/test/resources/files/sqs/list-queues.json
plugins/aws/test/resources/sqs_test.py
plugins/aws/tools/model_gen.py

[plugins/aws][feat] Add support for SQS

---

plugins/aws/resoto_plugin_aws/resource/elasticbeanstalk.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/elasticbeanstalk/describe-environment-resources__SomeId.json

[plugins/aws][feat] Add edge from Beanstalk resource to SQS Queue

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/redshift.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/redshift/describe-clusters.json
plugins/aws/test/resources/redshift_test.py
plugins/aws/tools/model_gen.py

[plugins/aws][feat] Add redshift collection support

---

plugins/aws/resoto_plugin_aws/__init__.py

No new collector class should be imported within the current setup.

[aws][fix] Do not use new collector classes

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/elasticache.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/__init__.py
plugins/aws/test/resources/elasticache_test.py
plugins/aws/test/resources/files/elasticache/describe-cache-clusters.json
plugins/aws/test/resources/files/elasticache/describe-replication-groups.json
plugins/aws/test/resources/files/elasticache/list-tags-for-resource__foo_cluster.json
plugins/aws/test/resources/files/elasticache/list-tags-for-resource__foo_rg.json
plugins/aws/tools/model_gen.py

[plugins/aws][feat] Support Elasticache collection.

---

.github/workflows/docker-build.yml
tools/release_notes.py

Also updates generated release notes Markdown file path to reflect new directory structure.

[ci][chore] Handle reversed component/group in release notes generator

---

resotolib/requirements.txt

[resotolib][fix] Use the snapshot version of the cattrs

---

plugins/aws/resoto_plugin_aws/resource/redshift.py

- Add edge between Redshift Cluster and KMS Key
- Add `reference_kinds`
- [x Lint and test with `tox`

[plugins/aws][feat] Add edge between Redshift Cluster and KMS Key

---

resotoshell/resotoshell/__main__.py

[resotoshell][fix] Wait for resotocore to be online when starting

---

plugins/aws/resoto_plugin_aws/resource/elasticbeanstalk.py

Consistent use of service prefixes
- Fixes #XXXX

[plugins/aws][fix] Consistent use of service prefixes

---

plugins/aws/resoto_plugin_aws/resource/ec2.py

Add edge between EC2 Snapshots, Volumes and KMS Keys

[plugins/aws][feat] Add edge between EC2 Snapshots, Volumes and KMS Keys

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/athena.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/athena_test.py
plugins/aws/test/resources/files/athena/get-data-catalog__resoto_catalog.json
plugins/aws/test/resources/files/athena/get-work-group__resoto_workgroup.json
plugins/aws/test/resources/files/athena/list-data-catalogs.json
plugins/aws/test/resources/files/athena/list-tags-for-resource__arn_aws_athena_eu_central_1_test_datacatalog_resoto_catalog.json
plugins/aws/test/resources/files/athena/list-tags-for-resource__arn_aws_athena_eu_central_1_test_workgroup_resoto_workgroup.json
plugins/aws/test/resources/files/athena/list-work-groups.json
plugins/aws/tools/model_gen.py
resotolib/resotolib/baseresources.py

[plugins/aws][feat] Collect Athena resources

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/dynamodb.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/dynamodb_test.py
plugins/aws/test/resources/files/dynamodb/describe-global-table__SomeGlobalName.json
plugins/aws/test/resources/files/dynamodb/describe-table__test1.json
plugins/aws/test/resources/files/dynamodb/list-global-tables.json
plugins/aws/test/resources/files/dynamodb/list-tables.json
plugins/aws/test/resources/files/dynamodb/list-tags-of-resource__arn_aws_dynamodb_us_west_2_test_table_test1.json
plugins/aws/tools/model_gen.py

[plugins/aws][feat] Add support for DynamoDB

---

plugins/aws/resoto_plugin_aws/resource/elasticache.py

Add edge between ElastiCache Replication Group and KMS Key

[plugins/aws][feat] Add edge between ElastiCache Replication Group and KMS Key

---

plugins/aws/resoto_plugin_aws/resource/lambda_.py

Add edge between Lambda Function and KMS Key

[plugins/aws][feat] Add edge between Lambda Function and KMS Key

---

plugins/aws/resoto_plugin_aws/resource/elasticbeanstalk.py

Add reference_kinds to Elasticbeanstalk Environment

[plugins/aws][fix] Add reference_kinds to Elasticbeanstalk Environment

---

plugins/aws/resoto_plugin_aws/resource/route53.py

Fix open left over from genesis implementation.

[aws][fix] Set correct DNS Record values

---

plugins/aws/resoto_plugin_aws/resource/athena.py
plugins/aws/resoto_plugin_aws/resource/redshift.py
plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/test/resources/athena_test.py
plugins/aws/test/resources/redshift_test.py
plugins/aws/test/resources/s3_test.py

[plugins/aws][feat] Collect ARN for s3 and others

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/test/__init__.py
plugins/aws/test/collector_test.py
plugins/aws/test/graphbuilder_test.py
plugins/aws/test/resources/__init__.py
plugins/aws/test/resources/cloudwatch_test.py
plugins/aws/test/resources/pricing_test.py

In case of UnauthorizedException, the collector should stop scraping a region.

[aws][fix] Give up collecting a region in case of UnauthorizedException

---

plugins/aws/resoto_plugin_aws/resource/service_quotas.py

[plugins/aws][fix] Use sequential collection of service quotas

---

plugins/aws/resoto_plugin_aws/resource/cloudwatch.py
plugins/aws/test/resources/cloudwatch_test.py
plugins/aws/test/resources/files/cloudwatch/list-tags-for-resource__arn_aws_cloudwatch_us_west_2_test_alarm_awsec2_CPU_Utilization.json

Collect tags for Cloudwatch Alarms

[plugins/aws][feat] Collect tags for Cloudwatch Alarms

---

plugins/aws/resoto_plugin_aws/resource/lambda_.py
plugins/aws/test/resources/files/lambda/list-tags__arn_aws_lambda_us_east_1_test_function_dcos_versions_lambda_dev_commit.json
plugins/aws/test/resources/lambda_test.py

Collect tags for Lambda Functions

[plugins/aws][feat] Collect tags for Lambda Functions

---

plugins/aws/resoto_plugin_aws/resource/rds.py
plugins/aws/test/resources/files/rds/list-tags-for-resource__arn_aws_rds_us_west_2_test_db_dashboard.json
plugins/aws/test/resources/rds_test.py

Collect tags for RDS Instances

[plugins/aws][feat] Collect tags for RDS Instances

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/ec2.py

Do not add the same VolumeType multiple times
Improve logging.

[aws][fix] Do not add the same VolumeType multiple times

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/resources/ec2_test.py
plugins/aws/test/resources/files/ec2/describe-network-interfaces.json

[aws][fix] Fix property names for network interfaces

---

plugins/aws/resoto_plugin_aws/resource/elbv2.py

Reverse direction of the delete edge.
- Towards #1115 

[aws][fix] alb -delete-> target_group

---

plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/test/resources/files/s3/get-bucket-tagging__bucket_1.json
plugins/aws/test/resources/s3_test.py

[plugins/aws][feat] Collect tags for S3 Buckets

---

plugins/aws/resoto_plugin_aws/resource/s3.py

resource tag collection now handles "NoSuchTagSet" exceptions as well

[aws][fix] Handle S3 "NoSuchTagSet" Exception in all cases

---

resotolib/resotolib/core/model_export.py

[resotolib][fix] Resolve attrs types in model exporter

---

resotocore/requirements-test.txt
resotoshell/requirements.txt

[resotolib][chore] Update resotoclient to 0.1.13

---

plugins/aws/resoto_plugin_aws/__init__.py

[plugins/aws][fix] Use the correct region in the client

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/resource/elbv2.py

Revert ALB delete edge and fix some client code

[plugins/aws][fix] Revert ALB delete edge and fix some client code

---

plugins/aws/resoto_plugin_aws/aws_client.py

[plugins/aws][fix] Enable legacy retry mode

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/aws_client.py
resotolib/resotolib/types.py
resotolib/resotolib/utils.py

[plugins/aws][chore] Log collect call runtime

---

plugins/aws/resoto_plugin_aws/aws_client.py

This reverts commit d5bc084d590ec757e3836f9f361eb0ec7a382e08.
- Fixes #XXXX

Revert "[plugins/aws][fix] enable legacy retry mode (#1133)"

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/service_quotas.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/service_quotas/list-service-quotas__iam.json
plugins/aws/test/resources/service_quotas_test.py

[fix][aws] Get service quotas from region

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/aws_client_test.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/ec2_test.py
plugins/aws/test/resources/files/ec2/describe-hosts.json
plugins/aws/test/resources/files/ec2/describe-instances.json
plugins/aws/tools/model_gen.py

[plugins/aws][feat] Collect Dedicated Hosts (EC2)

---

plugins/dockerhub/README.md
plugins/dockerhub/requirements.txt
plugins/dockerhub/resoto_plugin_dockerhub/__init__.py
plugins/dockerhub/resoto_plugin_dockerhub/config.py
plugins/dockerhub/resoto_plugin_dockerhub/resources.py
plugins/dockerhub/setup.cfg
plugins/dockerhub/setup.py
plugins/dockerhub/test/test_config.py
plugins/dockerhub/tox.ini

[plugins/dockerhub][feat] Docker Hub MVP collector

---

.github/workflows/check_pr_plugin_dockerhub.yml
plugins/dockerhub/resoto_plugin_dockerhub/config.py
plugins/dockerhub/setup.py
setup_venv.sh

[plugins/dockerhub][fix] Fix copy error

---

resotocore/Makefile
resotocore/resotocore/cli/cli.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/cli/model.py

[resotocore][feat] Show commands in sections

---

resotometrics/resotometrics/__main__.py

[resotometrics][fix] Fix counter metrics

---

plugins/dockerhub/resoto_plugin_dockerhub/__init__.py
plugins/dockerhub/resoto_plugin_dockerhub/resources.py

[plugins/dockerhub][feat] add pagination support

---

plugins/aws/resoto_plugin_aws/resource/ec2.py

[aws][fix] Fix wrong property name

---

.github/workflows/resotocore_test_and_build.yml
resotocore/requirements-jupyterlite.txt

[resotocore][fix[ Fix the broken resotocore workflow

---

Dockerfile
Dockerfile.resotobase

Set default COLORTERM if not set by client

[docker][fix] Set default COLORTERM if not set by client

---

Dockerfile
Dockerfile.resotobase

[resotocore][feat] Build jupyterlite in docker

---

plugins/digitalocean/resoto_plugin_digitalocean/collector.py

Signed-off-by: kushthedude <kushthedude@gmail.com>
- Fixes https://github.com/someengineering/resoto/issues/889

fix(digitalocean): remove redundant connection args

---

plugins/aws/resoto_plugin_aws/resource/apigateway.py

[plugins/aws][fix] Fix ApiGateway collection

---

docker-compose.yaml

Define `container_name` for each service.

[docker][fix] Define container names in Compose YAML

---

plugins/aws/resoto_plugin_aws/resource/base.py

[aws][fix] Improve error messages on exception

---

dockerV2/resh-shim
resotoshell/resotoshell/__main__.py

Add argument to wait for resotocore to be online

[resotoshell][fix] Add argument to wait for resotocore to be online

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/service_quotas.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/__init__.py
plugins/aws/test/resources/service_quotas_test.py
resotolib/resotolib/core/model_check.py

Removed the IAM service quota class

[plugins/aws][fix] Remove the ephemeral iam service quota class

---

plugins/aws/resoto_plugin_aws/resource/apigateway.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/apigateway_test.py
plugins/aws/test/resources/files/apigateway/get-domain-names.json
plugins/aws/tools/model_gen.py

new resource:
- `aws_api_gateway_domain_name`

[plugins/aws][feat] Collect Custom Domain Names (ApiGateway)

---

plugins/aws_k8s/resoto_plugin_aws_k8s/__init__.py
plugins/digitalocean_k8s/resoto_plugin_digitalocean_k8s/__init__.py
resotolib/resotolib/baseplugin.py
resotoworker/resotoworker/pluginloader.py

Start the post-collection plugins automatically when the pre-requirements are met

[resotoworker][feat] Start the post-collection plugins automatically

---

Dockerfile
Dockerfile.resotobase

[resotocore][fix] Use a separate venv for jupyterlite build

---

plugins/aws/resoto_plugin_aws/resource/sqs.py

[aws][fix] Map ctime and mtime for aws_sqs_queue correctly

---

plugins/aws/resoto_plugin_aws/resource/apigateway.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/dockerhub/resoto_plugin_dockerhub/resources.py
resotolib/resotolib/json.py

- ApiGateway uses wrong default values
- DockerHubRepository declares status as int which is already defined as string

[aws][fix] Fix wrong default values for ApiGateway

---

plugins/aws/resoto_plugin_aws/resource/athena.py

Excluded the default data catalog from collection

[plugins/aws][fix] Do not collect the default AwsDataCatalog

---

plugins/aws/resoto_plugin_aws/resource/eks.py
plugins/aws/test/resources/eks_test.py

API requires a dict not a list to update tags for EKS.

[aws][fix] Fix EKS tagging

---

docker-compose.yaml

Add RESOTOCORE_ANALYTICS_OPT_OUT to `docker-compose.yml`
- Fixes #XXXX

[resotocore][chore] Add RESOTOCORE_ANALYTICS_OPT_OUT to docker-compose.yml

---

plugins/aws/resoto_plugin_aws/resource/apigateway.py
plugins/aws/resoto_plugin_aws/resource/ecs.py
plugins/aws/resoto_plugin_aws/resource/eks.py
plugins/aws/resoto_plugin_aws/resource/redshift.py

[aws][fix] Correction of edges to IAM Roles

---

.github/workflows/docker-build.yml
Dockerfile.resotobase

[docker][fix] fix broken Docker build

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/sns.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/sns/get-platform-application-attributes__arn_aws_sns_us_west_2_123456789012_app_ADM_MyApplication.json
plugins/aws/test/resources/files/sns/get-subscription-attributes__arn_aws_sns_us_west_2_123456789012_my_topic_acc6_7be.json
plugins/aws/test/resources/files/sns/get-topic-attributes__arn_aws_sns_us_west_2_123456789012_my_topic.json
plugins/aws/test/resources/files/sns/list-endpoints-by-platform-application__arn_aws_sns_us_west_2_123456789012_app_ADM_MyApplication.json
plugins/aws/test/resources/files/sns/list-platform-applications.json
plugins/aws/test/resources/files/sns/list-subscriptions.json
plugins/aws/test/resources/files/sns/list-tags-for-resource__arn_aws_sns_us_west_2_123456789012_my_topic.json
plugins/aws/test/resources/files/sns/list-topics.json
plugins/aws/test/resources/sns_test.py
plugins/aws/tools/model_gen.py

new resources:
- `aws_sns_topic`
- `aws_sns_subscription`
- `aws_sns_platform_application`
- `aws_sns_endpoint`
- Fixes #1172 

[plugins/aws][feat] Add Support for SNS

---

plugins/digitalocean/resoto_plugin_digitalocean/collector.py
plugins/digitalocean/test/fixtures/snapshots.py

[plugins/digitalocean][fix] Fix the snapshots regions collection

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/cli/search_of_the_day.py
resotocore/resotocore/cli/tip_of_the_day.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/web/api_test.py

Added the tip of the day feature: it provides command line examples directly in the resotoshell.
- Fixes #XXXX

[resotocore][feat] Add a tip of the day functionality

---

resotoworker/resotoworker/collect.py

having no post collectors is not an error

[resotoworker][fix] change log severity from error to info when no post collector is configured

---

.github/workflows/check_pr_plugin_scarf.yml
plugins/scarf/resoto_plugin_scarf/resources.py
plugins/scarf/resoto_plugin_scarf/scarf.py
plugins/scarf/test/test_config.py

[plugins/scarf][fix] Correctly update headers

---

plugins/posthog/README.md
plugins/posthog/requirements.txt
plugins/posthog/resoto_plugin_posthog/__init__.py
plugins/posthog/resoto_plugin_posthog/config.py
plugins/posthog/resoto_plugin_posthog/posthog.py
plugins/posthog/resoto_plugin_posthog/resources.py
plugins/posthog/setup.cfg
plugins/posthog/setup.py
plugins/posthog/test/test_config.py
plugins/posthog/tox.ini

[plugins/posthog][feat] Initial posthog plugin

---

.gitignore
.vscode/launch.json
.vscode/settings.json

Added a VSCode config which I find useful for running tests and debugging

[resoto][chore] Add a VSCode launch and test config

---

.github/workflows/docker-build.yml

The `charts` directory was renamed to `someengineering`.

[ci][chore] Update path to helm chart yaml

---

resotocore/resotocore/model/model_handler.py

Show the correct type in diagrams for synthetic properties.

[resotocore][fix] Show the correct kind for synthetic properties

---

.github/workflows/docker-build.yml

Needs to be cherrypicked, but already fixed manually in someengineering/resoto.com#383 so no need to retag the 2.4.2 release.

[ci][chore] Correct file path & link for release notes

---

resotocore/resotocore/core_config.py
resotocore/tests/resotocore/cli/command_test.py

Introduces clearer Jira custom command parameter names

[resotocore][feat] clearer Jira custom command parameter names

---

.github/workflows/docker-build.yml

One more fix (should be cherrypicked but no need to re-tag as this has already been fixed manually for the latest release).

[ci][chore] Correct link for release notes

---

.github/workflows/docker-build.yml

My oversight, sorry! Will need to cherry-pick to the 2.4 branch and re-tag 2.4.3 :(

[ci][chore] Fix release notes generation

---

resotocore/resotocore/web/api.py
resotocore/resotocore/web/tsdb.py

This allows serving debug builds of the UI.
Path: https://server:8900/debug/ui/{commithash}
The artifact is loaded from somecdn.

[resotocore][feat] Allow serving ui test builds

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/task/__init__.py
resotocore/resotocore/task/task_handler.py
resotocore/tests/resotocore/action_handlers/merge_outer_edge_handler_test.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/task/job_handler_test.py
resotocore/tests/resotocore/task/task_handler_test.py

[resotocore][fix] Show meaningful error message if a task is already running

---

.github/workflows/docker-build.yml

This is the fix that is already applied on the 2.4 release branch.

[docker][fix] Create swap file for ARM builds

---

.github/workflows/resotocore_test_and_build.yml
Dockerfile.resotobase
resotocore/jupyterlite_extras/jupyter-lite.json
resotocore/requirements-jupyterlite.txt
resotocore/resotocore/jupyterlite/README.md
resotocore/setup.py

Fix the jupyterlite build by adding a flag. Also update the versions.

[resotocore][fix] Update JupyterLite and add an explicit configuration flag.

---

README.md

Added a few commas to enhance readability.
Documentation error update.
- Fixes #XXXX

Docs(update) README.md

---

resotocore/.gitignore
resotocore/resotocore/jupyterlite/README.md
resotocore/resotocore/web/api.py

Removed the readme.md in the jupyterlite folder.

[resotocore][chore] remove the readme in the jupyterlite folder

---

README.md

Revert error introduced in #1236

[docs][fix] Undo grammar mistake

---

resotocore/tests/resotocore/web/api_test.py

Additional safeguard to not report analytics data for tests.

[resotocore][fix] Make sure no analytics event is sent during test

---

resotocore/resotocore/__main__.py
resotocore/resotocore/analytics/__init__.py
resotocore/resotocore/config/__init__.py
resotocore/resotocore/config/config_handler_service.py
resotocore/resotocore/core_config.py
resotocore/tests/resotocore/config/config_handler_service_test.py

- event `system.installed` now with information about the installation method
- new event `system.configuration-deleted`
- new event `system.configuration-changed` with information about the configured providers and authentication methods

[resotocore][chore] Adjust analytics events

---

plugins/aws/resoto_plugin_aws/resource/service_quotas.py
plugins/aws/test/resources/service_quotas_test.py

Wire service quotas to resources in the same region.

[aws][fix] Service quotas need to match the correct region

---

plugins/aws/resoto_plugin_aws/resource/iam.py
plugins/aws/test/resources/files/iam/list-users.json

Handle `aws_iam_user` with no `PasswordLastUsed`

[aws][fix] Handle aws_iam_user with no PasswordLastUsed

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/test/__init__.py
plugins/aws/test/collector_test.py
plugins/aws/test/graphbuilder_test.py
plugins/aws/test/resources/__init__.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/message_bus.py
resotocore/resotocore/task/task_description.py
resotocore/resotocore/task/task_handler.py
resotocore/setup.py
resotocore/tests/resotocore/message_bus_test.py
resotocore/tests/resotocore/task/task_description_test.py
resotolib/requirements.txt
resotolib/resotolib/core/actions.py
resotolib/resotolib/core/ca.py
resotolib/resotolib/core/progress.py
resotolib/test/core/progress_test.py
resotolib/test/test_plugin.py
resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/collect.py
resotoworker/test/test_collect.py

- resotocore: collect, summarize and emit progress
- resotolib: add ProgressTree and CoreFeedback
- resotoworker: create and pass CoreFeedback
- aws: use CoreFeedback to send messages and progress

[aws][feat] Report errors and progress

---

resotocore/resotocore/message_bus.py
resotolib/requirements.txt
resotoshell/resotoshell/__main__.py
resotoshell/resotoshell/shell.py

Attach to the message_bus and print error messages

[resotoshell][feat] Attach to the message_bus and print error messages

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/digitalocean/resoto_plugin_digitalocean/__init__.py
plugins/digitalocean/resoto_plugin_digitalocean/client.py
plugins/digitalocean/test/test_collector.py
plugins/gcp/resoto_plugin_gcp/__init__.py
plugins/k8s/resoto_plugin_k8s/__init__.py
plugins/k8s/resoto_plugin_k8s/base.py
plugins/k8s/test/collector_test.py
plugins/k8s/test/fixtures.py
resotocore/resotocore/task/task_description.py
resotolib/resotolib/core/actions.py
resotolib/resotolib/core/progress.py
resotolib/test/core/progress_test.py
resotoworker/resotoworker/collect.py

- every collector now by default get progress reported by the worker as fallback
- add error messages for k8s
- add error message and progress for digitalocean
- add error message and progress for gcp
- report all errors from aws

[resoto][feat] Add progress and error for k8s, digialocean and gcp

---

Dockerfile.resotobase
docker-compose.yaml

Set an explicit resh download directory.

[docker][feat] set an explicit resh download directory

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/kms.py
plugins/aws/resoto_plugin_aws/resource/lambda_.py
plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/resoto_plugin_aws/resource/sns.py
plugins/aws/test/aws_client_test.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/__init__.py
plugins/aws/test/resources/s3_test.py

Not all errors are bad - some are valid.
Do not show errors for anything that is not an error.

[aws][feat] Define ignorable errors

---

resotoshell/resotoshell/__main__.py

Opt out from event stream via cmd line arg.

[resotoshell][feat] Allow ignoring updates from event stream.

---

resotocore/resotocore/cli/command.py

[resotocore][chore] Add .cyjs info to cli output

---

plugins/aws/resoto_plugin_aws/__init__.py
resotolib/resotolib/baseresources.py
resotolib/resotolib/core/model_export.py
resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/cleanup.py

Collect feedback during cleanup.

[resotoworker][feat] Report errors that are happening during cleanup

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/resource/apigateway.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/lambda_.py
plugins/aws/resoto_plugin_aws/resource/sns.py
plugins/aws/test/resources/files/lambda/get-policy__test_lambda_function.json

- introduce synthetic id for api gateway stage
- fix policy bender: the input is a json string not json
- sns topic: use the arn as id
- client: report access denied errors as warning
- Fixes #1253

[aws][fix] Fix duplicate ids

---

.github/workflows/check_pr_resotolib.yml
resotolib/resotolib/core/model_export.py
resotolib/test/core/model_export_test.py
resotolib/test/test_graph.py

[resotolib][fix] UnionType and NoneType in python 3.9

---

resotocore/resotocore/task/task_handler.py
resotolib/resotolib/core/progress.py
resotolib/test/core/progress_test.py

Make sure every progress change is sent to the event bus.

[resotocore][fix] Send progress messages when the progress has changed internally

---

plugins/aws/resoto_plugin_aws/resource/autoscaling.py
plugins/aws/resoto_plugin_aws/resource/cloudformation.py
plugins/aws/resoto_plugin_aws/resource/cloudwatch.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/resource/eks.py
plugins/aws/resoto_plugin_aws/resource/elb.py
plugins/aws/resoto_plugin_aws/resource/elbv2.py
plugins/aws/resoto_plugin_aws/resource/iam.py
plugins/aws/resoto_plugin_aws/resource/lambda_.py
plugins/aws/resoto_plugin_aws/resource/rds.py
plugins/aws/resoto_plugin_aws/resource/route53.py
plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/resoto_plugin_aws/resource/service_quotas.py

[plugins/aws][chore] Remove unused imports

---

resotocore/resotocore/static/api-doc.yaml

Fix api doc description for config validation

[resotocore][fix] Fix api doc description for config validation

---

plugins/aws/requirements.txt

Remove unused SQLAlchemy dependency

[plugins/aws][chore] Remove SQLAlchemy dependency

---

.github/workflows/docker-build.yml

Updates CI workflow to generate API docs. Please see someengineering/resoto.com#438 for details.

[ci][chore] Update API docs CI

---

resotoworker/resotoworker/collect.py

Update post collector log message

[resotoworker][chore] Update log message

---

.github/workflows/docker-build.yml
Dockerfile.resotobase

Rebase on resotopython base image and update to Node 16 actions

[docker][fix] Rebase on resotopython base image and update to Node 16 actions

---

.github/workflows/docker-build.yml
Dockerfile.resotobase

Refactor to use resotopython:1.0.2

[docker][fix] Refactor to use resotopython:1.0.2

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/gcp/resoto_plugin_gcp/__init__.py
plugins/k8s/resoto_plugin_k8s/resources.py
resotocore/resotocore/model/model.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/model/model_test.py
resotolib/resotolib/config.py
resotolib/resotolib/core/model_export.py
resotolib/resotolib/graph/__init__.py
resotolib/resotolib/logger.py

The listed changes are prerequisites for cloud2sql to work correctly.
- model export can be narrowed down to explicit known target classes
- config is able to parse external json
- graph_root has an id
- setup_logger is destructive - allow setting the log level explicitly

[resotolib][feat] Customize model export and logging

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/resource/iam.py
resotocore/resotocore/util.py
resotocore/tests/resotocore/util_test.py

Policy Document was stored as string.

[aws][fix] Policy Document is json not string

---

resotoworker/resotoworker/tag.py

[resotoworker][fix] Allow multiple updates

---

.github/workflows/docker-build.yml

See someengineering/resoto.com#453, which adds multiple stable versioned docs support in preparation for the 3.0 release.
Also adds step to update data models.

[ci][chore] Update/tag respective stable version docs on tag

---

resotocore/resotocore/db/arango_query.py
resotocore/tests/resotocore/db/arango_query_test.py

[resotocore][fix] Respect limit in with clause

---

plugins/aws/resoto_plugin_aws/aws_client.py

Handle non list objects in paginated results.

[aws][fix] Handle paginated results that are not lists correctly

---

Dockerfile.resotobase
dockerV2/postflight
dockerV2/resotocore-shim
setup_venv.sh

[docker][feat] Bump Python 3.11

---

Dockerfile.resotobase
resotolib/requirements.txt

[resotolib][chore] Bump cattrs 22.2.0

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/resource/base.py

[aws][fix] Support legacy interface

---

resotolib/resotolib/asynchronous/web/auth.py

Compare origin to host in cookie based JWT auth

[resotolib][fix] Compare origin to host in cookie based JWT auth

---

resotocore/resotocore/task/task_description.py
resotocore/resotocore/task/task_handler.py
resotocore/tests/resotocore/task/task_description_test.py
resotolib/resotolib/core/progress.py
resotolib/test/core/progress_test.py

[resotocore][fix] Define correct progress order

---

.github/workflows/resotocore_coverage.yml
.github/workflows/resotocore_test_and_build.yml
docker-compose.yaml
resotocore/requirements.txt
resotoeventlog/requirements-dev.txt
resotoeventlog/requirements.txt
resotolib/requirements-test.txt
resotolib/requirements.txt

Tested against arangodb 3.10. 
Everything seems to work.
Would move to 3.10 after we tested this setup extensively.
- Fixes #1294

[resotocore][fix] Support ArangoDB 3.10

---

resotocore/resotocore/web/api.py
resotocore/tests/resotocore/web/api_test.py

Send correct multipart response
```http
--cli-part
Content-Type: application/json
["foo"]
--cli-part
Content-Type: application/json
["bla"]
--cli-part
Content-Type: application/json
["bar"]
--cli-part--
```

[resotocore][fix] Fix multipart response handling

---

plugins/aws/resoto_plugin_aws/resource/glacier.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/glacier/list-jobs__nice_vault.json

Adds missing edge between `aws_glacier_job` and `aws_sns_topic`

[plugins/aws][fix] Add missing edge between aws_glacier_job and aws_sns_topic

---

docker-compose.yaml

Use ArangoDB 3.10.1 in docker-compose

[docker][feat] Use ArangoDB 3.10.1 in docker-compose

---

plugins/aws/resoto_plugin_aws/resource/cloudwatch.py

[aws][fix] Correct method name

---

plugins/aws/resoto_plugin_aws/resource/kinesis.py

Only a bandaid fix - proper fix will follow.

[aws][fix] Handle Kinesis response correctly

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/db/runningtaskdb.py
resotocore/resotocore/message_bus.py

Errors reported by the plugins are shown. 
If the complete action fails, the message is shown only once and unavailable via the log.
This PR fixes the issue and also shows an error message here.

[resotocore][fix] Also show ActionErrors in log

---

plugins/aws/resoto_plugin_aws/collector.py

[aws][fix] Define missing API calls

---

plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/ec2.py

Non regional edge could lead to wrong edges being created.
- Fixes #1329

[aws][fix] Remove wrong edge from VolumeType -> Volume

---

plugins/aws/resoto_plugin_aws/resource/cloudformation.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/__init__.py
plugins/aws/test/resources/cloudformation_test.py
plugins/aws/test/resources/files/cloudformation/list-stack-instances__ResotoAccessStack_some_id.json
plugins/aws/test/resources/files/cloudformation/list-stack-sets__ACTIVE.json
plugins/aws/tools/model_gen.py

[aws][feat] Add deferred edge from StackSet to Stack instance

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/resource/iam.py
plugins/aws/test/resources/iam_test.py

All policy versions can get really big!
Also non existing service endpoints get ignored during collect.

[aws][fix] Only collect default policy

---

plugins/aws/resoto_plugin_aws/collector.py

[aws][fix] Add missing collect api

---

plugins/aws/resoto_plugin_aws/configuration.py
resotolib/resotolib/proc.py

[aws][fix] Redefine default pool sizes

---

resotocore/resotocore/cli/command.py
resotocore/tests/resotocore/cli/command_test.py

[resotocore][fix] Read search arguments more gracefully

---

plugins/k8s/resoto_plugin_k8s/base.py
plugins/k8s/resoto_plugin_k8s/collector.py
plugins/k8s/test/collector_test.py
plugins/k8s/test/config_test.py

- Allow pasting whole kube config object
- In case of zero configs, fall back to default locations
- filtering is done on resource kind

[k8s][feat] Allow defining access as kubernetes config

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/resource/cloudfront.py
resotolib/resotolib/json.py

- default values for list properties were missing
- Tags get collected for resources without ARN
- Paginated results with more than one batch only handled the first one

[aws][fix] Fix CloudFront collection

---

plugins/aws/setup.py
plugins/aws_k8s/setup.py
plugins/cleanup_aws_alarms/setup.py
plugins/cleanup_aws_loadbalancers/setup.py
plugins/cleanup_aws_vpcs/setup.py
plugins/cleanup_expired/setup.py
plugins/cleanup_untagged/setup.py
plugins/cleanup_volumes/setup.py
plugins/digitalocean/setup.py
plugins/digitalocean_k8s/setup.py
plugins/dockerhub/setup.py
plugins/example_collector/setup.py
plugins/gcp/setup.py
plugins/github/setup.py
plugins/k8s/setup.py
plugins/onelogin/setup.py
plugins/onprem/setup.py
plugins/posthog/setup.py
plugins/protector/setup.py
plugins/random/setup.py
plugins/scarf/setup.py
plugins/slack/setup.py
plugins/tagvalidator/setup.py
plugins/vsphere/setup.py
resotocore/setup.py
resotoeventlog/setup.py
resotolib/setup.py
resotometrics/setup.py
resotoshell/setup.py
resotoworker/setup.py

In pypi and also in brew formulas the URL is taken into consideration and should be defined.

[resoto][chore] Define project urls

---

resotolib/requirements.txt
resotolib/resotolib/core/progress.py
resotolib/resotolib/tree.py
resotolib/test/test_tree.py

treelib is marked vulnerable in snyk due to a transitive dependency.
This PR inlines the required code so the dependency is no longer required.

[resoto][chore] Inline treelib

---

README.md

[resoto][feat] Add vulnerability badge

---

resotocore/resotocore/core_config.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/core_config_test.py

- Allow defining the request body size 
- Increase the default from 1mb to 5mb

[resotocore][feat] Allow adjusting request body size

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/test/graphbuilder_test.py

Always fetch the instance types from every region.

[aws][fix] Fetch instance types in all regions

---

plugins/aws/resoto_plugin_aws/__init__.py

Explicit message if an account gets discarded.

[aws][chore] Improve error messages

---

plugins/aws/resoto_plugin_aws/resource/lambda_.py
plugins/aws/test/resources/lambda_test.py

Optional fields should be marked as optional.

[aws][fix] Aws lambda function can not be read

---

.github/workflows/docker-build.yml

Temporary workaround for docker/buildx#1533

[docker][fix] set `provenance: false` on docker/build-push-action

---

plugins/aws/resoto_plugin_aws/resource/sqs.py
plugins/aws/test/resources/files/sqs/get-queue-attributes__All_queue_amazonaws_com_882347060974_SomeName.json
resotolib/resotolib/json_bender.py

[aws][fix] Fix SQS handling

---

Dockerfile.resotobase
docker-compose.yaml
docker/service.in/resotocore.sh
resotocore/requirements.txt
resotocore/resotocore/core_config.py
resotocore/resotocore/dependencies.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/config/core_config_handler_test.py
resotocore/tests/resotocore/core_config_test.py

Use the Resoto UI as dependency.

[resotocore][feat] Use UI as dependency

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
resotoworker/resotoworker/cleanup.py

[aws][fix] Fix predelete was not called

---

plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/ecs.py
plugins/aws/resoto_plugin_aws/resource/elasticbeanstalk.py
plugins/aws/resoto_plugin_aws/resource/sns.py
resotoworker/resotoworker/tag.py

Fix handling of ecs, beanstalk and sns

[aws][fix] Fix handling of ecs, beanstalk and sns

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/test/aws_client_test.py
resotolib/resotolib/core/actions.py

Accumulate same errors and report them combined

[aws][fix] Accumulate same errors and report them combined

---

plugins/cleanup_expired/setup.py
plugins/gcp/resoto_plugin_gcp/collector.py
plugins/gcp/resoto_plugin_gcp/resources.py

Fixed the private values which were not handled nicely by attrs

[plugins/gcp][fix] Fix the GCP collection issues

---

plugins/gcp/resoto_plugin_gcp/gcp_client.py
plugins/gcp/resoto_plugin_gcp/resources/billing.py
plugins/gcp/resoto_plugin_gcp/resources/sqladmin.py

Make next gen gap collector work.

[gcp][fix] Make gcp_next work again

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/collector.py
resotolib/resotolib/core/progress.py
resotolib/test/core/progress_test.py

Show progress update for all accounts right away - not when the executor starts.
Same for all regions when the account is collected.

[aws][fix] List all accounts and all regions in progress update

---

plugins/gcp/test/random_client.py
plugins/gcp/test/test_compute.py
resotolib/resotolib/json.py

Support created nodes with specific data and test edge creation.

[gcp][feat] Support testing edges

---

plugins/aws/resoto_plugin_aws/resource/efs.py
plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/resoto_plugin_aws/resource/sagemaker.py

[aws][fix] Fix IAM permissions

---

resotocore/resotocore/task/task_handler.py

this breaks the black formatter on main.

[resotocore][fix] Fix merge conflict

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/cloudtrail.py
plugins/aws/resoto_plugin_aws/resource/efs.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/__init__.py
plugins/aws/test/resources/cloudtrail_test.py
plugins/aws/test/resources/files/cloudtrail/get-event-selectors__arn_aws_cloudtrail_us_east_1_test_trail_management_events.json
plugins/aws/test/resources/files/cloudtrail/get-insight-selectors__arn_aws_cloudtrail_us_east_1_test_trail_management_events.json
plugins/aws/test/resources/files/cloudtrail/get-trail-status__arn_aws_cloudtrail_us_east_1_test_trail_management_events.json
plugins/aws/test/resources/files/cloudtrail/get-trail__arn_aws_cloudtrail_us_east_1_test_trail_management_events.json
plugins/aws/test/resources/files/cloudtrail/list-tags__arn_aws_cloudtrail_us_east_1_test_trail_management_events.json
plugins/aws/test/resources/files/cloudtrail/list-trails.json
plugins/aws/tools/model_gen.py
resotolib/resotolib/json_bender.py

[aws][feat] Collect CloudTrail resources

---

.github/CODEOWNERS

[chore][github] update CODEOWNERS

---

plugins/onprem/resoto_plugin_onprem/__init__.py
plugins/onprem/resoto_plugin_onprem/resources.py
plugins/onprem/resoto_plugin_onprem/ssh.py

Fix log formating in forked onprem collector

[fix][plugins/onprem] Fix log formating in forked onprem collector

---

plugins/aws/resoto_plugin_aws/resource/cloudtrail.py
plugins/aws/resoto_plugin_aws/resource/efs.py

Forgot to push my last commit.

[aws][fix] CloudTrail: last commit

---

plugins/aws/resoto_plugin_aws/resource/athena.py
plugins/aws/resoto_plugin_aws/resource/ecs.py
plugins/aws/resoto_plugin_aws/resource/elasticache.py
plugins/aws/resoto_plugin_aws/resource/kinesis.py

- `aws_elasticache_cache_cluster` -> `aws_sns_topic`
- `aws_athena_work_group` -> `aws_s3_bucket`
- `aws_kinesis_stream` <-> `aws_kms_key` 

[aws][fix] add missing edges

---

resotocore/requirements-dev.txt
resotoeventlog/requirements-dev.txt
resotolib/requirements-test.txt

[resoto][chore] downgrade to tox 3.28.0

---

plugins/aws/tools/awspolicygen/awspolicygen/upload.py
plugins/aws/tools/awspolicygen/requirements-test.txt
plugins/aws/tools/awspolicygen/tox.ini

Fix E713 in awspolicygen. Also updates toxfile for tox 4.

[fix][plugin/aws] Fix E713 in awspolicygen

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/cloudtrail.py
plugins/aws/resoto_plugin_aws/resource/config.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/resource/kms.py
plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/config_test.py
plugins/aws/test/resources/ec2_test.py
plugins/aws/test/resources/files/config/describe-configuration-recorder-status.json
plugins/aws/test/resources/files/config/describe-configuration-recorders.json
plugins/aws/test/resources/files/ec2/describe-flow-logs.json
plugins/aws/test/resources/files/kms/describe-key__32b03fb9.json
plugins/aws/test/resources/files/kms/get-key-rotation-status__32b03fb9.json
plugins/aws/test/resources/files/s3/get-bucket-acl__bucket_1.json
plugins/aws/test/resources/files/s3/get-bucket-logging__bucket_1.json
plugins/aws/test/resources/kms_test.py
plugins/aws/tools/model_gen.py
resotocore/resotocore/static/report/benchmark/aws/aws_cis_1.5.json
resotocore/resotocore/static/report/checks/aws/aws_cloudtrail.json
resotocore/resotocore/static/report/checks/aws/aws_config.json
resotocore/resotocore/static/report/checks/aws/aws_ec2.json
resotocore/resotocore/static/report/checks/aws/aws_kms.json
resotolib/resotolib/json.py
resotolib/resotolib/json_bender.py

[aws][feat] AWS CIS Section 3 Logging

---

plugins/aws/resoto_plugin_aws/resource/cloudtrail.py
plugins/aws/resoto_plugin_aws/resource/efs.py
plugins/aws/resoto_plugin_aws/resource/eks.py

[aws][fix] EKS reference to autoscaling group, EFS delete and multi region Cloud Trails

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/cloudtrail.py
plugins/aws/resoto_plugin_aws/resource/kms.py
plugins/aws/test/__init__.py
plugins/aws/test/collector_test.py
resotocore/resotocore/static/report/benchmark/aws/aws_cis_1.5.json
resotocore/resotocore/static/report/checks/aws/aws_cloudtrail.json

Collect the trail in home account and region.
Use deferred edges for all other places this trail is listed.

[aws][fix] Only collect trail in home account and region

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/rds.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/rds/describe-db-clusters.json
plugins/aws/test/resources/rds_test.py
plugins/aws/tools/model_gen.py
resotolib/resotolib/baseresources.py
resotolib/resotolib/json_bender.py

[resotolib][feat] Support RDS Clusters

---

plugins/gcp/resoto_plugin_gcp/resources/compute.py

Adds edges to Gcp Compute Resources for the next-gen collector.
Edges already defined have remained unchanged, new ones have been added.

[gcp][feat] Add edges to compute resource models in next gen collector pt. 2

---

resotolib/resotolib/baseresources.py
resotolib/resotolib/graph/__init__.py

When duplicate nodes are found in the graph the current debug output has no information about their neighbourhood making it impossible to properly identify the issue.

[resotolib][chore] Add better debug output

---

plugins/gcp/resoto_plugin_gcp/resources/container.py
plugins/gcp/test/test_container.py

`gcp_container_cluster` -> `gcp_container_operation`

[gcp][feat] Add edges to container resource models in next gen collector

---

plugins/vsphere/resoto_plugin_vsphere/vsphere_client.py

Update VSphere Client to use new Config syntax

[plugins/vsphere][fix] Update VSphere Client to use new Config syntax

---

plugins/aws/resoto_plugin_aws/resource/iam.py
plugins/aws/resoto_plugin_aws/resource/sagemaker.py
resotolib/resotolib/graph/__init__.py
resotolib/test/test_graph.py
resotoworker/resotoworker/collect.py

Fix cyclic dependency and show the cycle directly in the log.

[aws][fix] Fix cyclic dependency and log the cycle

---

resotolib/resotolib/graph/__init__.py
resotolib/test/test_graph.py

[resotolib][chore] Remove unused code

---

plugins/aws/resoto_plugin_aws/aws_client.py

[aws][fix] Complete the list of retryable errors

---

plugins/gcp/resoto_plugin_gcp/resources/sqladmin.py
plugins/gcp/test/test_sqladmin.py

`gcp_database_instance` -> `gcp_sql_backup_run`
`gcp_ssl_certificate` -> `gcp_sql_database_instance`
`gcp_sql_database_instance` -> `gcp_sql_operation`

[gcp][feat] Add edges to sqladmin resource models in next gen collector

---

resotocore/resotocore/analytics/__init__.py
resotocore/resotocore/db/graphdb.py

Event with the highest frequency that does not provide any insights.

[resotocore][chore] Remove Query event

---

plugins/cleanup_untagged/resoto_plugin_cleanup_untagged/__init__.py
plugins/cleanup_untagged/resoto_plugin_cleanup_untagged/config.py
plugins/cleanup_untagged/test/test_config.py
plugins/cleanup_untagged/tox.ini
plugins/tagvalidator/resoto_plugin_tagvalidator/__init__.py
plugins/tagvalidator/resoto_plugin_tagvalidator/config.py
plugins/tagvalidator/test/test_config.py
plugins/tagvalidator/tox.ini
resotolib/resotolib/baseplugin.py

[plugin][fix] Fix wrong cleanup and tagvalidator plugin

---

plugins/vsphere/resoto_plugin_vsphere/__init__.py
plugins/vsphere/resoto_plugin_vsphere/resources.py

Update VSphere Plugin for Resoto 3.0

[plugins/vsphere][fix] Update VSphere Plugin for Resoto 3.0

---

plugins/gcp/resoto_plugin_gcp/resources/billing.py

Minor stuff to have more consistency across resource models. Not much else to do here 👍🏻 

[gcp][chore] Housekeeping

---

plugins/aws/resoto_plugin_aws/resource/efs.py
plugins/aws/test/resources/__init__.py
plugins/aws/test/resources/efs_test.py
resotolib/resotolib/baseresources.py
resotolib/resotolib/json_bender.py

[aws][fix] EFS Share is a network share not a volume

---

resotocore/requirements.txt

[resotocore][feat] Bump UI to 3.2.2

---

.github/workflows/publish.yml

(Manually fixed for the 3.2.2 release notes)

[ci][chore] Fix writing of release notes link to website repo

---

resotocore/resotocore/core_config.py

[resotocore][chore] Improve wording.

---

resotocore/requirements.txt

[resotocore][chore] Bump UI to 3.2.3

---

.github/holopin.yml

Adds configuration file to allow for issuing of Holopins to GitHub contributors.

[holopin][chore] Add Holopin config
