README.md

Use full image paths so that external websites like Dockerhub don't show broken images.

Update README with full image paths for use on external sites

---

plugins/logdump/cloudkeeper_plugin_logdump/__init__.py

By default the logdump plugin would fail if the `--logdump-path` did not exist. It now tries to create it upon startup.

Create logdump path if it does not exist

---

README.md
cloudkeeper/cloudkeeper/__main__.py
cloudkeeper/cloudkeeper/baseresources.py
cloudkeeper/cloudkeeper/cli.py
cloudkeeper/cloudkeeper/event.py
cloudkeeper/cloudkeeper/scheduler.py
cloudkeeper/cloudkeeper/web.py
cloudkeeper/setup.py
plugins/remote_event_callback/README.md
plugins/remote_event_callback/cloudkeeper_plugin_remote_event_callback/__init__.py
plugins/remote_event_callback/setup.cfg
plugins/remote_event_callback/setup.py
plugins/remote_event_callback/test/test_args.py
plugins/remote_event_callback/tox.ini

This PR implements periodically scheduled CLI actions.
In the process it adds support for one-shot event registrations (i.e. registering for an event and having the callback happen only once).

Allow scheduling of CLI actions

---

cloudkeeper/cloudkeeper/baseresources.py
plugins/aws/cloudkeeper_plugin_aws/accountcollector.py

Fixes an issue where if the Pricing API returned invalid data the collection of EC2 instances would abort leading to no instances being connected to ALBs/ELBs in the Graph. This would then cause the LB Cleanup Plugin to think that the LBs are orphaned and remove them.

Fix an error where LB cleanup would falsely remove ELBs/ALBs if pricing API returns invalid results

---

plugins/aws/cloudkeeper_plugin_aws/accountcollector.py
plugins/cleanup_aws_loadbalancers/cloudkeeper_plugin_cleanup_aws_loadbalancers/__init__.py

This uses the new .backends loadbalancer attribute when performing cleanup to double check that a) there's no backends in the graph and b) there's no backends added to the LB node itself.

Double check the number of backends in AWS LB cleanup

---

plugins/aws/cloudkeeper_plugin_aws/resources.py
plugins/cleanup_aws_vpcs/README.md
plugins/cleanup_aws_vpcs/cloudkeeper_plugin_cleanup_aws_vpcs/__init__.py
plugins/cleanup_aws_vpcs/setup.py
plugins/cleanup_aws_vpcs/test/test_args.py

Instead of targeting all VPCs marked for cleaning in all accounts, users can now whitelist account IDs in a config file.

Config file support for Cleanup AWS VPCs plugin

---

keepercore/.gitignore
keepercore/core/__main__.py
keepercore/core/cli/cli.py
keepercore/core/cli/command.py
keepercore/core/db/graphdb.py
keepercore/core/error.py
keepercore/core/event_bus.py
keepercore/core/model/model.py
keepercore/core/model/model_handler.py
keepercore/core/parse_util.py
keepercore/core/query/query_parser.py
keepercore/core/static/api-doc.yaml
keepercore/core/util.py
keepercore/core/web/api.py
keepercore/requirements-dev.txt
keepercore/requirements.txt
keepercore/tests/core/cli/cli_test.py
keepercore/tests/core/cli/command_test.py
keepercore/tests/core/model/__init__.py
keepercore/tests/core/util_test.py

This PR introduces a CLI that tries to match the UI of the existing CLI in cloudkeeper (work in progress).
A command in `keepercore` can contain several command lines chained by a semicolon.
Every command line consists of one or more commands chained by a pipe.
Data emitting commands are called sources and transformation commands are called flow commands.
Every command line has this structure: `source | flow | ... | flow | sink`.
Since the command line interpreter is remote, the sink is always the http response.
In order to test this behaviour locally, start up keepercore and fire this on your command line:
```
▶ echo 'help' | http :8080/cli/execute  | jq -r ".[0]"                   
```
Which currently gives you this result:
```
Valid placeholder string:
@UTC@ -> 2021-08-18T13:12:51Z …
```

[keepercore] CLI Genesis

---

cloudkeeper/cloudkeeper/event.py
keepercore/core/__main__.py
keepercore/core/db/async_arangodb.py
keepercore/core/db/db_access.py
keepercore/core/db/entitydb.py
keepercore/core/db/modeldb.py
keepercore/core/db/subscriberdb.py
keepercore/core/event_bus.py
keepercore/core/model/model.py
keepercore/core/model/model_handler.py
keepercore/core/model/typed_model.py
keepercore/core/static/api-doc.yaml
keepercore/core/web/api.py
keepercore/core/workflow/model.py
keepercore/core/workflow/subscribers.py
keepercore/core/workflow/workflows.py
keepercore/tests/core/db/entitydb.py
keepercore/tests/core/db/graphdb_test.py
keepercore/tests/core/db/modeldb_test.py
keepercore/tests/core/db/subscriberdb_test.py
keepercore/tests/core/workflow/subscribers_test.py
keepercore/tests/core/workflow/workflows_test.py

This PR introduces durable subscriptions: all subscriptions are stored in a database and will be loaded when the service restarts. 
A subscription is automatically removed, when a client subscribes to events, but does not connect to handle those events.
- endpoint is added to define all subscriptions of one handler with one request (`PUT  /subscriber/{subscriber_id}`)
- endpoint is added to remove one subscriber with all subscriptions (`DELETE  /subscriber/{subscriber_id}`)
- it is checked, that there is only one active listener per subscriber_id
- api-documentation for the subscriber endpoints

[keepercore] Durable subscriptions

---

keepercore/core/cli/command.py
keepercore/tests/core/cli/command_test.py

Fixes #103
Mental mismatch:
```
async def foo() -> AsyncGenerator[int, None]:
raise Exception("")
for a in range(0, 100):
yield a
async def bla() -> AsyncGenerator[int, None]:
async def gen() -> AsyncGenerator[int, None]:
for a in range(0, 100):
yield a
raise Exception("")
return gen()
```
foo() and bla() both return the same result.
bla() needs to be awaited and throws an exception when called while foo() would throw an exception,
when the generator is consumed.
This has been the case with echo: so parse_arg did not throw, but execute did.
I also changed the implementation of echo to allow empty string or any other value as string, if it can not be parsed as json.

[keepeercore] Fix echo parse_arg

---

keepercore/core/cli/command.py
keepercore/core/db/arangodb_functions.py
keepercore/core/db/graphdb.py
keepercore/core/db/model.py
keepercore/core/static/api-doc.yaml
keepercore/core/web/api.py
keepercore/tests/core/db/graphdb_test.py

Example:
```
reported.name=="foo" and desired.cleaned==true and metadata.version>2
```
Following new endpoints are available:
- `POST /graph/{graph_id}/query`
- `POST /graph/{graph_id}/query/raw`
- `POST /graph/{graph_id}/query/explain`
- `POST /graph/{graph_id}/query/list`
- `POST /graph/{graph_id}/query/graph`
- `POST /graph/{graph_id}/query/aggregate`

[keepercore] add endpoints to query all sections

---

keepercore/core/cli/cli.py
keepercore/core/cli/command.py
keepercore/core/db/graphdb.py
keepercore/core/model/model.py
keepercore/core/query/model.py
keepercore/core/query/query_parser.py
keepercore/core/web/api.py
keepercore/tests/core/cli/cli_test.py
keepercore/tests/core/db/graphdb_test.py
keepercore/tests/core/model/model_test.py
keepercore/tests/core/query/query_parser_test.py

Allows definition of `merge_with="parent_kind,..,parent_kind"`
The specified kinds are searched in the graph and merged with every search result.
Example:
```
{merge_with="cloud,account"}: isinstance("instance_quota")
```
will search all nodes of kind `instance_quota`. 
The result will additionally contain following properties in the reported section:
- cloud: the first predecessor of the instance node of type `cloud`
- account: the first predecessor of the instance node of type `account`
This can be used to aggregate values like this:
```
aggregate(cloud.name as cloud, region.name as region : sum(quota) as quota) {merge_with="cloud,region"}: isinstance("base_instance_quota")
```

[keepercore] merge nodes as part of the query

---

keepercore/core/__main__.py
keepercore/core/db/db_access.py
keepercore/core/db/graphdb.py
keepercore/core/model/adjust_node.py
keepercore/core/model/graph_access.py
keepercore/core/model/model.py
keepercore/core/model/resolve_in_graph.py
keepercore/core/util.py
keepercore/tests/core/cli/cli_test.py
keepercore/tests/core/db/graphdb_test.py
keepercore/tests/core/model/adjust_node_test.py
keepercore/tests/core/model/graph_access_test.py
keepercore/tests/core/model/model_test.py
keepercore/tests/core/model/resolve_in_graph_test.py
keepercore/tests/core/util_test.py
keepercore/tox.ini

- In order to make it very simple to filter for cloud, account, region, zone: the data is retrieved and stored with each node in the metadata section (note only the name is available, which should be enough for filtering reasons)
- the id of the related node is stored separately to enable direct fetching of additional data
- AdaptNode is introduced which is called after the node has been processed (and possibly updated) and before it is written to the database. Current use-case: interpret the expire/expiration tag

[keepercore] Resolve common graph references during import

---

keepercore/core/db/graphdb.py
keepercore/core/parse_util.py
keepercore/core/query/model.py
keepercore/core/query/query_parser.py
keepercore/tests/core/db/graphdb_test.py
keepercore/tests/core/query/query_parser_test.py

This change allows for creating combined aggregation variables.
Example:
```
aggregate("{account.name} ({account.id})" as account: sum(reservations) as reserved_instances_total) (merge_with_ancestors="account"): is("instance_type")
```
For every matching element, a string is created with this template and used as aggregation variable. The result could look like this:
```
[
{
"group": {"account": "pumpkin (123512331213)"},
"reserved_instances_total": 23
},
{
"group": {"account": "demo (123512331212)"},
"reserved_instances_total": 12
}
]
```
Fixes #154

[keepercore] Aggregation: allow combined parameters

---

cksh/cksh/__main__.py

- Request text/plain instead of application/yaml
- Submit tty columns/rows headers for server side output formatting
- Add `--stdin` arg for reading commands from stdin instead of starting an interactive terminal session

[cksh] Request text/plain instead of application/yaml

---

keepercore/core/parse_util.py
keepercore/tests/core/parse_util_test.py
keepercore/tests/core/query/query_parser_test.py

This change introduces an unquoted string parser that allows timestamps to be entered without quotes

[keepercore] A more generous unquoted string parser

---

ckcore/core/model/graph_access.py
ckcore/core/model/resolve_in_graph.py

Example:
```
> reported is(gcp_instance) limit 1
reported:
kind: gcp_instance
id: '123123123'
tags: {}
name: agent1
ctime: '2018-04-20T01:31:04Z'
instance_cores: 2
instance_memory: 7.5
instance_type: n1-standard-2
instance_status: terminated
link: https://www.googleapis.com/compute/v1/projects/fooo/zones/us-central1-c/instances/agent1
label_fingerprint: 42WmSpB8rSM=
metadata:
ancestors:
cloud:
name: gcp
id: gcp
account:
name: foo-support
id: foo-support
region:
name: us-central1
id: '1000'
zone:
name: us-central1-c
id: '2002'
kinds:
- instance
- resource
- gcp_instance
- gcp_resource
```

[ckcore] Make resolved ancestor attributes available under metadata.ancestors.

---

ckcore/core/cli/command.py
ckcore/core/db/graphdb.py
ckcore/core/model/graph_access.py
ckcore/core/model/model.py
ckcore/core/model/model_handler.py
ckcore/core/web/api.py
ckcore/tests/core/cli/command_test.py
ckcore/tests/core/db/graphdb_test.py
ckcore/tests/core/db/modeldb_test.py
ckcore/tests/core/model/model_test.py

```
Usage: kind [-p property_path] [name_of_kind]
kind gives information about the graph data kinds.
Use case 1: show all available kinds:
$> kind
This will list all available kinds and print the name as list.
Use case 2: show all details about a specific kind:
$> kind graph_root
This will show all available information about the given kind.
Use case 3: I want to know the kind of a property in my model
$> kind reported.tags.owner
Lookup the type of the given property in the model.
Assume a complex model A with reported properties: name:string, tags:dictionary[string, string]
A lookup of property name reported.tags.owner will yield the type string
```

[ckcore] Introduce kind command

---

ckcore/core/__main__.py

This PR:
- updates all arg descriptions to use the same syntax as the other ck* programs
- binds on localhost by default instead of 0.0.0.0
- adds the `--host` arg which allows to bind on multiple interfaces
Example:
```
$ckcore --host 127.0.0.1 ::1
...
...
======== Running on http://127.0.0.1:8900, http://[::1]:8900 ========
...
```
The default value is a string `localhost` which will make aiohttp choose the appropriate interface(s) depending on whether IPv4, v6 or both are available.

[ckcore] Update arg descriptions and bind localhost only by default

---

ckcore/core/__main__.py
docker/bootstrap-graphdb
docker/supervisor.conf.in/ckcore.conf

The current GraphDB backend is ArangoDB with plans to add more. Instead of using `--arangodb-server` as a main arg to ckcore we should use a more generic one like `--graphdb-server` and then have a selector like `--graphdb-type arangodb` to choose the backend type. That way we're not going to end up with multiple redundant args like `--arangodb-server --neo4j-server --orientdb-server --dgraph-server` and their `*-username *-password *-database` equivalents.

Use generic GraphDB args

---

ckcore/core/__main__.py

There seem to be scenarios, where aiohttp is not allowed to bind to the ipv6 localhost device.
To not run into this issue, the default uses the ipv4 loopback address explicitly.

[ckcore] use 127.0.0.1 as default host

---

ckcore/core/db/async_arangodb.py

Until this fix is shipped, add the `-reduce-extraction-to-projection` optimizer flag.
See: https://github.com/arangodb/arangodb/pull/14801

[ckcore] Apply workaround for arango issue

---

ckcore/.pylintrc
ckcore/core/db/arango_query.py
ckcore/core/db/graphdb.py
ckcore/core/query/model.py
ckcore/core/query/query_parser.py
ckcore/core/util.py
ckcore/requirements.txt
ckcore/tests/core/db/graphdb_test.py
ckcore/tests/core/query/query_parser_test.py

This PR adds support for subqueries.
Subqueries are queries executed for every matching element. 
The result of this subquery will be added to the original element.
Example:
```
is(aws_ec2_instance) {region: <-[0:]- is(region), account: <-[0:]- is(account), cloud: <-[0:]- is(cloud)}  
```
This query will match all aws_ec2_instances.
The subqueries now define to add region, account and cloud by executing the related subqueries on every element.
The resulting json element will look like this:
```
[
{
id: ".."
reported: {..}
desired: {..}
metadata: { ..}
cloud: { id: "..", reported: {..}, desired:{..}, metadata:{..}} 
account: { id: "..", reported: {..}, desired:{..}, metadata:{..}} 
region: { id: "..", reported: {..}, desired:{..}, metadata:{..}} 
},
.
.
]
```

[ckcore] Add support for subqueries

---

ckcore/core/db/arango_query.py
ckcore/core/db/arangodb_functions.py
ckcore/core/query/model.py
ckcore/core/query/query_parser.py
ckcore/tests/core/db/arangodb_functions_test.py
ckcore/tests/core/query/query_parser_test.py

Support `some.array all > 23` or `some.array any < 12` or `some.array none in [1, 2, 3]`
Also add a function to test for available keys: `has_key(path.to.property, name_of_prop)` or `has_key(path.to.property, [name_of_prop_a, name_of_prop_b])` which evaluates to true, if reported.tags has all the properties named.

[ckcore] Add support for array modifiers

---

ckcore/core/db/arango_query.py
ckcore/core/query/model.py
ckcore/core/query/query_parser.py
ckcore/tests/core/db/arangodb_functions_test.py
ckcore/tests/core/db/graphdb_test.py
ckcore/tests/core/query/model_test.py
ckcore/tests/core/query/query_parser_test.py

`is(volume)` matches all resources of type volume
`is([volume, instance])` matches all resources of type volume or of type instance

[ckcore] is() allows for list of kinds

---

.github/workflows/test_ckcore.yml
Dockerfile
ckcore/core/db/async_arangodb.py
ckcore/core/db/db_access.py
ckcore/core/error.py
docs/source/getting_started/setup_individual_components.rst

Reverts workaround introduced in #254
Fixes: https://github.com/someengineering/cloudkeeper/projects/1#card-69699569

[bump] Define arangodb 3.8.3 as dependency

---

ckcore/core/cli/cli.py
ckcore/core/db/arango_query.py
ckcore/core/model/graph_access.py
ckcore/core/model/resolve_in_graph.py
ckcore/core/query/model.py
ckcore/core/query/query_parser.py
ckcore/tests/core/query/__init__.py
ckcore/tests/core/query/model_test.py
ckcore/tests/core/query/query_parser_test.py

This PR brings a change to the query language which introduces 2 "magic" sections: ancestors and descendants.
In order to merge and filter data of properties coming from a node which is connected to the current selected node,
it is now as easy as write: `ancestors.<kind>.path.to.property <op> <value>`. This predicate will be translated into a merge query which will merge the current node with the ancestor node of given kind. The path that is defined will be available after the merge and can be used to filter the result.
Example:
```
> query is(volume) and ancestors.volume_type.reported.volume_type=pd-standard
```
This query will select all `volume`s. All matching instances get merged with the relevant ancestor of kind `volume_type` and filtered by the reported property `volume_type`.
The …

[ckcore] Rewrite query to automatically merge ancestors and/or descendants

---

cklib/cklib/x509.py

For completeness this adds `csr_to_bytes()` as an alias to `cert_to_bytes()`

[cklib] Add `csr_to_bytes()` to x509 functions

---

ckcore/core/cli/cli.py
ckcore/core/cli/command.py
ckcore/core/db/__init__.py
ckcore/core/db/arango_query.py
ckcore/core/db/async_arangodb.py
ckcore/core/db/graphdb.py
ckcore/core/static/api-doc.yaml
ckcore/core/web/api.py
ckcore/tests/core/cli/command_test.py
ckcore/tests/core/db/arango_query_test.py

API: use the `/query/explain` endpoint to get the query cost estimate.
CLI: use `query --explain` flag to get the query cost estimate.
Fixes: #505

[ckcore] Introduce query cost explanation

---

ckcore/core/task/task_description.py
ckcore/core/task/task_handler.py
ckcore/tests/core/task/task_handler_test.py

A TaskDescriptor can now use surpass behaviour wait.
If a task is started and there is a task with the same descriptor already running, the task is added to a starting queue. Once the existing task is finished, the next task will be started directly.
Note: There can be only one item in the waiting queue per task descriptor. If one task is already running, one already in the waiting queue and another one is triggered, the waiting queue does not change.
Fixes #172

[ckcore] Introduce the TaskSurpassBehaviour `Wait`

---

ckcore/core/__main__.py
ckcore/tests/core/web/api_test.py

The entry point to the process as defined in setup.py does not allow to define parameters.
So `main` does not define parameters, but `run` does.
`run` is used in Integration tests to start ckcore in different configurations.

[ckcore] Fix entrypoint.

---

ckcore/core/__main__.py
ckcore/core/cli/__init__.py
ckcore/core/cli/cli.py
ckcore/core/cli/command.py
ckcore/core/cli/model.py
ckcore/core/parse_util.py
ckcore/core/task/task_description.py
ckcore/core/task/task_handler.py
ckcore/core/web/api.py
ckcore/tests/core/cli/cli_test.py
ckcore/tests/core/cli/command_test.py
ckcore/tests/core/db/jobdb_test.py
ckcore/tests/core/task/task_description_test.py
ckcore/tests/core/web/api_client.py
cksh/README.md
docs/source/getting_started/quick_start.rst
docs/source/manual/automate.rst
plugins/tagvalidator/README.md

Replace `add_job` `delete_job`, `tasks` with a more powerful `jobs` command
```
jobs: get the list of all jobs in the system
jobs show <name>: show the current definition of the job defined by given job name
jobs add <name> ...: add a job to the task handler with provided name, trigger and command line to execute.
jobs update <name> ... : update trigger and or command line of an existing job with provided name.
jobs delete <name>: delete the job with the provided name.
jobs activate <name>: activate the triggers of a job.
jobs deactivate <name>: deactivate the triggers of a job - so the job will not get started.
jobs run <name>: run the job as if the trigger would be triggered.
jobs ps: show all currently running jobs.
```
Fixes #517

[ckcore] Unify jobs command

---

.github/workflows/deploy-api-docs.yml
resotocore/core/static/api-doc.yaml

Generates and deploys Swagger UI to GitHub Pages, so that we can link to it from the docs rather than instructing users to view it from their own installs.

Deploy API docs to GH Pages

---

resotocore/core/cli/command.py

Otherwise the system command might fail in certain scenarios.
This happens under tox, but not under pytest directly.

[resotocore][fix] Define configfile parameter explicitly

---

.github/PULL_REQUEST_TEMPLATE.md

Remind PR authors that documentation needs to be updated, by adding a to-do to the PR template.
Users can easily reference the relevant documentation PR in the someengineering/resoto.com repo by simply replacing `XXXX` with the PR number/ID.

[github] Update PR template w/ documentation to-do

---

README.md

Link to `resotoshell` had a typo.

[README] fix dead link in README

---

resotocore/core/cli/command.py
resotocore/core/cli/model.py
resotocore/tests/core/cli/command_test.py
resotocore/tox.ini

The value of a tag update can back-reference attributes from a resource in the same way as the `format` command.
- Fixes #595

[resotocore][feat] Tag update allows format like templating

---

resotolib/resotolib/graph/__init__.py
resotoworker/resotoworker/resotocore.py

`resotoworker` always understood the `--debug-dump-json` arg. However the NDJSON of the graph was generated as part of the export generator. As such if the export from worker to core aborted halfway for whatever reason (network failure, OOM kill of the `resotocore` import process, etc.) only half the json would be written. When debugging these kinds of issues it's tedious having to re-run the entire collect.
With this change the worker can now be started with `--debug-dump-json` which generates the json model and ndjson graph files before sending them to the core. This way if something breaks during the import and adjustments have to be 
made on the core side, the already collected graph and model can be taken and manually sent to the core api like so:
Look for the lines saying:
```
... …
```

[resotoworker] Create tempfile with graph ndjson before sending to core

---

resotocore/core/dependencies.py

It uses the term `Job` which confuses people with resoto jobs.

[resotocore][fix] Silence apscheduler logs

---

resotolib/resotolib/graph/graph_extensions.py
resotolib/test/test_graph_extensions.py

Walk a loosely connected graph by dependent edges.
Emit list of nodes in generations, so one generation of nodes always only depend on previous generations of nodes.
- Fixes #XXXX

[resotolib][feat] Implement a dependent node iterator

---

resotocore/core/cli/command.py
resotocore/tests/core/cli/command_test.py

```
query xxxx | jq ./reported
```

[resotocore][fix] Allow absolute path in jq

---

tools/release_notes.py

Adds truncate marker to generated release notes, for better list view in Docusaurus.
**Note:** This marker should be moved above the changelog in cases where additional content is added above the auto-generated list of commits.

[github][fix] Add truncate marker to generated release notes

---

resotocore/core/model/db_updater.py

Instead of throwing `queue.Empty`, raise a more meaningful exception.

[resotocore][fix] Improve error message in case of timeout.

---

resotolib/resotolib/graph/__init__.py
resotoworker/resotoworker/resotocore.py

Introduces an arg `--tempdir` to `resotoworker` that allows specifying a directory to create temporary files in. This is useful in environments with large graphs where there is no swap and `/tmp` resides on a RAM backed `tmpfs`. This might be a situation where one would want to specify an alternative temp location on disk like `/var/tmp` or something custom.

[resotolib/resotoworker][feat] Allow specifying the directory to create temp files in

---

resotocore/core/cli/cli.py
resotocore/core/cli/command.py
resotocore/tests/core/cli/cli_test.py

The edge type can be either defined as an argument or as env var.
The argument takes always precedence over the env var.

[resotocore][feat] successors,predecessors,ancestors, descendants useedge_type from env

---

resotocore/core/cli/cli.py
resotocore/core/db/arango_query.py
resotocore/tests/core/cli/command_test.py
resotocore/tests/core/db/graphdb_test.py

Queries that use the same variable in different aggregation functions did not work properly.
```
> query is(instance) | aggregate sum(1) as count,  sum(instance_cores) as cores, sum(instance_memory) as memory, max(instance_memory) as max_mem
```

[resotocore][fix] Fix aggregation functions using the same variable

---

plugins/gcp/resoto_plugin_gcp/collector.py
plugins/gcp/resoto_plugin_gcp/resources.py

Adding a GKE cluster resource with collector to the GCP plugin. This allows to collect `gke_clusters`. 
Please note that we are not collecting GKE nodepools yet and therefore do not link any instances.
```
> query is(gcp_gke_cluster) | head 3
kind=gcp_gke_cluster, id=b1256ccc4e044930b78633db406ccbec65792471847f418e979667415d30aa23, name=us-east1-fast-demo-9ccc7f42-gke, age=8mo23d, cloud=gcp, account=acme-labs
kind=gcp_gke_cluster, id=1ccc7052286042049a861bdd7afbe73cd75e0649f6e8477d9c30ec3744051e42, name=test-cluster-one, age=4mo25d, cloud=gcp, account=acme-labs
kind=gcp_gke_cluster, id=f0a9caae11dd416d961814188af5e8198c4b5714746e424ca6abff3204706042, name=marv-private-terraform-test-2, age=6d12h, cloud=gcp, account=acme-labs
```
The GCP plugin ships with practically no tests. Manual tests …

[plugin gcp][feat] Add GKE clusters resource

---

resotocore/core/console_renderer.py

Examples in help use code blocks, which are rendered via pygments.
The default style is very hard to read on terminals with less than 256 colors.
This change uses the `native` theme, which seem to deliver better results.
See: https://github.com/someengineering/resoto/issues/652 for examples.
- Fixes #652

[resotocore][fix] Use color theme that is better readable

---

resotoshell/resotoshell/__main__.py

Commands were encoded with the system defined encoding, but the server expected utf8.
- Fixes #663

[resotoshell][fix] Send command utf8 encoded

---

resotoshell/resotoshell/__main__.py

The cache directive is only available in python 3.9 or later.

[resotoshell][fix] Use lru_cache instead of cache

---

resotocore/resotocore/query/model.py
resotocore/tests/resotocore/query/model_test.py

```
a<1 {test: <-[1:]- is(account)}" 
```
`test` will be interpreted relative to the current section.
By default this will yield: `/reported.test` - people need to prefix the merge path with a slash if it should be on root level.

[resotocore][fix] The merge path should be interpreted relative to the defined section

---

resotocore/resotocore/query/query_parser.py
resotocore/tests/resotocore/query/query_parser_test.py

Parens in `not` are now optional.
Now you can write this:
```js
> search not(not is(instance) and not /ancestors.account.reported.name=~eng)
```

[resotocore][feat] search: make parens in not optional

---

resotocore/resotocore/model/graph_access.py
resotocore/resotocore/model/resolve_in_graph.py

Currently, the account node lists the current node under `/ancestors` as the account node.

[resotocore][fix] ancestors should not hold a reference to the current node

---

resotocore/resotocore/__main__.py
resotocore/resotocore/analytics/recurrent_events.py

Only sent this event after one hour. Installations that will start and stop under one hour will not send this event.

[resotocore][fix] Send ModelInfo event after one hour uptime

---

plugins/aws/resoto_plugin_aws/accountcollector.py
plugins/aws/resoto_plugin_aws/resources.py
plugins/gcp/resoto_plugin_gcp/collector.py
plugins/k8s/resoto_plugin_k8s/resources/common.py
resotolib/resotolib/baseresources.py

Add support for Cloudformation Stack Sets. This is part 1 of a 2 part PR. Part 2 is for the commented code that requires support in resotocore for creating edges between accounts, after all accounts have been collected. We could already implement this on the collector level in the form of a deferred_connection but that would only work for `--graph-merge-kind cloud` and break if a user collects two different accounts on two different workers.
- Fixes #651

[plugins/aws][feat] Add support for Cloudformation Stack Sets

---

resotocore/resotocore/db/async_arangodb.py
resotocore/tests/resotocore/web/auth_test.py

Edges are deferred when the nodes are not visited yet.
In the end, a final check is required to ensure both nodes have been visited.

[resotocore][fix] Only render edges where the nodes have been visited

---

resotocore/resotocore/cli/cli.py
resotocore/resotocore/db/arango_query.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/query/model.py
resotocore/resotocore/query/query_parser.py
resotocore/tests/resotocore/cli/cli_test.py
resotocore/tests/resotocore/query/__init__.py
resotocore/tests/resotocore/query/model_test.py
resotocore/tests/resotocore/query/query_parser_test.py

This PR introduces 2 changes to the search syntax:
- limit now allows defining two values: offset and limit
if only one value is provided, the offset defaults to 0
- the keyword `reversed` can be used after the limit, which will reverse the limited sorted result.
All subsequent head/tail combinations are now computed into a single limit with offset and length.
In case the result is sorted, the sort order is reserved for `tail`, limited, and reversed again.
If no sort order is defined, a sort is injected (global identifier).
- Fixes #683 

[resotocore][fix] Multiple head/tail commands can be combined

---

resotocore/resotocore/config/config_handler_service.py
resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py
resotocore/resotocore/web/content_renderer.py

Config is only ipdayted if changed - also the event is also only emitted in this case.
The revision number comes as part of GET/PUT/PATCH requests.

[resotocore][feat] Only update config on change + revision header

---

.github/workflows/docker-build.yml
resotocore/resotocore/static/api-doc.yaml

Writes a modified version of the resotocore OpenAPI YAML spec to the [someengineering/resoto.com](https://github.com/someengineering/resoto.com) repository upon each release.  The modifications are necessary so that the server path appears as expected on the website API docs. (I have manually copied and committed the current state of the spec to the resoto.com repo already.)
Also removes the description, which does not add any additional information not provided by the title.

[ci][chore] Commit resotocore API YAML to website repo on release

---

plugins/k8s/resoto_plugin_k8s/resources/__init__.py
plugins/k8s/resoto_plugin_k8s/resources/horizontal_pod_autoscaler.py

This adds horizontal_pod_autoscaler as a k8s resource, using the [V1 autoscaling API](https://github.com/kubernetes-client/python/blob/master/kubernetes/docs/V1HorizontalPodAutoscaler.md). (V2 is the latest version but stable only as of 1.23, so V1 is better for broader compatibility IMO.)
Current fields are `max_replicas` and `min_replicas`.

k8s plugin: Add horizontal_pod_autoscaler type

---

plugins/k8s/README.md
plugins/k8s/resoto_plugin_k8s/__init__.py
plugins/k8s/resoto_plugin_k8s/utils.py
plugins/k8s/test/test_args.py

This avoids the need to specify every context in order to have it imported.
Added a new argument rather than a magic value like `all` for `--k8s-context` to avoid any potential conflicts.
- N/A ~Document new or updated functionality (someengineering/resoto.com#XXXX)~

[plugins/k8s][feat] Add argument to collect all contexts in config file

---

resotocore/resotocore/cli/__init__.py
resotocore/resotocore/cli/cli.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/query/template_expander.py
resotocore/resotocore/task/task_handler.py
resotocore/tests/resotocore/cli/cli_test.py
resotocore/tests/resotocore/query/template_expander_test.py

While experimenting with AliasTemplates I realized a couple of possible improvements:
- The analytics event should show commands and aliases separately
- Jq needs an option to get rid  of preprocessing
- More clever templates might be required (something like: in 3 hours)
- Replace parameters are case insensitive   
- Fixes #XXXX

[resotocore][feat] Improve AliasTemplate handling

---

resotocore/resotocore/cli/command.py
resotocore/tests/resotocore/cli/command_test.py

Removed the restriction to always provide the tag values when updating tags.

[resotocore][feat] Support tagging by key only

---

.github/workflows/docker-build.yml
tools/release_notes.py

Husky changed the env var to disable/skip hooks in a recent release, and this is causing the release note generation part of the CI to fail.
(Going to manually create the release shortly.)

[ci][chore] Fix release CI

---

resotocore/requirements-dev.txt
resotolib/requirements-test.txt

Fix CI by updating black from 22.1.0 to 22.3.0
https://github.com/psf/black/issues/2964

[resotocore/resotolib][chore] Bump black==22.3.0

---

resotoworker/resotoworker/cleanup.py

Log the notification "not running cleanup because cleanup is not turned on" as debug instead of error

[resotoworker][fix] log turned off cleanup as debug not error

---

resotolib/resotolib/core/__init__.py
resotometrics/resotometrics/__main__.py
resotoworker/resotoworker/__main__.py

Adds a wait function at resotoworker/resotometrics startup to wait for resotocore to be online. This way esp. in a Docker environment the user isn't greeted with hundreds of exceptions while the core is starting up.

[resotoworker/resotometrics][feat] Wait for the core to be online

---

resotocore/resotocore/__main__.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/dependencies.py
resotocore/resotocore/parse_util.py
resotocore/tests/resotocore/dependencies_test.py

Allows defining simple and list override parameters.
Example:
```
resotocore --override resotocore.api.web_hosts=localhost,case resotocore.api.web_port=12345
```
Would bind to localhost and case with port 12345

[resotocore][fix] Allow simple and list values as override parameters

---

resotocore/resotocore/cli/cli.py
resotocore/resotocore/cli/command.py

- help does not show placeholders and aliases any longer via `help`
- `help placeholders` shows available placeholders
- `help <cmd>` always shows available aliases or the proper command name
- all info messages have a dot.
- Fixes #XXXX

[resotocore][fix] Improve help

---

resotocore/resotocore/__main__.py
resotocore/resotocore/core_config.py
resotocore/resotocore/db/arangodb_extensions.py
resotocore/resotocore/db/db_access.py
resotocore/resotocore/model/db_updater.py
resotocore/resotocore/web/certificate_handler.py
resotocore/tests/resotocore/core_config_test.py
resotocore/tests/resotocore/web/certificate_handler_test.py

Make the ca bundle available to the request context of arangodb client. 
This allows creating/securing the access to arangodb.
Since the certificate is stored inside the database - an untrusted call is required first.

[resotocore][fix] Allow secure access to arangodb

---

.github/workflows/docker-build.yml
tools/release_notes.py

Remove all-in-one Docker image from release notes going forward.

[ci][chore] remove individual Docker images from generated release notes

---

resotocore/resotocore/query/query_parser.py
resotocore/tests/resotocore/query/query_parser_test.py

Reduce the effect of `not` to the next simple term expression.
Example with 2 terms `<a>` and `<b>`:
```
search not <a> and <b>
```
Before:
interpreted as `not( <a> and <b> )`
After:
interpreted as `(not <a>) and <b>`

[resotocore][fix] Not should affect only the next simple term

---

.github/workflows/docker-build.yml
Dockerfile
Dockerfile.resh
Dockerfile.resotobase
Dockerfile.resotocore
Dockerfile.resotometrics
Dockerfile.resotoshell
Dockerfile.resotoworker
docker-compose.yaml
dockerV2/resh-shim

Add a `someengineering/resh` container that uses resh as its entrypoint.

[docker][feat] Add someengineering/resh container

---

resotocore/tools/render_dot.py

Added the graph rendering script instructions in the readme

[resoto][docs] Add an example of the rendering script usage

---

resotocore/resotocore/__main__.py
resotocore/resotocore/web/certificate_handler.py

On some OS the tmp folder is cleaned for files that are not touched.
This PR will rewrite the ca cert bundle periodically that is used for requests done by the requests library.

[resotocore][fix] write ca bundle periodically to tmp

---

docker-compose.yaml

With this change the workflow is this:
1) `docker-compose up` to start the Resoto stack
1) `docker run resotoshell` to start resh 

[docker][fix] Allow docker-compose run resotoshell

---

resotolib/resotolib/utils.py
resotolib/test/test_utils.py
resotoshell/resotoshell/shell.py

Compare actual changes for tmpfs filesystems where ctime==mtime.

[resotoshell][fix] Compare config checksum instead of ctime/mtime

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/config.py
plugins/aws/test/test_config.py
plugins/gcp/resoto_plugin_gcp/collector.py

Fix AWS `scrape_exclude_account` default and update GCP severity for machine and instance types with no region removal.

[plugins][fix] Fix aws excluded accounts default and update gcp severity

---

resotoshell/resotoshell/shell.py

Check resotocore returned filename for invalid path element. If the filename returned by resotocore includes a `/` character abort the download.

[resotoshell][feat] Check resotocore returned filename for invalid path element

---

resotolib/resotolib/config.py
resotolib/resotolib/signal.py

Close FDs more targeted so restarts on systems with 1 billion allowed open fds don't take several minutes to complete.
Also increase severity for config change based restarts from debug to info so the user knows why a component was restarted based on a config change.

[resotolib][fix] close fds more targeted during restart

---

plugins/cleanup_aws_alarms/setup.py
plugins/cleanup_aws_loadbalancers/setup.py
plugins/cleanup_aws_vpcs/setup.py
plugins/cleanup_expired/setup.py
plugins/cleanup_untagged/setup.py
plugins/cleanup_volumes/setup.py
plugins/example_collector/setup.py

Use of `_` in package name is discouraged. This replaces it with `-` in source which is what pip/pypi does automatically anyways.

[plugins][fix] Remove _ from plugin package names

---

resotoshell/resotoshell/__main__.py

Detect if stdin is a tty and read from stdin if not.
This allows:
```sh
echo "search is(instance) limit 3" | resh
```
without providing extra options.

[resotoshell][feat] select mode if stdin is not a tty

---

resotolib/resotolib/graph/__init__.py

Use debug instead of error log severity for messages not relevant to the user.

[resotolib][fix] Use debug instead of error log severity

---

resotoshell/resotoshell/__main__.py

Resotoshell now quits when no PSK is supplied but core was started with a PSK

[resotoshell][fix] handle wrong PSK

---

docker-compose.yaml
resotolib/resotolib/core/actions.py
resotolib/resotolib/core/events.py
resotolib/resotolib/core/tasks.py

Changes the severity of auto-recovering message bus errors and info messages.
Anything that is not helpful to the user of where the user can't really do anything to fix the situation shouldn't be exposed as an error and instead silently recover.
Also allows setting RESOTO_VERBOSE as an env and propagate to each container.

[resotolib][fix] Change severity of auto-recovering info and error messages

---

plugins/aws/resoto_plugin_aws/resources.py
plugins/digitalocean/resoto_plugin_digitalocean/resources.py
plugins/gcp/resoto_plugin_gcp/resources.py
plugins/slack/resoto_plugin_slack/resources.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/model/model.py
resotocore/resotocore/model/model_handler.py
resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/db/graphdb_test.py
resotocore/tests/resotocore/model/__init__.py
resotocore/tests/resotocore/model/model_test.py
resotolib/resotolib/baseresources.py
resotolib/resotolib/core/model_export.py
resotolib/test/core/model_export_test.py

The following changes are included in this PR:
- option to define successors for a given kind in the model
- store and retrieve successor information
- allow successors to be defined in dataclass and export it
- define successors for `aws`, `gcp` and `digitalocean`  resources if applicable.
- add `successors` and `predecessors` to the `kind` output
- add dependency edges in the uml generation

[resoto][feat] Add possible successors to the model

---

resotolib/resotolib/config.py

Handle failure to save config after load gracefully. This could have multiple harmless causes like the user downgrading resoto. Instead of aborting just log an error so the user can manually fix the config.

[resotolib][fix] Handle failure to save config after load gracefully

---

Dockerfile
Dockerfile.resotobase

Use `nano` instead of `vi` as default config editor in Docker image. 🥹🙂

[docker][chore] Use `nano` as default editor in Docker 🤷

---

plugins/digitalocean/resoto_plugin_digitalocean/collector.py
plugins/digitalocean/test/test_collector.py

Changed the DO plugin: droplets use gigabytes instead of megabytes.
- Fixes #XXXX

[plugins][digitalocean] Use Gb instead of Mb for DO instances

---

resotocore/resotocore/query/query_parser.py
resotocore/tests/resotocore/query/query_parser_test.py

A query like `search is(instance) and sort instance_cores` was read into `search is(instance) and sort in "stance_cores"`.
For the `in` and `not in` operators at least one space is now required.

[resotocore][fix] Make query parser more strict

---

tools/release_notes.py

Commits without associated PRs have `(#)` added to the generated release notes.

[ci][fix] Properly handle commits without associated PRs in release notes generator

---

resotocore/resotocore/query/query_parser.py
resotocore/tests/resotocore/query/query_parser_test.py

```bash
search all | tail -1 | successors
```
Did not execute and threw an errror. Now this search is possible.

[resotocore][fix] search navigation after tail

---

resotolib/resotolib/core/__init__.py

Remove trailing slash in resotocore_uri

[resotolib][fix] Remove trailing slash in resotocore_uri

---

.github/workflows/docker-build.yml

- Create prereleases instead of releases on GitHub for non-stable versions
- Only generate changelog and commit to website repo for stable versions

[ci][chore] Create preleases for non-stable versions

---

plugins/onprem/requirements.txt

Bump paramiko 2.11.0
Fixes
```
python3.10/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
"class": algorithms.Blowfish,
```

[plugins/onprem][chore] Bump paramiko 2.11.0

---

resotocore/resotocore/core_config.py
resotocore/tests/resotocore/cli/command_test.py

As I was editing the Discord how-to guide, I noticed that the current Discord alerts look a little unpolished:
We should allow for users to omit the alert message entirely if they only want to specify the title. Also, the message text should be contained within the embed object for a cleaner look (and also so that the message doesn't look like a title).

[resotocore][fix] Allow for empty Discord alert message & move to embed description

---

resotolib/resotolib/config.py

Fixes a regression introduced with the attrs migration. Dataclasses fields() would accept classes or class instances. Attrs expects a class.

[resotolib][fix] Pass class to fields()

---

resotocore/requirements.txt
resotocore/resotocore/cli/cli.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/dependencies.py
resotocore/resotocore/task/scheduler.py
resotolib/requirements.txt
resotolib/resotolib/utils.py
resotolib/test/test_utils.py

Migrate to zoneinfo
Fixes
```
/Users/lukas/repo/resoto/venv-pypy/lib/pypy3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
return tzinfo.localize(dt)
```
Also adds a dependency to tzdata because of https://docs.python.org/3/library/zoneinfo.html#data-sources
Normal Linux distributions should come with a timezone db, but this prepares it to work on systems that don't come with one, and more importantly also makes it work in minimal container environments that don't come with a system timezone db.
By submitting this pull request, I agree to …

[resotocore][fix] Migrate to zoneinfo

---

resotocore/resotocore/task/scheduler.py

Ignore
```
/Users/lukas/repo/resoto/venv-pypy/lib/pypy3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
```
generated by the use of new Python 3.9+ ZoneInfo timezones. The warning is generated in the external APScheduler dependency.

[resotocore][fix] Ignore PyTz deprecation shim warnings

---

resotolib/resotolib/durations.py

Allow plural for month in duration strings

[resotolib][fix] allow plural for month in duration strings

---

plugins/aws/resoto_plugin_aws/resource/autoscaling.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/resource/elbv2.py
plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/ec2_test.py
plugins/aws/test/resources/files/ec2/describe-addresses.json
plugins/aws/test/resources/files/ec2/describe-instances.json
plugins/aws/test/resources/files/ec2/describe-internet-gateways.json
plugins/aws/test/resources/files/ec2/describe-nat-gateways.json
plugins/aws/test/resources/files/ec2/describe-network-interfaces.json
plugins/aws/test/resources/files/ec2/describe-route-tables.json
plugins/aws/test/resources/files/ec2/describe-security-groups.json
plugins/aws/test/resources/files/ec2/describe-snapshots.json
plugins/aws/test/resources/files/ec2/describe-subnets.json
plugins/aws/test/resources/files/ec2/describe-vpc-endpoints.json
plugins/aws/test/resources/files/ec2/describe-vpc-peering-connections.json
plugins/aws/test/resources/files/ec2/describe-vpcs.json
plugins/aws/tools/model_gen.py
resotolib/resotolib/baseresources.py
resotolib/resotolib/json_bender.py
resotolib/test/json_bender_test.py

Model, mapping and test for:
- elastic ips
- network interfaces
- vpc
- subnets
- security groups
- nat gateways
- internal gateways
- snapshots
- vpc peering connections
- vpc endpoints
- route tables
- Fixes #XXXX

[aws][feat] Define remaining AWS EC2 resources 

---

resotocore/resotocore/config/config_handler_service.py
resotocore/resotocore/model/model.py
resotocore/tests/resotocore/model/model_test.py

Duration values get normalized by default to SI base unit, which is seconds.
This PR adapts this behaviour and will not normalize configuration values.

[resotocore][fix] Do not normalize configuration values

---

plugins/aws/resoto_plugin_aws/resources.py
resotolib/resotolib/baseresources.py

Remove access_key_status and redundant base resource.
Fixes tagging and cleanup for lambdas.

[plugins/aws][fix] Remove access_key_status and redundant base resource

---

plugins/aws/resoto_plugin_aws/resource/elasticbeanstalk.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/elasticbeanstalk_test.py
plugins/aws/test/resources/files/elasticbeanstalk/describe-applications.json
plugins/aws/test/resources/files/elasticbeanstalk/describe-environment-resources__SomeId.json
plugins/aws/test/resources/files/elasticbeanstalk/describe-environments.json
plugins/aws/test/resources/files/elasticbeanstalk/list-tags-for-resource__SomeAppArn.json
plugins/aws/test/resources/files/elasticbeanstalk/list-tags-for-resource__SomeEnvArn.json
plugins/aws/tools/model_gen.py

- collect existing tags on Elasticbeanstalk Applications
- collect Environments of Applications (incl. existing tags)
- add edges from Environments to Applications
- collect Resources in Environments
- add edges from Resources to Environments
- tagging and deletion methods for Environments

 [plugins/aws][feat] Add support for Elastic Beanstalk Application Environments and Resources

---

plugins/aws/resoto_plugin_aws/resources.py

**"filename"**: "plugins/aws/resoto_plugin_aws/resources.py"
**"warning_type"**: "Incompatible attribute type [8]",
**"warning_message"**: " Attribute `runtime` declared in class `AWSLambdaFunction` has type `str` but is used as type `None`.",
**"warning_line"**: 206
**"fix"**: add Optional types
- Fixes #XXXX

Incompatible attribute type

---

kubernetes/chart/Chart.yaml
kubernetes/chart/templates/resotormetrics/deployment.yaml
kubernetes/chart/templates/resotormetrics/serviceMonitor.yaml
kubernetes/chart/values.yaml

Signed-off-by: cebidhem <cebidhem@pm.me>
ServiceMonitors are the way to scrape metrics for users deploying Prometheus through the Operator (kube-prometheus-stack). 
If explicitly enabled by the user, this aims to create a service and a servicemonitor to scrape resoto metrics.
Comments have been added within the values.yaml file. If you feel this should be added somewhere else, please let me know.
- Fixes #1057

feat(helm): Adds a serviceMonitor and its service to scrape resoto metrics

---

resotocore/resotocore/model/model.py
resotocore/tests/resotocore/model/model_test.py

The existing model is not checked for the model update.
The only check we will do: the final model needs to be sound and should not have any overlapping property paths with different types.

[resotocore][feat] Check the updated model not the update

---

plugins/aws/test/collector_test.py
plugins/aws/test/resources/files/dynamodb/describe-table__test1.json
plugins/aws/test/resources/files/kms/describe-key__bdc0c890.json

KMS Keys collected in the test run had a mixup regarding id/arn. This led to volatile behaviour in counting edges to those keys. The two test keys had different ids but same arn.

[plugins/aws][fix] Fix edge count with unique keys

---

resotolib/resotolib/baseresources.py

Make DNSZone.id() part of DNSRecord and DNSRecordSet _keys()
Fixes duplicate IDs

[plugins/aws][fix] Make DNSZone.id() part of DNSRecord and DNSRecordSet _keys()

---

plugins/aws/resoto_plugin_aws/config.py

[plugins/aws][fix] Migrate the db config on config class change

---

plugins/aws/resoto_plugin_aws/resource/athena.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/resource/kms.py
plugins/aws/resoto_plugin_aws/resource/rds.py
plugins/aws/test/resources/kms_test.py

- Add edge between RDS Instances and KMS Keys
- Kms Keys can be identified by a variety of references (Id, Arn, ...). This introduces a normalisation method that leads back to the actual key id, making it simpler to add edges to Keys

[plugins/aws][feat] Normalise KMS Key IDs and add edges

---

resotolib/resotolib/json.py

Using a string representation of timedelta makes it hard for anybody who is using our API, while the number is much simpler. Use the number as default representation and allow to read string or number.

[resotocore][fix] Use default timedelta representation

---

plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/resoto_plugin_aws/resource/athena.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/cloudwatch.py
plugins/aws/resoto_plugin_aws/resource/dynamodb.py
plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/aws/resoto_plugin_aws/resource/eks.py
plugins/aws/resoto_plugin_aws/resource/elasticache.py
plugins/aws/resoto_plugin_aws/resource/elasticbeanstalk.py
plugins/aws/resoto_plugin_aws/resource/elb.py
plugins/aws/resoto_plugin_aws/resource/elbv2.py
plugins/aws/resoto_plugin_aws/resource/iam.py
plugins/aws/resoto_plugin_aws/resource/kinesis.py
plugins/aws/resoto_plugin_aws/resource/kms.py
plugins/aws/resoto_plugin_aws/resource/lambda_.py
plugins/aws/resoto_plugin_aws/resource/pricing.py
plugins/aws/resoto_plugin_aws/resource/rds.py
plugins/aws/resoto_plugin_aws/resource/route53.py
plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/resoto_plugin_aws/resource/service_quotas.py
plugins/aws/resoto_plugin_aws/resource/sqs.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/__init__.py
plugins/aws/test/resources/s3_test.py

This creates a list of all API calls that are made. This way it should be possible to create an IAM policy document.
Example:
```json
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "AllowResotoAccess",
"Effect": "Allow",
"Action": [
"athena:GetDataCatalog",
"athena:GetWorkGroup",
"athena:ListDataCatalogs",
"athena:ListTagsForResource",
"athena:ListWorkGroups",
"autoscaling:DescribeAutoScalingGroups",
"cloudformation:DescribeStacks",
"cloudformation:ListStackSets",
"cloudwatch:DescribeAlarms",
"dynamodb:DescribeGlobalTable",
"dynamodb:DescribeTable",
"dynamodb:ListGlobalTables",
"dynamodb:ListTables",
"dynamodb:ListTagsOfResource",
"ec2:DescribeAddresses",
"ec2:DescribeInstanceTypes",
"ec2:DescribeInstances",
"ec2:DescribeInternetGateways",
"ec2:DescribeKeyPairs", …
```

[aws][feat] Return all API's that get called during collect

---

resotocore/setup.py

If pypy is detected, jupyterlite won't generate assets instead of failing with a cloudpickle error. cloudpickle does not support pypy runtime.

[resotocore][fix] Do not run jupyterlite build when in pypy

---

.github/workflows/docker-build.yml
tools/release_notes.py

- Release notes generator doesn't properly process commit messages without an associated PR
- Helm chart `version` and `appVersion` need to be updated on release

[ci][chore] Fix release notes generator when no PR, bump helm-charts versions

---

.github/workflows/docker-build.yml
tools/release_notes.py

someengineering/resoto.com#350 adds docs versioning.
- Latest release version is now tracked locally in the [someengineering/resoto.com](https://github.com/someengineering/resoto.com) repo, so `latestRelease.json` needs to be updated with the tag and release notes link when publishing a new stable release
- API docs for latest stable release _and_ main/edge are now maintained separately in the [someengineering/resoto.com](https://github.com/someengineering/resoto.com) repo, so these two files both need to be updated as appropriate (main/edge version on every commit)
This PR also fixes these issues:
- API docs were not being updated at all
- We weren't publishing release notes for prereleases, which would result in a weird empty "Release Notes" section with no link on GitHub
- Remove `v` …

[ci][chore] Update CI for versioned docs

---

plugins/aws/resoto_plugin_aws/resource/apigateway.py
plugins/aws/resoto_plugin_aws/resource/athena.py
plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/ecs.py
plugins/aws/resoto_plugin_aws/resource/redshift.py
plugins/aws/resoto_plugin_aws/resource/s3.py
plugins/aws/test/resources/ecs_test.py
plugins/aws/test/resources/files/ecs/describe-capacity-providers__sampleCapacityProvider_TAGS.json

Introduces
- a method on `AwsResource` to construct the ARN of a resource instance.
- a static method on `AwsResource` to extract the ID from a given ARN

[aws] Add methods to handle missing ARNs/IDs

---

resotolib/resotolib/proc.py

Resoto used to work on Windows, but over time this compatibility got forgotten. This quick fix makes it so that `resh` starts on Windows again. All the code that uses these two modules already checks for the OS, so is prepared for the modules to be missing. Worker and Metrics also seem to work, though I didn't test all plugins and config hot-reload might not work. Core fails with a jq lib compile error. But the main thing was to get `resh` working again.

[resotolib][fix] Make resotolib win32 compatible again

---

resotocore/resotocore/core_config.py
resotocore/tests/resotocore/cli/command_test.py

Display no more than 25 result items and show note if the results have been truncated.
Issue created with 5 result items:
Issue created with > 25 result items:

[resotocore][fix] Display no more than 25 result items in Jira issue

---

resotolib/resotolib/graph/__init__.py

There could be multiple paths to a node which would currently result in them being checked multiple times.

[resotolib][fix] When searching for parent nodes only check them once

---

.github/workflows/docker-build.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

[github][fix] Update use of deprecated `set-output`

---

resotocore/resotocore/config/__init__.py
resotocore/resotocore/config/config_handler_service.py
resotocore/resotocore/config/core_config_handler.py
resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/config/config_handler_service_test.py
resotocore/tests/resotocore/config/core_config_handler_test.py

Define `dry_run=true` on put and patch operations to perform the requested change without changing the data.

[resotocore][feat] Config Service should allow testing updates using a dry run

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/db/async_arangodb.py
resotocore/resotocore/db/runningtaskdb.py
resotocore/resotocore/task/task_description.py
resotocore/resotocore/task/task_handler.py
resotocore/resotocore/util.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/db/runningtaskdb_test.py
resotocore/tests/resotocore/task/task_handler_test.py
resotocore/tests/resotocore/util_test.py

With this PR workflow runs are maintained in the database after the task is finished.
The `workflows` command is adapted to filter the list of past runs:
```bash
> workflows history
collect:
count: 264
last_run: '2022-11-04T12:33:32Z'
runs_with_errors: 1
average_duration: 18s
collect_and_cleanup:
count: 3416
last_run: '2022-11-04T12:00:00Z'
runs_with_errors: 0
average_duration: 34s
> workflows history collect --started-after 2022-11-03 --started-before 2022-11-05 --has-errors --limit 10
id: 037f23c6-5c1b-11ed-bb8b-dad780437c53
task_started_at: '2022-11-04T08:31:01Z'
duration: 87.786464
errors: 19
> workflows log 037f23c6-5c1b-11ed-bb8b-dad780437c53
2022-11-04T08:31:01Z: collect: collect: aws: 882347060974: collect-global: in progress
[aws:123456789] Access Denied to aws_account 123456789 …
```

[resotocore][feat] Maintain the list of workflow tasks

---

plugins/aws/resoto_plugin_aws/resource/route53.py

This includes the set identifier in the `_keys()` method, which is used to create the unique ID.
API response for location balanced RRSets:
```
{
"Name": "hello-rr.example.com.",
"Type": "CNAME",
"SetIdentifier": "eu-central",
"Weight": 33,
"TTL": 172800,
"ResourceRecords": [
{
"Value": "hello.eu-central.example.com."
}
]
},
{
"Name": "hello-rr.example.com.",
"Type": "CNAME",
"SetIdentifier": "us-east",
"Weight": 33,
"TTL": 172800,
"ResourceRecords": [
{
"Value": "hello.us-east.example.com."
}
]
},
{
"Name": "hello-rr.example.com.",
"Type": "CNAME",
"SetIdentifier": "us-west",
"Weight": 33,
"TTL": 172800,
"ResourceRecords": [
{
"Value": "hello.us-west.example.com."
}
]
},
```

[plugins/aws][fix] include set identifier in _keys() for RRSets

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/collector.py
plugins/aws/test/collector_test.py

Update of the AWS collector:
- Handle exceptions on a kind level instead of aborting the entire region when an individual kind is not allowed to be collected.
- Update progress to use account name & id instead of just the id

[plugins/aws][fix] Exception handling for individual resource kinds and rename of progress prefix

---

resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py
resotocore/resotocore/web/directives.py
resotocore/resotocore/web/tsdb.py

- ViaResoto Header defines if the response is created by Resoto or downstream
- 404 if tsdb is not configured
- 502 if tsdb is not reachable

[resotocore][feat] Improve TSDB proxy behaviour

---

resotoworker/requirements.txt
resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/config.py
resotoworker/resotoworker/pluginloader.py

- Expose list of loaded collectors on a `/info` endpoint
- Fix config reload bug
Example output:
```
$ curl -k https://localhost:9956/info | jq .
{
"active_collectors": [
"aws"
],
"all_collectors": [
"aws",
"gcp",
"slack",
"onelogin",
"k8s",
"onprem",
"github",
"dockerhub",
"random",
"example",
"vsphere",
"digitalocean"
]
}
```
This is so that the list of collectors no longer has to be hard coded in https://github.com/someengineering/resoto.com/blob/main/tools/export_model_images.py#L13

[resotoworker][feat] Expose list of loaded collectors

---

resotocore/.pylintrc
resotocore/resotocore/analytics/__init__.py
resotocore/resotocore/cli/cli.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/core_config.py
resotocore/resotocore/db/arango_query.py
resotocore/resotocore/db/db_access.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/db/model.py
resotocore/resotocore/model/db_updater.py
resotocore/resotocore/query/model.py
resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/util.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/cli/cli_test.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/core_config_test.py
resotocore/tests/resotocore/db/graphdb_test.py
resotocore/tests/resotocore/web/api_test.py

When a new graph snapshot is delivered, Resoto computes the list of changes based on the current state of the internal graph. The changes get applied to the snapshot.
This PR will store the changes as own entity in a separate data collection.
This data collection only maintains the list of changes of a defined time (14 days by default).
The changes can be accessed via the API:
- `/graph/{graph_id}/search/history/list` to search and return the history nodes
- `/graph/{graph_id}/search/history/aggregate` to search and aggregate the history nodes
The changes can be accessed via the CLI:
```shell
> history | count /change
node_deleted: 32
node_updated: 208
node_created: 518
total matched: 758
total unmatched: 0
> history --after 2022-01-01T03:00:00Z --before 2022-01-02T06:00:00Z …
```

[resotocore][feat] Maintain history of nodes and make it available via CLI/API

---

plugins/aws_k8s/resoto_plugin_aws_k8s/__init__.py
plugins/aws_k8s/test/test_collector.py
plugins/digitalocean_k8s/resoto_plugin_digitalocean_k8s/__init__.py
plugins/k8s/resoto_plugin_k8s/resources.py

Plugin now supports the following third party/deferred edges:
- `kubernetes_cluster <-> aws_eks_cluster`
- `kubernetes_persistent_volume <-> aws_ec2_volume`
- `kubernetes_node <-> aws_eks_nodegroup`,
- `kubernetes_node <-> aws_ec2_instance`,
- `kubernetes_service <-> aws_elb`
- part of #943 

[plugins][feat] support deferred edges between kubernetes and AWS

---

plugins/aws/resoto_plugin_aws/collector.py

Ignore NoSuchEntity in get-account-password-policy

[plugins/aws][fix] Ignore NoSuchEntity in get-account-password-policy

---

plugins/aws/resoto_plugin_aws/__init__.py
resotocore/resotocore/cli/cli.py

```shell
> search is(aws_ec2_instance)  | aws ec2 stop-instances --instance-ids {id}
```
`instance-ids` has to be of type list, even if it is called for a single instance.
Coerce to correct type based on the service model.

[aws][fix] Coerce to correct parameter type

---

resotolib/resotolib/proc.py
resotometrics/resotometrics/__main__.py
resotometrics/resotometrics/config.py
resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/config.py

Allow worker and metrics to start webserver without TLS
Also fixes an exception that can happen during config related reloads when there are no open files.

[resoto][fix] Allow worker and metrics to start webserver without TLS

---

resotolib/resotolib/asynchronous/web/ws_handler.py
resotolib/resotolib/core/actions.py
resotolib/resotolib/core/events.py
resotolib/resotolib/core/tasks.py

Turn on resotocore (server) based WebSocket pings
Also reduce interval for resotoworker and resotometrics initiated (client) pings from 30 to 20s
Websocket Pings can be initiated on the server as well as the client side. So far we only used client side pings. Since the UI has no explicit support for WebSocket client side pings this turns on server side pings in the core.
From [the Mozilla spec](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#pings_and_pongs_the_heartbeat_of_websockets):
```
At any point after the handshake, either the client or the server
can choose to send a ping to the other party. When the ping is
received, the recipient must send back a pong as soon as possible.
You can use this to make sure that the client is still connected, …
```

[resotocore][fix] Turn on WebSocket pings

---

plugins/aws/resoto_plugin_aws/collector.py

Add AwsCloudwatchMetricData API calls to collect api call list
Was currently missing, as AwsCloudwatchMetricData is not being collected directly, but as part of other resources like EBS volumes and databases.

[plugins/aws][fix] Add AwsCloudwatchMetricData API calls to collect api call list

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/db/arango_query.py
resotocore/resotocore/model/model.py
resotocore/resotocore/query/model.py
resotocore/resotocore/query/query_parser.py
resotocore/setup.cfg
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/db/arango_query_test.py
resotocore/tests/resotocore/db/graphdb_test.py
resotocore/tests/resotocore/model/model_test.py
resotocore/tests/resotocore/query/model_test.py
resotocore/tests/resotocore/query/query_parser_test.py
resotolib/resotolib/parse_util.py

This PR improves the capability of the Search DSL in Resoto. It allows to express patterns in objects inside arrays.
A simple predicate can look into arrays. Using the `[*]` it is possible to match any object inside an array.
If we have more than one predicate that we want to match inside an object inside an array, we can not simply use the `[*]` operator twice for each predicate, since each predicate matches on its own - there is no way to "bundle" 2 or more predicates. This PR introduces a context term, that allows exactly this.
Example using  an AWS security gateway (excerpt):
```json
{
"id": "sg-123",
"tags": {},
"name": "redirus-master",
"description": "redirus Master Security Group",
"group_ip_permissions": [
{
"from_port": 80,
"to_port": 80,
"ip_protocol": "tcp",
"ip_ranges": [
{ …
```

[resotocore][feat] Allow to search nested complex objects inside arrays

---

resotocore/resotocore/query/model.py
resotocore/tests/resotocore/query/model_test.py

Before:
```
> search is(aws_ec2_security_group) and name=launch-wizard-2 and group_ip_permissions[*].{ip_protocol = tcp and from_port >= 22 and to_port <= 22 and ip_ranges[*].{cidr_ip = "0.0.0.0/0"}} limit 1
kind=aws_ec2_security_group, id=sg-02b33740af7f83e95, name=launch-wizard-2, ip_protocol=[tcp], from_port=[22], to_port=[22], cidr_ip=[None], cidr_ip=[['0.0.0.0/0']], age=19d6h, cloud=aws, account=eng-production, region=us-west-2
```
It renders this output: `cidr_ip=[None]` which is coming from a non existing predicate path.
After:
```
> search is(aws_ec2_security_group) and name=launch-wizard-2 and group_ip_permissions[*].{ip_protocol = tcp and from_port >= 22 and to_port <= 22 and ip_ranges[*].{cidr_ip = "0.0.0.0/0"}} limit 1
kind=aws_ec2_security_group, id=sg-02b33740af7f83e95, …
```

[resotocore][fix] Ignore predicates in context for list rendering

---

resotocore/resotocore/cli/command.py
resotocore/tests/resotocore/cli/command_test.py

`kinds` currently shows all available complex kinds.
With this change, it only shows aggregate roots that are final - which represents the service kinds.

[resotocore][feat] kinds command shows aggregate roots

---

plugins/aws/resoto_plugin_aws/__init__.py

Since the aws client will not return a list for `call_single` any longer, we need to coerce the correct result type.
(Follow up after the aws client change).

[aws][fix] Fix usage of aws client

---

.github/workflows/docker-build.yml

Generate `docker-compose.yaml` referencing the appropriate tag upon the creation of each release, and add it as a release artifact.
This change will also need to be  cherrypicked back to the 2.4 branch, in case we tag a bugfix release in the future.

[ci][chore] Add docker-compose.yaml artifact to releases

---

resotolib/resotolib/core/actions.py

If the worker is not online for a couple of seconds, no user should care.
All jobs/tasks and workflows would need to wait for a certain amount of time for the worker to reappear.

[aws][feat] Do not unregister during shutdown

---

.github/workflows/docker-build.yml

@lloesche let's see if this resolves the issue fetching GH releases in the CI.

[ci][chore] Use GitHub CLI with access token instead of curl

---

plugins/aws/tools/awspolicygen/awspolicygen/gen.py
plugins/aws/tools/awspolicygen/awspolicygen/templates/resoto-role.template.in

Adding sagemaker has put the Role length over 10kb. This removes the Collect policy and replaces it with the AWS managed ReadOnlyAccess policy.

[fix][plugins/aws] Fix inline policy length

---

plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/cloudwatch.py
plugins/aws/test/collector_test.py
plugins/aws/test/resources/base_test.py

The same instance type defined in multiple regions could end up in the same global region, which is wrong.

[fix][aws] Fix duplicate instance types

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/cli/model.py
resotocore/resotocore/config/core_config_handler.py
resotocore/resotocore/core_config.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/core_config_test.py

Newly defined existing commands shipped with Resoto did not make it into user configuration.
This PR adds a migration to add non existent commands.
The commands that were defined had formatting errors and no description, which have been fixed as well.

[fix][resotocore] Fix predefined custom commands and make them available in existing configurations

---

resotocore/resotocore/core_config.py
resotocore/tests/resotocore/cli/command_test.py

This adds the `pagerduty` command that creates an alert in Pagerduty.
The result of a search is piped into `pagerduty` which will aggregate the resources by account and region.
`dedup_key` and `summary` has to be defined by the user in order to make sense out of that alert.
Example payload:
```yaml
payload:
summary: test
timestamp: '2023-02-10T15:15:24Z'
source: Resoto
severity: warning
component: Resoto
custom_details:
account_625596817853__region_us-east-1: 2
account_625596817853__region_us-east-2: 2
routing_key: kdjfhgkdfhgkdfjh
dedup_key: '123'
images:
- src: https://cdn.some.engineering/assets/resoto-logos/resoto-logo.svg
href: https://resoto.com/
alt: Resoto Home Page
links: []
event_action: trigger
client: Resoto Service
client_url: https://resoto.com
```
See rendered help page:
By …

[resotocore][feat] Add pagerduty notification command

---

resotolib/requirements.txt
resotolib/resotolib/graph/__init__.py
resotolib/resotolib/utils.py
resotolib/test/test_graph.py

`networkx` introduced `cached_property`s in 2.8.1 which blocked upgrading to the latest version.
This change unsets cached properties after the graph is exported and eliminates the references.
See: https://github.com/networkx/networkx/issues/6235

[resotolib][fix] Use latest networkx by unsetting cached properties

---

.github/CODEOWNERS
.github/workflows/check_pr_plugin_aws.yml
.github/workflows/docker-build.yml
.github/workflows/publish.yml

The AWS policy JSON cannot be fetched at build time from Netlify's build environment due to some networking/proxy issues on their side, so just write the policy JSON to the `someengineering/resoto.com` repo directly.
This also has the benefit of builds being able to work locally without an internet connection, though the downside is that we'll be maintaining two copies of the JSON (one on our DigitalOcean CDN and another on GitHub).
See also: someengineering/resoto.com#609

[ci][chore] Write AWS policy JSON to resoto.com repo

---

plugins/aws/resoto_plugin_aws/resource/cloudformation.py

AWS CloudFormation now requires that customers have the cloudformation:ListStacks permission when calling DescribeStacks without a target stack. This is in addition to the cloudformation:DescribeStacks permission that is already a requirement.

[plugins/aws][fix] Add new permissions for cloudformation stack listing

---

resotocore/resotocore/core_config.py
resotocore/tests/resotocore/cli/command_test.py

This PR changes the custom data send to Pagerduty. With this format Pagerduty is able to render the data visually more appealing in their webUI. Example:

[resotocore][chore] Improve Pagerduty details

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/resource/base.py
resotolib/resotolib/graph/__init__.py

The Graph class already emits a debug log message on add_edge. Right now for every edge there's two log messages containing exactly the same information.
This PR remove the duplicate log and skip deferred edge resolving in AWS since the new collector already does it on the account level. It also adjusts the node adding log to have the same format as edge adding messages.

[plugins/aws][fix] Remove duplicate log and skip deferred edge resoving in AWS

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/resoto_plugin_aws/configuration.py
plugins/aws/test/configuration_test.py

Boto sessions are memory hogs. No need to create more than one for the same access settings.

[aws][fix] Do not use a boto session per thread

---

resotocore/resotocore/web/api.py
resotocore/tests/resotocore/web/api_test.py

The raw_config which is used only on demand by overrides is not sent by default in using the API endpoint.
- Fixes #XXXX

[resotocore][fix] Do not send raw_config by default

---

resotolib/resotolib/config.py

Fixed a bug where specifying an env var that can't be resolved on the worker will cause a crash.
- Fixes #XXXX

[resotolib][fix] Fix config env vars resolving

---

resotocore/resotocore/config/config_handler_service.py

[resotocore][fix] Only use config roots to validate

---

resotocore/.pylintrc
resotocore/resotocore/model/json_schema.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/model/json_schema_test.py

When the content type `application/schema+json` is requested on the model endpoint,
json schema of our model is returned.
Test the schema:
1. Create the schema
2. Go to https://www.jsonschemavalidator.net and paste the schema
3. `search is(xxx) limit 1 | jq --no-rewrite .reported | format --json` and paste the json
The validator should report the pasted json as valid.

[resotocore][feat] Support json schema as model specification

---

resotoshell/resotoshell/shell.py

filename only allows ascii characters. aiohttp urlencodes the file name by default.

[resotoshell][fix] urldecode the file name

---

plugins/gcp/resoto_plugin_gcp/resources/sqladmin.py
plugins/gcp/test/test_sqladmin.py

`GcpSqlOperation` needs `GcpDatabaseInstance` as [query parameter](https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1/operations/list)

[gcp][fix] GcpSqlOperation needs GcpDatabaseInstance as query parameter

---

resotolib/resotolib/utils.py
resotolib/test/test_utils.py

Fixed the resolve env vars method to not remove the nulls
- Fixes #XXXX

[resotocore][fix] Do not remove nulls from the config on reading

---

plugins/aws/resoto_plugin_aws/__init__.py
resotolib/resotolib/baseplugin.py
resotolib/resotolib/config.py
resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/config.py
resotoworker/resotoworker/pluginloader.py

This PR implements auto enablement of collector plugins.
A `BaseCollectorPlugin` can now implement an `auto_enabled()` method that returns a bool whether the collector should be enabled or not. The default for all collectors is `False`.
This PR also implements `auto_enabled()` for the AWS collector.

[resoto][feat] auto enablement of collector plugins

---

plugins/gcp/resoto_plugin_gcp/project_collector.py
plugins/gcp/resoto_plugin_gcp/resources/base.py
plugins/gcp/test/test_project_collector.py

Removes nodes (`gcp_machine_type`, `gcp_disk_type`, `gcp_sku`, `gcp_service`) from the graph when they're not referenced.

[gcp][feat] Remove unreferenced nodes from graph

---

resotocore/resotocore/web/tsdb.py

Valid requests are failing with Code 400 for TSDB proxy requests.
This PR adds:
- logging for failing requests
- connection close
- retry failing requests

[resotocore][fix] Strip request specific headers and retry

---

resotolib/requirements.txt

Pin attrs since cattrs only depends on
```
attrs = ">= 20"
```
which makes `cloud2sql` fail on systems that come with an old attrs version pre-installed.

[resotolib][fix] Pin attrs

---

resotolib/requirements-test.txt
resotoworker/resotoworker/pluginloader.py

Return empty list when no collectors are configured

[resotoworker][fix] Return empty list when no collectors are configured

---

resotocore/resotocore/infra_apps/local_runtime.py
resotolib/resotolib/asynchronous/utils.py

Make infra apps execute full lines not chunks.
Also refactors some of the template args to be passed as args not put in the global space.

[resotocore][fix] Make infra apps execute full lines not chunks

---

resotocore/resotocore/cli/command.py

`job update` had wrong arg signature in help text.
This also makes it so that job update doesn't add new jobs and the `--id` arg is required on updates.

[resotocore][fix] `job update` had wrong arg signature

---

.github/workflows/publish.yml

Since the build step is expected to fail sometimes (e.g., when there are API changes to non-edge versions), split optimize & format into a separate step so that they still run.

[ci][chore] Split optimize/format from build step

---

.vscode/settings.json
plugins/digitalocean/resoto_plugin_digitalocean/collector.py

Digitalocean collector will fill in the backends field when collecting load balancers. Also, a small vscode configuration improvement. 
- Fixes #1316  (partly, only the Digitalocean part of the problem)

[plugins/digitalocean] Fill in backends when collecting load balancers.

---

resotoworker/Makefile
resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/config.py
resotoworker/test/test_args.py

Define configuration to allow the path to be used as a key.
This way, having two entries with the same path is impossible.

[resotoworker][feat] Define home-directory files as dict

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/configuration.py
plugins/aws/resoto_plugin_aws/utils.py

Set default region on all sessions.
This makes it so that every session that is created, has the partition's global region set as default. A client can then override the region with their own choice of region or if not specified (e.g. IAM) it will use the correct global region for the accounts partition.

[plugins/aws][fix] Set default region on all sessions

---

resotocore/resotocore/analytics/__init__.py
resotocore/resotocore/task/task_handler.py
resotocore/tests/resotocore/task/task_handler_test.py

[resotocore][feat] Send analytics event on action error

---

plugins/aws/resoto_plugin_aws/configuration.py
plugins/aws/test/configuration_test.py

Define `collect` and `no_collect` with GLOB style wildcards.
Example:
```yaml:
collect:
- ec?
no_collect:
- *sagemaker*
```

[aws][feat] Allow glob style service filters

---

resotocore/resotocore/cli/cli.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/cli/model.py
resotocore/resotocore/report/__init__.py
resotocore/tests/resotocore/report/benchnmark_renderer_test.py

Add a command line flag for the `report` command, which allows filtering only report checks.
This is useful in combination with other commands that expect entity JSON objects.
Example: 
```
report benchmark run aws_cis_1_5 --accounts 7524xxxxxx --only-failing --only-check-results | discord --title "Security Benchmark Issues!\nAccount 7524xxxxxx does not adhere to AWS CIS 1.5"
```

[resotocore][feat] Allow filtering of report checks

---

plugins/aws/resoto_plugin_aws/aws_client.py
plugins/aws/test/aws_client_test.py

AWS decided to respond with a ThrottlingError for services in the China partition, that are not available.
Since we can not distinguish whether the service is unavailable or the call was throttled, we have a hard coded list of services that are partially unavailable in the China partition (API is not covered 100%).

[aws][fix] Handle unavailable resources in China

---

resotocore/resotocore/cli/command.py
resotocore/tests/resotocore/cli/command_test.py

Current new commands are not displayed via `help`

[resotocore][fix] Put commands into correct category

---

resotocore/resotocore/model/model.py
resotocore/tests/resotocore/hypothesis_extension.py
resotocore/tests/resotocore/model/model_test.py

pyyamls indent parameter should not be used for indenting the value.

[resotocore][fix] Invalid yaml generation

---

.github/workflows/check_pr_plugin_aws.yml
.github/workflows/check_pr_plugin_gcp.yml
.github/workflows/create_plugin_workflows.py
plugins/gcp/resoto_plugin_gcp/collector.py
plugins/gcp/resoto_plugin_gcp/gcp_client.py
plugins/gcp/resoto_plugin_gcp/resources/base.py
plugins/gcp/resoto_plugin_gcp/resources/billing.py
plugins/gcp/resoto_plugin_gcp/resources/compute.py
plugins/gcp/resoto_plugin_gcp/resources/container.py
plugins/gcp/resoto_plugin_gcp/resources/sqladmin.py
plugins/gcp/resoto_plugin_gcp/resources/storage.py
plugins/gcp/test/test_collector.py
plugins/gcp/tools/gcppolicygen/MANIFEST.in
plugins/gcp/tools/gcppolicygen/README.md
plugins/gcp/tools/gcppolicygen/gcppolicygen/__init__.py
plugins/gcp/tools/gcppolicygen/gcppolicygen/__main__.py
plugins/gcp/tools/gcppolicygen/gcppolicygen/gen.py
plugins/gcp/tools/gcppolicygen/gcppolicygen/upload.py
plugins/gcp/tools/gcppolicygen/requirements-test.txt
plugins/gcp/tools/gcppolicygen/requirements.txt
plugins/gcp/tools/gcppolicygen/setup.cfg
plugins/gcp/tools/gcppolicygen/setup.py
plugins/gcp/tools/gcppolicygen/tox.ini

Extract the required permissions required for GCP.
Towards: #1487 
The permissions are created by analyzing all the API Calls made  in the collector.
This is the current result.
```
title: resoto_access
description: Permissions required to collect resources.
stage: GA
includedPermissions:
- cloudsql.backupRuns.list
- cloudsql.databases.list
- cloudsql.instances.get
- cloudsql.instances.list
- cloudsql.users.list
- compute.acceleratorTypes.list
- compute.addresses.list
- compute.autoscalers.list
- compute.backendBuckets.list
- compute.backendServices.list
- compute.commitments.list
- compute.diskTypes.list
- compute.disks.list
- compute.externalVpnGateways.list
- compute.firewalls.list
- compute.forwardingRules.list
- compute.globalOperations.list
- compute.healthChecks.list
- …
```

[gcp][feat] Export all required GCP permissions

---

.github/workflows/publish.yml

Adds the required env var for model generation only to a new file `docker-compose-model-gen.yaml`.
(This change isn't required for edge, but I added it to both jobs for consistency and to avoid "polluting" the Compose file in case we ever need to use the file elsewhere -- should prevent this oversight from occurring again.)
The `yq` commands were verified/tested locally.

[ci][fix] Publish docker-compose.yaml without RESOTOWORKER_OVERRIDE env

---

resotocore/resotocore/__main__.py
resotocore/resotocore/core_config.py
resotocore/resotocore/dependencies.py
resotocore/resotocore/util.py
resotocore/resotocore/web/certificate_handler.py
resotocore/tests/resotocore/core_config_test.py
resotocore/tests/resotocore/web/api_test.py
resotocore/tests/resotocore/web/certificate_handler_test.py
resotolib/resotolib/asynchronous/web/runner.py

`resotocore` now provides a port for SSL-encrypted HTTP and another for plain HTTP.

[feat][resotocore] Serve https and http requests

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/cli/command_test.py

Use a plain name for the local file and leave the user path untouched.
Only send the path header if the user path is more than a file name.

[resotocore][fix] Do not send path for file names

---

plugins/gcp/resoto_plugin_gcp/resources/base.py

This log on info level makes no sense. Results in these redundant messages:
```
23-06-29 01:48:22|resotoworker-gcp| INFO|3960|gcp_maestro-229419_28  Collecting GcpNotificationEndpoint for project maestro-229419 in region gcp_region us-west2
23-06-29 01:48:22|resotoworker-gcp| INFO|3960|gcp_maestro-229419_28  [Gcp:maestro-229419] Collecting GcpNotificationEndpoint with ({})
```
- Fixes #XXXX

[plugins/gcp][fix] Make redundant logging debug level

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
resotocore/resotocore/model/graph_access.py
resotocore/resotocore/model/model.py
resotocore/tests/resotocore/db/graphdb_test.py

Usage is stored as the list of values in the db, ec2 instances metrics are only collected if the instance status is running.

[resotocore] Fix the usage datapoints representation and only collect metrics from running instances

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/configuration.py
plugins/digitalocean/resoto_plugin_digitalocean/__init__.py
plugins/dockerhub/resoto_plugin_dockerhub/__init__.py
plugins/gcp/resoto_plugin_gcp/__init__.py
plugins/k8s/resoto_plugin_k8s/__init__.py
plugins/slack/resoto_plugin_slack/__init__.py
resotolib/resotolib/baseplugin.py
resotolib/resotolib/graph/__init__.py
resotoworker/resotoworker/__main__.py
resotoworker/resotoworker/collect.py
resotoworker/resotoworker/config.py
resotoworker/resotoworker/resotocore.py
resotoworker/test/test_collect.py

Send individual accounts to Resoto Core to conserve memory.
This PR makes merge on account level the default and sends individual accounts to Resoto Core as soon as they are available, to free up the memory they use.
This removes all post_collect code since we no longer have a complete graph of all clouds in memory. The plugins aws_k8s and digitalocean_k8s need to be rewritten to use the post_collect event, search the core instead of in-memory graph and send deferred edges to the core. Likely the better approach anyways since this allows us to collect different clouds on different workers instead of relying on all K8S cluster being collected on the same worker their cloud is collected on.
By submitting this pull request, I agree to follow the [code of …

[resoto][feat] Send individual accounts to Resoto Core

---

plugins/aws/resoto_plugin_aws/__init__.py
plugins/aws/resoto_plugin_aws/configuration.py
plugins/aws/tools/awspolicygen/awspolicygen/gen.py

Get AWS account name from organization. This is fully backwards compatible with the current naming scheme but if an account alias can not be found an attempt is made to get the account name via the organization. Since this requires root or delegated admin permissions (just like list_accounts) if a scrape org ARN is specified it is assumed for this operation. 
Additionally this introduces a config flag that allows you to specify whether you prefer the account alias or the org account name to be used as the account name.
Also the generated IAM permissions are updated.

[aws][feat] Get AWS account name from organization

---

resotocore/resotocore/model/resolve_in_graph.py
resotocore/resotocore/report/__init__.py
resotocore/resotocore/report/inspector_service.py
resotocore/resotocore/web/directives.py
resotocore/tests/resotocore/report/inspector_service_test.py

Every check result now contains head data of failing resources.
The change is backward compatible, so all clients should still behave correctly.

[feat] Add resource base data to the benchmark result

---

plugins/azure/resoto_plugin_azure/resource/compute.py
plugins/azure/test/collector_test.py
plugins/azure/test/compute_test.py
plugins/azure/test/conftest.py
plugins/azure/test/files/compute/availabilitySets.json
plugins/azure/test/files/compute/capacityReservationGroups.json
plugins/azure/test/files/compute/disks.json
plugins/azure/test/files/compute/restorePointCollections.json
plugins/azure/test/files/compute/snapshots.json
plugins/azure/test/files/compute/virtualMachines.json
plugins/azure/tools/azure_model_gen.py

I have introduced the following relationships to the reference_kinds:
```graph
AzureAvailabilitySet -> AzureProximityPlacementGroup -> AzureVirtualMachine
AzureCapacityReservationGroup -> AzureVirtualMachine
AzureDisk <- AzureDiskAccess -> AzureDiskEncryptionSet
AzureRestorePointCollection -> AzureResource
AzureSnapshot <- AzureDisk
AzureVirtualMachine -> AzureProximityPlacementGroup -> AzureImage -> AzureDisk
```
And I have implemented the connect_in_graph method to support these relationships.

[feat] [azure] Define Resource Relationship for all Azure compute resources

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/config/config_handler_service.py
resotocore/resotocore/config/core_config_handler.py
resotocore/resotocore/report/__init__.py
resotocore/resotocore/report/inspector_service.py
resotocore/resotocore/static/api-doc.yaml
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/config/core_config_handler_test.py
resotocore/tests/resotocore/report/inspector_service_test.py

A previously synced benchmark result can be loaded and shows the same data.
This PR introduces a command (`report benchmark load`) and provides an endpoint to load a benchmark result instead of performing it. 

[feat][resotocore] Allow loading synchronized benchmarks

---

resotocore/resotocore/__main__.py
resotocore/resotocore/dependencies.py
resotocore/resotocore/model/model_handler.py
resotocore/resotocore/report/inspector_service.py
resotocore/resotocore/web/directives.py
resotocore/tests/resotocore/conftest.py
resotocore/tests/resotocore/report/inspector_service_test.py

[feat][resotocore] Load static benchmarks and checks in multi-tenant mode

---

resotocore/resotocore/cli/cli.py
resotocore/resotocore/db/arango_query.py
resotocore/resotocore/query/model.py
resotocore/resotocore/query/query_parser.py
resotocore/resotocore/report/inspector_service.py
resotocore/tests/resotocore/cli/cli_test.py
resotocore/tests/resotocore/db/arango_query_test.py
resotocore/tests/resotocore/query/query_parser_test.py
resotoshell/resotoshell/promptsession.py

[feat][resotocore] Implement aggregate over arrays

---

plugins/aws/tools/awspolicygen/awspolicygen/__init__.py
plugins/gcp/tools/gcppolicygen/gcppolicygen/__init__.py

[aws|gcp][fix] Revert __init__.py changes

---

requirements-all.txt
requirements-test.txt
resotocore/resotocore/web/certificate_handler.py
resotocore/tests/resotocore/web/certificate_handler_test.py

A CA certificate passed to --ca-cert is added to the client SSL context.

[resotocore][feat] --ca-cert is added to the client context

---

resotolib/resotolib/web/__init__.py
resotoworker/resotoworker/__main__.py

[resotolib][feat] Support extra args to the webserver

---

plugins/azure/resoto_plugin_azure/azure_client.py
plugins/azure/resoto_plugin_azure/resource/base.py
plugins/azure/test/conftest.py

Resource deletion was implemented:
1. Implementation of Generic Delete Resource Function:
* Implemented a generic delete resource method that can be utilized for deleting Azure resources 
2. Update to AzureResource for Resource Deletion:
* Integrated the generic delete resource method into the Azure Resource class, enabling deletion of resources by retrieving the client and invoking the delete by id resource method

Implement delete of a resource

---

plugins/aws/resoto_plugin_aws/resource/ec2.py
plugins/azure/resoto_plugin_azure/collector.py
plugins/azure/resoto_plugin_azure/resource/compute.py
plugins/azure/resoto_plugin_azure/resource/network.py
plugins/azure/tools/azure_model_gen.py
plugins/gcp/resoto_plugin_gcp/resources/compute.py
plugins/gcp/resoto_plugin_gcp/resources/sqladmin.py
plugins/k8s/resoto_plugin_k8s/base.py

- Remove useless resources
- Fix overlapping properties

[azure][fix] Fix model and remove useless resources

---

plugins/aws/resoto_plugin_aws/resource/base.py
plugins/aws/resoto_plugin_aws/resource/cognito.py
plugins/digitalocean/resoto_plugin_digitalocean/resources.py
plugins/gcp/resoto_plugin_gcp/resources/base.py
resotolib/resotolib/baseresources.py

[resotoworker][fix] Do not use the name to compute the resource identifier

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/model/graph_access.py
resotocore/tests/resotocore/cli/command_test.py

[resotocore][feat] Add list table output

---

resotocore/resotocore/model/exportable_model.py
resotocore/resotocore/model/model.py
resotocore/resotocore/web/api.py
resotolib/resotolib/core/model_export.py
resotolib/resotolib/graph/__init__.py

[resotolib][feat] ModelExport: include name and description

---

resotocore/resotocore/db/graphdb.py
resotocore/resotocore/report/inspector_service.py

[resotocore][fix] Filter accounts when marking resources as compliant

---

resotocore/resotocore/cli/command.py
resotocore/tests/resotocore/cli/command_test.py

[resotocore][fix] Make list column unique

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/cli/model.py
resotocore/resotocore/db/arango_query.py
resotocore/resotocore/db/async_arangodb.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/infra_apps/local_runtime.py
resotocore/resotocore/query/model.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/db/graphdb_test.py

The search and cli/execute endpoint now return 2 additional headers:
```
Result-Count: 1
Total-Count: 61
```
One indicating the number of elements returned within this response, the other one shows the number of all available elements. There will be only a difference if a limit is applied to the search.

[resotocore][feat] Enable count and total count for search queries

---

resotocore/resotocore/cli/__init__.py
resotocore/tests/resotocore/cli/cli_test.py
resotolib/resotolib/parse_util.py

[resotocore][fix] args parser needs to allow empty space

---

requirements-all.txt
requirements-extra.txt
requirements-test.txt
requirements.txt
resotocore/.pylintrc
resotocore/pyproject.toml
resotocore/resotocore/cli/__init__.py
resotocore/resotocore/cli/cli.py
resotocore/resotocore/cli/command.py
resotocore/resotocore/cli/model.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/infra_apps/local_runtime.py
resotocore/resotocore/model/db_updater.py
resotocore/resotocore/report/benchmark_renderer.py
resotocore/resotocore/report/inspector_service.py
resotocore/resotocore/task/task_handler.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/cli/cli_test.py
resotocore/tests/resotocore/cli/command_test.py
resotolib/pyproject.toml

[resoto][chore] Bump aiostream to latest version

---

plugins/azure/resoto_plugin_azure/azure_client.py
plugins/azure/resoto_plugin_azure/collector.py
plugins/azure/resoto_plugin_azure/resource/base.py
plugins/azure/resoto_plugin_azure/resource/compute.py
plugins/azure/resoto_plugin_azure/resource/network.py
plugins/azure/test/collector_test.py
plugins/azure/test/compute_test.py
plugins/azure/test/conftest.py
plugins/azure/test/files/compute/virtualMachines.json
plugins/azure/test/files/compute/vmSizes.json
plugins/azure/test/network_test.py

Filter virtual machine sizes to retain only those associated with existing virtual machines.

[azure] [feat] Filter virtual machine sizes

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/db/graphdb.py
resotocore/resotocore/web/api.py
resotocore/tests/resotocore/cli/command_test.py
resotocore/tests/resotocore/db/graphdb_test.py

[resotocore][feat] Allow history search with multiple change types

---

resotocore/resotocore/core_config.py
resotocore/resotocore/db/graphdb.py
resotocore/tests/resotocore/core_config_test.py

[resotocore][feat] Allow configuring history duration

---

resotocore/resotocore/static/report/checks/aws/aws_acm.json

per https://docs.aws.amazon.com/acm/latest/APIReference/API_CertificateOptions.html#ACM-Type-CertificateOptions-CertificateTransparencyLoggingPreference
AWS ACM returns ENABLED|DISABLED for this option

[resotocore][fix] fix case for certificate_transparency_logging value

---

.github/workflows/publish.yml

Allow for manual re-runs of the publish workflow when dependent actions/checks fail on tagged releases.

[ci][chore] Bypass waits when publish workflow triggered manually

---

resotocore/resotocore/cli/command.py
resotocore/resotocore/model/model.py
resotocore/tests/resotocore/cli/command_test.py

[resotocore][feat] introduce refine-resource-data command

---

.github/workflows/docker-build.yml

[inventory][fix] do not publish resoto images

---

fixcore/fixcore/__main__.py
fixcore/fixcore/cli/command.py
fixcore/fixcore/db/db_access.py
fixcore/fixcore/db/graphdb.py
fixcore/fixcore/db/system_data_db.py
fixcore/fixcore/graph_manager/graph_manager.py
fixcore/tests/fixcore/graph_manager/graph_manager_test.py

If there is an existing `resoto` database but no `fix` database, fixinventory will try to connect to the `resoto` database. This was the default behavior in previous versions. Existing users will continue using the `resoto` database.
The `resoto` graph is renamed to `fix` during startup. 
The configuration items known to fix get renamed and adjusted to use the `fix` graph.
All other configuration items get deleted.

[fixcore][feat] Migrate existing resoto data and configs

---

fixlib/fixlib/core/ca.py

Cryptography now prefers timezone aware datetimes. 

[fixlib][fix] Fix Cryptography deprecation warning

---

docker-compose.yaml

When a user schedules a job and writes to the download directory, it will have the same effect as executed from within the shell.

[docker][feat] same downloads folder for core and shell

---

.github/workflows/publish.yml

Workflow runs don't necessarily complete in the order that they were submitted, which is problematic when created PRs are overwritten with data generated from an earlier commit.
For the publish workflow, we only care about the latest commit to main, so any currently running jobs can and should be canceled.
**Note:** Due to the defined concurrency group, tagged releases will not be terminated.

[ci][fix] Limit concurrent publish workflow runs on main

---

plugins/aws/fix_plugin_aws/resource/base.py
plugins/aws/fix_plugin_aws/resource/cloudwatch.py
plugins/aws/fix_plugin_aws/resource/ec2.py
plugins/aws/fix_plugin_aws/resource/elbv2.py

[aws][fix]: Fix query stat for cloudwatch metric requests

---

fixlib/fixlib/baseplugin.py
fixlib/fixlib/graph/__init__.py
fixlib/test/test_graph.py
fixworker/fixworker/collect.py
fixworker/fixworker/config.py
fixworker/test/test_collect.py
plugins/aws/fix_plugin_aws/__init__.py
plugins/aws/fix_plugin_aws/collector.py
plugins/azure/fix_plugin_azure/__init__.py
plugins/azure/fix_plugin_azure/collector.py
plugins/digitalocean/fix_plugin_digitalocean/__init__.py
plugins/digitalocean/fix_plugin_digitalocean/collector.py
plugins/gcp/fix_plugin_gcp/__init__.py
plugins/gcp/fix_plugin_gcp/collector.py

This adds a config property `fixworker.max_resources_per_account` which defaults to `None`.
It also adds a `max_nodes` property to the `fixlib.graph.Graph` class. If the number of max nodes is exceeded during an `add_node()` operation a `MaxNodesExceeded` exception is thrown.
`BaseCollectorPlugin` now has a `max_resources_per_account` property. In `send_account_graph()`, the method that sends a plugin's account graph to the core (if `merge_kind = account`) or merges it into the global graph (if `merge_kind = cloud`) a check is performed to see whether the number of nodes in the account graph exceeds the max configured. If yes, the account graph is discarded. This acts as a safety net in case the collector plugin messes up.
Ideally a too large account graph should never reach the …

[fixinventory][feat] Add ability to specify max number of resources per account

---

fixcore/fixcore/db/arango_query.py
fixcore/tests/fixcore/db/arango_query_test.py

[core][fix] Context query with array with or

---

fixcore/fixcore/core_config.py

Properties marked as optional are handled as required in the configuration.
This leads to issues with custom commands.

[core][fix] Treat optional config properties as such

---

fixcore/fixcore/cli/command.py
fixcore/fixcore/db/arango_query.py
fixcore/fixcore/db/timeseriesdb.py
fixcore/tests/fixcore/db/arango_query_test.py
fixcore/tests/fixcore/db/timeseriesdb_test.py

Computing the average with big numbers can lead to an overflow in ArangoDB.
This PR applies a factor to all values before the avg is computed.
Related issue is this: https://github.com/arangodb/arangodb/issues/21096

[core][feat] TimeSeries: allow defining a factor for computing the average

---

plugins/azure/fix_plugin_azure/resource/containerservice.py

Fleet members can have different cluster references, allowing them to connect to various clusters instead of just one.

[azure][fix]: Reimplemented fleet and clusters connection

---

fixcore/fixcore/report/inspector_service.py

[core][fix] Use consistent reading when updating the account

---

plugins/azure/fix_plugin_azure/resource/mysql.py
plugins/azure/fix_plugin_azure/resource/postgresql.py
plugins/azure/fix_plugin_azure/utils.py
plugins/azure/test/collector_test.py
plugins/azure/test/files/mysql/configurations.json
plugins/azure/test/files/postgresql/configurations.json

[azure][feat]: Update configs collection for mysql and postgresql

---

plugins/azure/fix_plugin_azure/collector.py
plugins/azure/fix_plugin_azure/resource/authorization.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/resource/compute.py
plugins/azure/fix_plugin_azure/resource/containerservice.py
plugins/azure/fix_plugin_azure/resource/keyvault.py
plugins/azure/fix_plugin_azure/resource/monitor.py
plugins/azure/fix_plugin_azure/resource/mysql.py
plugins/azure/fix_plugin_azure/resource/network.py
plugins/azure/fix_plugin_azure/resource/sql_server.py
plugins/azure/fix_plugin_azure/resource/storage.py
plugins/azure/fix_plugin_azure/resource/web.py
plugins/azure/fix_plugin_azure/utils.py
plugins/azure/test/collector_test.py
plugins/azure/test/files/resources/locks.json
plugins/azure/test/files/web/certificates.json
plugins/azure/test/files/web/containerApps.json
plugins/azure/test/files/web/domains.json
plugins/azure/test/files/web/hostingEnvironments.json
plugins/azure/test/files/web/kubeEnvironments.json
plugins/azure/test/files/web/list.json
plugins/azure/test/files/web/serverfarms.json
plugins/azure/test/files/web/sites.json
plugins/azure/test/files/web/staticSites.json
plugins/azure/test/web_test.py
plugins/azure/tools/azure_model_gen.py

[azure][feat] Add WebApp

---

fixcore/fixcore/db/arango_query.py

The view only yields some results correctly when using nested array searches.
With this PR, the view is no longer used; it uses plain old filters instead.

[core][fix] Do not use arangosearch for nested array context searches

---

fixlib/fixlib/basecategories.py
fixlib/fixlib/baseresources.py
fixlib/fixlib/core/model_check.py
fixlib/fixlib/core/model_export.py
fixlib/test/test_basecategories.py
fixlib/test/test_config.py
plugins/aws/fix_plugin_aws/collector.py
plugins/aws/fix_plugin_aws/resource/amazonq.py
plugins/aws/fix_plugin_aws/resource/cloudformation.py
plugins/aws/fix_plugin_aws/resource/cloudfront.py
plugins/aws/fix_plugin_aws/resource/cloudtrail.py
plugins/aws/fix_plugin_aws/resource/cloudwatch.py
plugins/aws/fix_plugin_aws/resource/config.py
plugins/aws/fix_plugin_aws/resource/ec2.py
plugins/aws/fix_plugin_aws/resource/kms.py
plugins/aws/fix_plugin_aws/resource/redshift.py
plugins/aws/fix_plugin_aws/resource/s3.py
plugins/aws/fix_plugin_aws/resource/sagemaker.py
plugins/aws/fix_plugin_aws/resource/ssm.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/fix_plugin_azure/resource/compute.py
plugins/azure/fix_plugin_azure/resource/cosmosdb.py
plugins/azure/fix_plugin_azure/resource/keyvault.py
plugins/azure/fix_plugin_azure/resource/machinelearning.py
plugins/azure/fix_plugin_azure/resource/monitor.py
plugins/azure/fix_plugin_azure/resource/postgresql.py
plugins/azure/fix_plugin_azure/resource/security.py
plugins/azure/fix_plugin_azure/resource/storage.py
plugins/gcp/fix_plugin_gcp/resources/billing.py
plugins/gcp/fix_plugin_gcp/resources/compute.py

Unify groups and categories:
- Category: `iam` --> `access_control`
- Group: `control` --> `management`
- Group: `generative_ai` --> `ai`
- Add the group to the set of categories
- Export categories as part of the model

[lib][feat] Unify groups and categories

---

fixcore/fixcore/db/db_access.py
fixcore/fixcore/db/graphdb.py
fixcore/fixcore/db/model.py
fixcore/fixcore/model/graph_access.py
fixcore/tests/fixcore/conftest.py

[core][fix] Persist parent update structure in an atomic way

---

plugins/aws/fix_plugin_aws/resource/backup.py
plugins/aws/fix_plugin_aws/resource/dynamodb.py
plugins/aws/fix_plugin_aws/resource/ecr.py
plugins/aws/fix_plugin_aws/resource/efs.py
plugins/aws/fix_plugin_aws/resource/kinesis.py
plugins/aws/fix_plugin_aws/resource/sns.py
plugins/aws/test/resources/backup_test.py
plugins/aws/test/resources/dynamodb_test.py
plugins/aws/test/resources/ecr_test.py
plugins/aws/test/resources/kinesis_test.py

[aws][feat]: Add more policies to collect

---

fixcore/fixcore/db/arango_query.py
fixcore/fixcore/db/async_arangodb.py
fixcore/tests/fixcore/db/graphdb_test.py

[core][fix] Merge edge and vertex and unfold in code

---

fixlib/fixlib/core/model_export.py
fixlib/test/core/model_export_test.py

Add a source attribute to the kind metadata section.
Example:
```json
[
{ "fqn": "resource", "metadata": { "source": "base" } },
{ "fqn": "instance", "metadata": { "source": "base" } }
{ "fqn": "aws_resource", "metadata": { "source": "aws" } },
{ "fqn": "aws_ec2_instance", "metadata": { "source": "aws" } }
]
```

[fixlib][feature] Add the source of resource kind

---

fixlib/fixlib/baseresources.py
fixlib/fixlib/graph/__init__.py
fixlib/fixlib/json_bender.py
plugins/aws/fix_plugin_aws/collector.py
plugins/aws/fix_plugin_aws/resource/base.py
plugins/aws/fix_plugin_aws/resource/sqs.py
plugins/azure/fix_plugin_azure/collector.py
plugins/azure/fix_plugin_azure/resource/base.py
plugins/azure/test/collector_test.py
plugins/azure/test/machinelearning_test.py
plugins/gcp/fix_plugin_gcp/collector.py
plugins/gcp/fix_plugin_gcp/resources/base.py
plugins/gcp/test/test_collector.py

[inventory][fix] Better detect and remove unused regions

---

.github/workflows/publish.yml
fixcore/fixcore/__main__.py
fixcore/fixcore/system_start.py
fixlib/fixlib/core/model_export.py

[core][feat] Allows retrieving the model from plugins instead of db

---

fixlib/fixlib/baseresources.py
plugins/aws/fix_plugin_aws/resource/kinesis.py

Make resource_policy abstract method to trigger typecheck

---

fixlib/fixlib/baseresources.py
fixlib/fixlib/core/model_export.py

[fixlib][feat] Define separate assessment section

---

fixcore/.pylintrc
fixcore/fixcore/cli/__init__.py
fixcore/fixcore/cli/cli.py
fixcore/fixcore/cli/command.py
fixcore/fixcore/cli/model.py
fixcore/fixcore/db/graphdb.py
fixcore/fixcore/infra_apps/local_runtime.py
fixcore/fixcore/model/db_updater.py
fixcore/fixcore/report/benchmark_renderer.py
fixcore/fixcore/report/inspector_service.py
fixcore/fixcore/task/task_handler.py
fixcore/fixcore/web/api.py
fixcore/pyproject.toml
fixcore/tests/fixcore/cli/command_test.py
fixcore/tests/fixcore/db/graphdb_test.py
fixcore/tests/fixcore/hypothesis_extension.py
fixcore/tests/fixcore/report/benchmark_renderer_test.py
fixcore/tests/fixcore/util_test.py
fixcore/tests/fixcore/web/content_renderer_test.py
fixlib/fixlib/asynchronous/stream.py
fixlib/test/asynchronous/stream_test.py
fixshell/.pylintrc
requirements-all.txt
requirements-extra.txt
requirements.txt

[core][feat] Add Async Streams abstraction

---

plugins/gcp/fix_plugin_gcp/collector.py
plugins/gcp/fix_plugin_gcp/resources/aiplatform.py
plugins/gcp/fix_plugin_gcp/resources/firestore.py
plugins/gcp/test/aiplatform_test.py
plugins/gcp/test/files/aiplatform_resources.json
plugins/gcp/test/files/firestore_backup.json
plugins/gcp/test/files/firestore_database.json
plugins/gcp/test/files/firestore_document.json
plugins/gcp/test/firestore_test.py
plugins/gcp/tools/model_gen.py

[gcp][feat] Add firestore service collection

---

plugins/gcp/fix_plugin_gcp/collector.py
plugins/gcp/fix_plugin_gcp/resources/filestore.py
plugins/gcp/test/files/filestore_backup.json
plugins/gcp/test/files/filestore_instance.json
plugins/gcp/test/files/filestore_instance_snapshot.json
plugins/gcp/test/test_filestore.py
plugins/gcp/tools/model_gen.py

[gcp][feat] Add filestore service collection

---

plugins/gcp/fix_plugin_gcp/collector.py
plugins/gcp/fix_plugin_gcp/resources/cloudfunctions.py
plugins/gcp/test/files/cloudfunctions.json
plugins/gcp/test/test_cloudfunctions.py
plugins/gcp/tools/model_gen.py

[feat][gcp] Add cloudfunctions service collection

---

plugins/gcp/fix_plugin_gcp/gcp_client.py
plugins/gcp/fix_plugin_gcp/resources/base.py
plugins/gcp/fix_plugin_gcp/resources/billing.py
plugins/gcp/fix_plugin_gcp/resources/compute.py
plugins/gcp/test/test_billing.py
plugins/gcp/test/test_compute.py

[feat][gcp] Improve the way of collection for DiskTypes and MachineTypes

---

fixcore/fixcore/static/api-doc.yaml

[core][chore] Remove "Experimental" disclaimers from API documentation.

---

.github/workflows/check_pr_plugin_aws.yml
.github/workflows/check_pr_plugin_gcp.yml
.github/workflows/create_plugin_workflows.py
.github/workflows/publish.yml

[fix][chore] Do not use S3/CDN in GitHub actions

---

fixlib/fixlib/config.py
fixlib/fixlib/tree.py
fixlib/fixlib/utils.py
fixlib/test/test_utils.py

This PR fixes some typos in [`fixlib`](https://github.com/someengineering/fixinventory/tree/main/fixlib). Similar to #2303.
I decided not to create an issue for such a small change. If you think it is needed, please let me know.

[docs][fixlib] Fix some typos in doc-strings

---

plugins/k8s/test/resources_test.py

Another _typo-like-fix_: removes the duplicated `pytest` import.

[plugins/k8s][style] Remove duplicated `pytest` import

---

fixcore/tests/fixcore/model/model_test.py
fixcore/tests/fixcore/util_test.py
plugins/aws/fix_plugin_aws/resource/dynamodb.py

This PR makes the code conformant with [F632](https://docs.astral.sh/ruff/rules/is-literal/#is-literal-f632)/[R0123](https://pylint.readthedocs.io/en/stable/user_guide/messages/refactor/literal-comparison.html).

[style] Do not use `is` to compare literals

---

fixcore/fixcore/model/typed_model.py
fixlib/test/core/model_export_test.py
plugins/azure/tools/azure_model_gen.py

This PR makes the code conformant with [E721](https://docs.astral.sh/ruff/rules/type-comparison/#type-comparison-e721).
Similar to #2314.

[style] Use `is` to compare types

---

.github/ISSUE_TEMPLATE/config.yml
README.md
fixcore/README.md
fixlib/README.md
fixmetrics/README.md
fixshell/README.md
fixworker/README.md

[fix][fix] Update Discord server invitation links

---

fixcore/pyproject.toml
fixlib/pyproject.toml
fixmetrics/pyproject.toml
fixshell/pyproject.toml
plugins/aws/pyproject.toml
plugins/aws/tools/awspolicygen/setup.py
plugins/azure/pyproject.toml
plugins/digitalocean/pyproject.toml
plugins/dockerhub/pyproject.toml
plugins/example_collector/pyproject.toml
plugins/gcp/pyproject.toml
plugins/gcp/tools/gcppolicygen/setup.py
plugins/github/pyproject.toml
plugins/hetzner/pyproject.toml
plugins/k8s/pyproject.toml
plugins/onelogin/pyproject.toml
plugins/posthog/pyproject.toml
plugins/random/pyproject.toml
plugins/scarf/pyproject.toml
plugins/slack/pyproject.toml

Just to make the intention clear although License classifiers are deprecated...

Fix some AGPL references that were left after returning to Apache2 
